### ISSUE TITLE
Deploy PM url not valid

### ISSUE THREAD

**Issue by maxime-crunding** [strongloop/strong-pm#104]
After building my application using Git onto deploy branch (http://docs.strongloop.com/display/public/SLC/Committing+a+build+to+Git)

The process manager is running on http://127.0.0.1:7777/ 
```
{"started":"2015-01-13T14:16:20.532Z","uptime":2131.081}
```

I can't deploy 
- via de command line
```
slc deploy http://localhost:7777 deploy
 URL `http://localhost:7777/default` is not valid
```
- neither via ARC

Should I do a full strongloop config on my LIVE server 1st and then from my localhost deploy ?

**Comment by rmg** [comment]
I predict you are running Mac OS 10.10, correct?

The most common cause for this is your OS supports IPv6 as well as IPv4 and `localhost` is resolving as `::1` instead of `127.0.0.1`. To get around this, specify `http://127.0.0.1:7777` as the URL you are deploying to.
