### ISSUE TITLE
Upgrade guide for strong-pm

### ISSUE THREAD

**Issue by crandmck** [strongloop/strong-pm#108]
Per Sam:
> We might need an upgrade guide for strong-pm, its a bit more than the normal `npm install -g strongloop`, so we should document it ...

See #45

**Comment by DeniseLee** [comment]
@rmg, @sam-github, @crandmck  Just following up on this. 

--In #45 @rmg says 
"Sorry, I was typing on my phone. I meant to spell out the restart commands.

    Upstart: initctl restart strong-pm
    systemd: systemctl restart strong-pm

When re-installing the systemd or Upstart service, it is probably a good idea to reload those job/service/unit configs.

    Upstart: initctl reload-configuration
    systemd: systemctl daemon-reload

All initctl and systemctl commands generally require root access, so run them in a root shell or with sudo."
---
Should I add these two commands into doc?
Upstart: initctl reload-configuration
    systemd: systemctl daemon-reload
Thanks!

**Comment by rmg** [comment]
Yes, it might be helpful to some users to mention those commands somewhere in the docs:
 * `sudo initctl reload-configuration`
 * `sudo systemctl daemon-reload`

They tell Upstart and systemd, respecitively, to reload their job configs so they are using the configs that were just generated with `sudo slc pm-install` or `sudo sl-pm-install`.

**Comment by DeniseLee** [comment]
@rmg, @sam-github Added this information to Installing Process Manager as a Service page.

Upgrading Note: When re-installing the systemd or Upstart service, it is a good idea to reload the job configurations that were just generated when you installed the Process Manager with sudo slc pm-install or sudo sl-pm-install.

For Upstart, use this command:
    sudo initctl reload-configuration
For systemd, use this command:
    sudo systemctl daemon-reload

**Comment by rmg** [comment]
The changes look good to me :-)

**Comment by sam-github** [comment]
@DeniseLee I'll go looking at the docs, to see if I can find this. Its helpful to include links to confluence after you've done something to speed up review.

**Comment by sam-github** [comment]
@DeniseLee Not having much luck. Links that I should review, please?

**Comment by DeniseLee** [comment]
So sorry @sam-github. Getting used to this process. Here's the link: http://docs.strongloop.com/display/SLC/Installing+Process+Manager+as+a+service.

**Comment by sam-github** [comment]
Use port 8701 for all example calls to pm-install, please (it will soon be the default, but best leave the docs for now but specify the default).

For upstart, some example system names are provided, but not for systemd. It would be useful to mention a couple prominent systemd distributions. Also, I could read the note to as meaning that systemd will be used when you use `--systemd`, but actually, it just won't work if the system doesn't have systemd and you specify `--systemd`. So, make it clear that you must use the option that corresponds with your system's process manager.

You don't use sudo in the first CLI snippets.but you do use it in the third. And I'm a bit confused as to why you have the third snippet, its identical to the second.

`sudo start strong-pm` - that works with upstart (both versions) and with systemd?

Logging Note: I think you should use replace "redirect" with "rotate", its more clear.

Logging Note: and with systemd.... logs go where?

Upgrading Note: first mention of sl-pm-install.... maybe it should be used all the time? But if it isn't mentioned anywhere else, it shouldn't be mentioned here.

Upgrading Note: "re-installing the systemd or Upstart service" and "installed the Process Manager" sound like two different things, but I think the service in the first phrase is the service file that gets generated by the second phrase? When I first read, I thought it meant re-installing systemd *itself*. Anyhow, I think the intention is to say "call pm-install to upgrade pm, and reload the configuration afterwards using `...`"

**Comment by DeniseLee** [comment]
Updated doc per comments. Sam, I have a review comment on the page for you regarding where systemd logs are stored. Thanks!

http://docs.strongloop.com/display/SLC/Installing+Process+Manager+as+a+service

**Comment by sam-github** [comment]
LGTM

@rmg can you look at this, Denise has one question about where systemd logs go (I don't know).

**Comment by rmg** [comment]
Everything run under systemd is logged to `journald`, which is accessible via the `journalctl` command. I think anyone using systemd should probably already be familiar with those mechanisms, so I don't think we need to document that in too much detail.

For convenience, our systemd service definitions _also_ log to syslog.

@DeniseLee does that give you enough information to make something readable by our users?

**Comment by sam-github** [comment]
I think somebody who just happens to be using systemd might not know about journalctl, and could use a pointer to it.

**Comment by DeniseLee** [comment]
@rmg, @sam-github. I updated the systemd log info as you've stated. How does it look? Thanks for your help!

**Comment by DeniseLee** [comment]
Here's the link: http://docs.strongloop.com/display/SLC/Installing+Process+Manager+as+a+service

**Comment by rmg** [comment]
Looks good. I see an open comment about how to check if the service is running.

For Upstart systems, the command and example output would be:
```
$ sudo status strong-pm
strong-pm start/running, process 1057
```

For systemd systems:
```
$ sudo systemctl status strong-pm
strong-pm.service - StrongLoop Process Manager
   Loaded: loaded (/etc/systemd/system/strong-pm.service; enabled)
   Active: active (running) since Mon 2015-03-09 20:51:33 UTC; 4min 13s ago
 Main PID: 1628 (node)
```

**Comment by DeniseLee** [comment]
@rmg, I'm sending this back to you for review. Do you want me to reassign to Sam or Rand? Thanks for your help.

**Comment by rmg** [comment]
LGTM.
