### ISSUE TITLE
implement inject-file support

### ISSUE THREAD

**Issue by sam-github** [strongloop/strong-pm#113]
As described in #61 by @rmg:

> I propose that it look/work something like this:
> 
> ```
> $ slc pmctl inject-file strongloop.json
> strong-pm: copying strongloop.json to strong-pm store...
> strong-pm: restarting application with injected files: strongloop.json
> $ slc pmctl inject-file production.env:.env
> strong-pm: copying production.env to strong-pm store...
> strong-pm: restarting application with injected files: .env strongloop.json
> $ slc pmctl inject-file strongloop.json
> strong-pm: copying strongloop.json to strong-pm store...
> strong-pm: injected files unchanged, not restarting
> $ slc pmctl files
> Current file injections and md5 hashes:
>   .env=production.env (5a0ea52ff2e3c7b4592e83303a3fa962)
>   strongloop.json=strongloop.json (07915d313e3d08bc83817f5e5286782e)
> ```
> 
> I would also like to expose this as a pm-install option, similar to how persisted environments are in #56 with something like:
> 
> ```
> $ sudo slc pm-install --port 7777 --inject-file strongloop.json --inject-file produciton.env:.env
> ```
> 
> Both would use a git refspec inspired mapping format of LOCAL:REMOTE with the following semantics:
> - `a:b` copy a, relative to local path to b relative to app root
> - `a` copy a relative to local path to a relative to app root
> - `:b` delete file at path b, relative to app root
>   - is this useful?
>   - if useful, is this syntax at all intuitive?
> - `a:` remove file a from strong-pm store
>   - I intend to store files by content hash, so this would involve performing a local hash and sending the hash to strong-pm for lookup and delete

**Comment by chandadharap** [comment]
@sam-github @rmg Please add a description even if short. chasing links is painful.

**Comment by rmg** [comment]
@chandadharap updated description.
