### ISSUE TITLE
Detect process start & crash (spinning) and indicate on the instance model

### ISSUE THREAD

**Issue by kraman** [strongloop/strong-pm#117]
@ritch and @seanbrookes request an API to detect a PM that attempts to start a broken app, detects the crashed pid and keeps trying to start it forever. This could be exposed as a `spinning` boolean flag on the instance model.

/cc @sam-github

**Comment by sam-github** [comment]
It is theoretically known to strong-supervisor (it makes an internal state change causing it to delay restart, that state change can be surfaced).

This is for remote PM, though, right? Because the arc-internal PM no longer restarts.

**Comment by kraman** [comment]
@sam-github yes, this is for a remote PM. When the Pm is spinning, the UI doesnt show any PIDs and since logs are not yet exposed, the user has no way of knowing.
