### ISSUE TITLE
"Ignore metrics" error on the pm server console

### ISSUE THREAD

**Issue by cgole** [strongloop/strong-pm#118]
App deployed on pm server throws this error on the pm console.

Not sure how to repro it. I have a basic loopback app deployed to a pm server on my mac and I keep getting these messages on the console.

Ignoring metrics for unknown worker: 1
Ignoring metrics for unknown worker: 2
Ignoring metrics for unknown worker: 3
Ignoring metrics for unknown worker: 4
Ignoring metrics for unknown worker: 5
Ignoring metrics for unknown worker: 6
Ignoring metrics for unknown worker: 7
Ignoring metrics for unknown worker: 8

**Comment by cgole** [comment]
https://github.com/strongloop/strong-arc/issues/965

**Comment by rmg** [comment]
This is coming from code added in af9e0cf8 and appears very intentional.
```js
Process.findOne(q, function(err, proc) {
  assert.ifError(err);
  if (!proc) {
    console.error('Ignoring metrics for unknown worker: %d', wid);
    // Metrics can show up after process death, or perhaps even before
    // supervisor knows they have forked. The timing is a bit
    // uncertain, don't rely on it.
    return asyncCb();
  }
  m.processId = proc.id;
  m.workerId = wid;
  m.timeStamp = req.metrics.timestamp;
  Metric.upsert(m, asyncCb);
});
```

@sam-github @kraman perhaps this should debug instead? Or maybe there's some way we can tighten up the timing?

**Comment by kraman** [comment]
@rmg yes I think this should be debug. I am not sure why agent is pushing up metrics for stale procs tho...

**Comment by sam-github** [comment]
@cgole @kraman if you find a reproducible case I'd like to know, but yes, for now better move it to debug.

**Comment by cgole** [comment]
not an issue anymore
