### ISSUE TITLE
Improve pm README

### ISSUE THREAD

**Issue by alexgorbatchev** [strongloop/strong-pm#121]
It's pretty confusing trying to figure out `strong-pm` at the moment. The README is not clear at all that `strong-pm` is part of an echo system which also includes `strong-build` and `strong-deploy`. I presume same goes for READMEs of all three modules. I think it needs to be made more clear that it's not really just a standalone process manager (in fact it's nothing like the popular `pm2` for example) and it works in conjunction with the other two.

**Comment by chandadharap** [comment]
@alexgorbatchev Thanks for the feedback, we have indeed been pondering about linking to the other README's from within each other. Perhaps its time to do that for strong-build, strong-deploy and strong-pm. 

But specifically to understand the ease of composition of these three modules, perhaps you might want to start with @sam-github 's blog http://strongloop.com/strongblog/node-js-deploy-production-best-practice/  and or read the documentation here http://docs.strongloop.com/display/SLC/Deploying+applications+with+slc

**Comment by rmg** [comment]
FWIW, pm2 is closer to strong-supervisor, which is what strong-pm uses internally to run apps that are deployed to it.

**Comment by sam-github** [comment]
@alexgorbatchev do you think the slc usage message gives a better idea of the relationship between the tools?  https://github.com/strongloop/strongloop/blob/master/man/slc.txt

**Comment by alexgorbatchev** [comment]
@sam-github looking at the slc.txt you do get a better grasp of the picture. One thing to keep in mind that generally node modules follows the "small module" mantra that do one thing well. Because of that, IMO, three separate modules working together message needs to be reenforced and be painfully obvious as it might not be immediately clear.

I would also remove `slc` command from the README as only complicated things further for a newcomer. I would make that a separate point that the pm/build/deploy do work just fine on their own BUT are also a part of this awesome echosystem while keeping example usage to commands that are actually installed with the modules.

**Comment by rmg** [comment]
@alexgorbatchev how did you find strong-pm? I'm curious because my own preference is for treating the modules as standalone like you suggest. I haven't been able to make a strong case for it because all of our docs and messaging tell people to `npm install -g strongloop` and almost hide the fact that the many `slc` commands are installable as standalone modules.

**Comment by alexgorbatchev** [comment]
@rmg I'm writing an article about it :)

**Comment by sam-github** [comment]
@alexgorbatchev The only reference to slc is the one liner alternative command in the usage: https://github.com/strongloop/strong-pm#slc-pm-install

Is that what threw you off?

I'm thinking about removing that, and somewhere sticking a note that strong-pm is part of the strongloop command line (... link to strongloop/strongloop, and mentioning the mapping from `sl-pm-install` to `slc pm-install`).

**Comment by alexgorbatchev** [comment]
> A hard stop is performed by killing the supervisor with SIGTERM. The signal is configurable, but we do not recommend changing it.
>
> A soft restart is performed by killing the supervisor with SIGHUP. The signal is configurable, and may be set to "no" to disable soft restart, but we do not recommend changing it.

This part is pretty confusing... it sounds like the supervisor is first SIGTERMed and then SIGHUPed... is one of this referring to the running application by chance?

**Comment by sam-github** [comment]
@alexgorbatchev I don't know where you found that text, and it leaves me a bit confused, too.

Is this clearer?  https://github.com/strongloop/strong-pm/blob/master/bin/sl-pmctl.txt#L27-L35

**Comment by alexgorbatchev** [comment]
last two paragraphs in https://github.com/strongloop/strong-pm/blob/master/README.md#life-cycle

**Comment by sam-github** [comment]
@alexgorbatchev thanks for the reference. I agree, that section is confusing, it describe an earlier incarnation of strong-pm, and hasn't applied for some time.

The lifecycle and configuration section (as well as support for the config file) will be removed in https://github.com/strongloop/strong-pm/pull/61. Please do not depend on it, or describe it.

**Comment by crandmck** [comment]
@alexgorbatchev We document stuff in two places: GitHub READMEs and http://docs.strongloop.com/.

Some time ago, the team and I concluded that the README would focus on the individual module, and docs.strongloop.com would explain how everything works together.  Although there will inevitably be duplication between the two, but the purpose and emphasis will be different.  So, http://docs.strongloop.com/display/SLC/Operating+Node+applications documents our "Dev Ops" tools and best practices.  Strong PM specifically is described primarily in http://docs.strongloop.com/display/SLC/Deploying+applications+with+slc, and http://docs.strongloop.com/display/SLC/Provisioning+hosts.

Every README should link to appropriate articles in docs.strongloop.com, and it also makes sense to link to related READMEs in GH.

**Comment by sam-github** [comment]
https://github.com/strongloop/strongloop/issues/191 obsoletes and follows on to this.
