### ISSUE TITLE
Change documentation of PM config

### ISSUE THREAD

**Issue by crandmck** [strongloop/strong-pm#124]
Apparently, the config file is being eliminated, to be replaced by other mechanisms, per #61.

Need to change docs accordingly.

**Comment by chandadharap** [comment]
Wait for heads up from @rmg

**Comment by rmg** [comment]
Easy change. The next major release of strong-pm will not support configuration files at all.

**Comment by chandadharap** [comment]
I guess the question is, should we just make  the mod to docs now? else
please give Rand/Denise a heads up after the next release.
=c

On Thu, Feb 19, 2015 at 9:02 AM, Ryan Graham <notifications@github.com>
wrote:

> Easy change. The next major release of strong-pm will not support
> configuration files at all.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/strongloop/strong-pm/issues/124#issuecomment-75091637>
> .
>



-- 
Chanda Dharap
Director, Engineering
@StrongLoop Inc
(510) 304-3924
chanda@strongloop.com

*StrongLoop <http://strongloop.com/>** makes it easy to **develop APIs
<http://strongloop.com/mobile-application-development/loopback/>** in Node,
plus get DevOps capabilities
<http://strongloop.com/node-js-performance/strongops/> like monitoring,
debugging and clustering**.*

**Comment by rmg** [comment]
I'm ok with it being removed now.

**Comment by sam-github** [comment]
We should remove now... we don't want people to start using the config file.

**Comment by crandmck** [comment]
@DeniseLee From above comments, it sounds like you should address this ASAP.  Let's chat and I can answer any questions.

**Comment by DeniseLee** [comment]
Hi @sam-github and @rmg (and @crandmck). I am a new contract writer for StrongLoop, and this is my first assignment. I've gone through #61, and it seems like all that needs to be done is to the docs is to remove references to the config file.

A couple of questions: 
1. Do we have a new way to configure PM now? (If so, what is it?)
2. Do we need to tell users that this is deprecated?

Thanks!

**Comment by crandmck** [comment]
@denise Be sure to update http://docs.strongloop.com/display/SLC/Running+Process+Manager#RunningProcessManager-Configuration with the new way to configure PM operation, assuming there is one

**Comment by rmg** [comment]
@DeniseLee there is no new way to configure the aspects of PM that the config file was used for. The best we can do in terms of alternatives is to point them at the existing CLI options and `pmctl` commands for getting/setting environment variables.

A deprecation notice might make sense for a 1.x release. @sam-github what do you think?

**Comment by DeniseLee** [comment]
Restricted  Process Manager config file page to strongloop group. 

Removed config option info from slc deploy, slc pm-install, slc pm, and Running Process Manager Configuration pages.

@chanda, @rmg, @sam-github 
I have not put in a deprecation notice. Not sure where to put it. Release notes?

**Comment by sam-github** [comment]
Many of the things that were theoretically configurable in `config` could not in fact be configured, so a deprecation notice is shutting the stable door after... you get the idea.

We'll bump the major, right? I think that's enough. Longer term, we'll need better ways, I guess, but that and the Changelog should be good enough for now, IMO.

**Comment by rmg** [comment]
@DeniseLee sorry for the confusion. I meant a deprecation notice added to the CLI for strong-pm@1.x as a backported fix for people who don't upgrade to 2.x right away. I wasn't intended for it to be published anywhere, since as Sam points out, the feature doesn't work properly anyway and our fix was just to remove it entirely.

**Comment by DeniseLee** [comment]
Thanks @sam-github and @rmg.
