### ISSUE TITLE
Add Express usage records

### ISSUE THREAD

**Issue by kraman** [strongloop/strong-pm#125]
Add Express usage records

**Comment by cgole** [comment]
@kraman,  how do I verify this?

**Comment by kraman** [comment]
I think @bajtos has a test script you can use to verify this API.

**Comment by bajtos** [comment]
@cgole 
1. Create an express app using the instructions in [strong-express-metrics](https://github.com/strongloop/strong-express-metrics#usage).
2. Deploy the app via strong-pm
3. Make some requests against your app
4. View the records via `http://localhost:7777/api/ExpressUsageRecords`, assuming `7777` is strong-pm's port.

@kraman you haven't renamed `usage` to `details `yet, have you?

**Comment by cgole** [comment]
I couldnt get this to work. Saw no data when I called the api. @kraman,  to help figure this out.

**Comment by cgole** [comment]
verified - 
 Create an app with - 
var express = require('express');
var metrics = require('strong-express-metrics');

var app = express();
app.use(metrics(function buildRecord(req, res) {
  return {
    client: {
      id: 1,
      username: 'a@bcom'
    },
    data: {
      url: req.url,
      status: res.statusCode
    }
  };
}));
app.listen(3000);


Deploy it to strong-pm
Check api - http://localhost:7777/api/ExpressUsageRecords

**Comment by chandadharap** [comment]
K has a small change TBD
