### ISSUE TITLE
refactor pm core: Move REST API implementation into strong-mesh-models

### ISSUE THREAD

**Issue by kraman** [strongloop/strong-pm#129]
"1.g" from https://docs.google.com/a/strongloop.com/document/d/1lRLv8zE5uflL84HoT360oyPU5PyDp2LTZE6w8t1QAuc/edit#

**Comment by chandadharap** [comment]
This is an APi change, so when we up the version, we'll need a full QA and this is an Arc impacting change, so need orchestration with @seanbrookes and a corresponding Arc release before publishing to npmjs.org. 

will close now.

**Comment by kraman** [comment]
Internals only change. API and CLI remain the same. Due to amount of code moved around, I suggest doing a full test of PM surface. I also suggest waiting for strongloop/strong-pm#131 and possibly strongloop-internal/scrum-nodeops#311 before starting verification.
