### ISSUE TITLE
refactor pm core: Move model update code into strong-mesh-models

### ISSUE THREAD

**Issue by kraman** [strongloop/strong-pm#131]
"1.g" from https://docs.google.com/a/strongloop.com/document/d/1lRLv8zE5uflL84HoT360oyPU5PyDp2LTZE6w8t1QAuc/edit#

**Comment by cgole** [comment]
verified. tried deploying to pm server  status, shutdown, start, stop, soft-stop, restart, soft-restart, set-size, set-env.

**Comment by cgole** [comment]
@kraman, Let me know if there is anything else I need to verify

**Comment by kraman** [comment]
@cgole how about profiling commands?

**Comment by cgole** [comment]
I tried all commands, including log dump and profiling. Everything is working. 
@sam @rmg - how does one know which env variable to use to get metrics. Dont see it documented anywhere..
env-set STRONGLOOP_METRICS=statsd://localhost:5140
