### ISSUE TITLE
Error installing service 'strong-pm'

### ISSUE THREAD

**Issue by braincomb** [strongloop/strong-pm#146]
Hi all,

I already have strong-pm installed, initial install was smooth, but subsequent re-installs result in an error:
```
sudo slc pm-install --port 7654 --systemd --set-env NODE_ENV=production
...
Error installing service 'strong-pm': stdout maxBuffer exceeded.
```

Using:
```
slc --version
strongloop v2.10.3 (node v0.10.36)
├── strong-arc@1.1.0
├── strong-build@1.0.3 (5a43a57)
├─┬ strong-supervisor@1.4.1 (c945bd1)
│ └── strong-agent@1.3.2
├── node-inspector@0.7.4
├── strong-deploy@1.1.4 (5e25e21)
├── strong-pm@1.7.2 (315d448)
├── strong-registry@1.1.4 (aab3dbb)
├── nodefly-register@0.3.3
└── generator-loopback@1.7.2 (96a7f70)
```

**Comment by sam-github** [comment]
Could you plrease re-run the pm-install with `DEBUG=*`, and post output? Perhaps as a gist if it is too long to paste in here.

**Comment by braincomb** [comment]
Sure, 

Here's the output:
https://gist.github.com/braincomb/c7e3a1fd7095bfdacaf1

**Comment by sam-github** [comment]
@rmg one of the calls to `execFile()` is clearly getting way more data than it expected, see [node](https://github.com/joyent/node/blob/master/lib/child_process.js#L787), but I'm having trouble seeing which one it was. All the ones in `lib/install.js` should be tiny, I think.

**Comment by rmg** [comment]
I caught and fixed the maxBuffer problem in #126, which is scheduled for the next major release.

@braincomb There is a good chance that you do not need to re-run `pm-install` after upgrading, since the service config itself has likely not changed. What version of strong-pm are you upgrading from?

**Comment by braincomb** [comment]
@rmg My original intention was not to upgrade but re-run the install to set an env variable, which I then realized I could do with `pmctl`. I also wanted to re-run it so I could set `--http-auth`, for some reason `sudo slc pmctl -C /var/lib/strong-pm/pmctl env-set STRONGLOOP_PM_HTTP_AUTH=user:secret` isn't doing anything for me, I checked env.json and I see it set, restarted the service just in case but still able to deploy without creds.

**Comment by rmg** [comment]
@braincomb the reason `env-set` doesn't work for this is because it is part of strong-pm's configuration but `env-set` only sets environment variables for the application. Your best bet at the moment is to manually edit your service file. Based on your open PR against strong-service-systemd you might have guessed that this involves adding a line to `/etc/systemd/system/strong-pm.service` in the Service section like:
```
Environment=STRONGLOOP_PM_HTTP_AUTH=user:secret
```

**Comment by rmg** [comment]
@braincomb we haven't updated strongloop to use it yet, but we've released a new version of strong-pm that includes the fixes I described. If the workaround or upgrade work for you, would you mind closing this?

**Comment by braincomb** [comment]
Updated to 3.0.0 and ran `sl-pm-install` - no issues.

Thanks! Closing.
