### ISSUE TITLE
Spike: Metrics persistance to disk + 1 hour (or n) of retention

### ISSUE THREAD

**Issue by kraman** [strongloop/strong-pm#148]
Chanda added: 
- [ ] First please check if extending aggregation via current mechanism on agent is a doable option for MVP. That need not involve writing connectors for now.
- [ ] I checked with Albert and Issac, Al's suggestion is even an hour of data is fine, we can work out a storage mechanism at the Arc end, on the file system.

Below is not in scope for this Spike
-------
For displaying API Usage metrics for LB, we will need to look at overhead involved in storing 1 days worth of API usage metrics and adding APIs to retrieve aggregate and detailed data for the recorded calls.

A working document describing the final ARC product is here https://docs.google.com/a/strongloop.com/document/d/1xTHn-GC29yTiPjtKeM2HK4IaBla8YvoImU9PwUgD5bA/edit#heading=h.598zeqqc14k4

* [ ] Determine model structure which will allow aggregation/filtering
* [ ] Persist API Usage metrics & processes
* [ ] Update Client to provide APIs that Arc needs to retrieve data

**Comment by Setogit** [comment]
Break down to smaller pieces and figure out inter dependencies to define which pieces, if not all, make a reasonable milestone for the sprint.

**Comment by chandadharap** [comment]
Obsolete, should be closed?
