### ISSUE TITLE
Add support for live environment set/unset

### ISSUE THREAD

**Issue by rmg** [strongloop/strong-pm#151]
Once strong-supervisor supports get/set/unset of environment variables via control channel strong-pm will need a way of utilizing it for truly zero-downtime environment updating.

See:
- strongloop-internal/scrum-nodeops#302
- strongloop-internal/scrum-nodeops#303
- strongloop-internal/scrum-loopback#206

**Comment by sam-github** [comment]
@rmg, complete?

**Comment by rmg** [comment]
I believe strong-pm is still issuing a full restart after the env changes instead of a rolling restart.
