### ISSUE TITLE
If app dependencies not installed, slc start fails and gives incorrect message "App `.` started under local process manager."

### ISSUE THREAD

**Issue by crandmck** [strongloop/strong-pm#163]
```
git clone https://github.com/strongloop/express-example-app.git
$ cd express-example-app/
$ slc start
App `.` started under local process manager.
  View the status:  slc ctl status
  View the logs:    slc ctl log-dump
  More options:     slc ctl -h
$ slc ctl
manager:
  pid:                66322
  port:               8701
  base:               /Users/rand/.strong-pm
current:
  status:             started
  pid:                66323
  link:               /Users/rand/StrongLoop/express-example-app
  current:            express-example-app
  branch:             local-directory
  worker count:       0
```
And if you try to load http://localhost:3000/ you can confirm the app doesn't respond.

Now:
```
$ slc run
...
supervisor running without clustering (unsupervised)

module.js:340
    throw err;
          ^
Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:338:15)
...
```
Then after running this
```
npm i
```
Everything works fine:
```
$ slc start
App `.` started under local process manager.
 ...
$ slc ctl 
manager:
  pid:                66322
  port:               8701
  base:               /Users/rand/.strong-pm
current:
  status:             started
  pid:                66323
  link:               /Users/rand/StrongLoop/express-example-app
  current:            express-example-app
  branch:             local-directory
  worker count:       4
    [1]:              cluster id 92, pid 66427
    [2]:              cluster id 93, pid 66431
    [3]:              cluster id 94, pid 66432
    [4]:              cluster id 95, pid 66433
```

**Comment by sam-github** [comment]
That's how it works. `slc start` (unlike build+deploy, but ***like*** the arc "app controller start") runs the app "in place". If it isn't runnable, it doesn't run.

Two things to note in above, though:

- If you had done `slc ctl log-dump`, one of the suggested cmds, you would have seen error messages about require failing
- after you did `npm i`, you did `slc start` again... you didn't have to: `slc start` runs under the process manager, it restarts it every second or so, or tries to, so as soon as you'd fixed the deps,it would restart. This latter behaviour is ***unlike*** the app controller start, which currently runs in one-shot mode.

**Comment by crandmck** [comment]
It just seems like a usability issue.  It says `App `.` started  ...` but it is not.  Isn't there any way to tell if the app is not actually running, and provide a more accurate message, i.e. the stack trace or even just "Unable to start app -- do "slc ctl log-dump" to see errors."

This also makes me think that simply replacing `slc run` with `slc start` everywhere in the LoopBack docs is a bad idea.  Unless we can provide better error messages for cases such as this, we'll need to tell them to ALWAYS do `slc ctl log-dump` during development, because otherwise you apparently don't see any errors or stack traces.
