### ISSUE TITLE
windows issues - cannot deploy to windows

### ISSUE THREAD

**Issue by cgole** [strongloop/strong-pm#165]
PS C:\Users\Administrator> slc pm -l 7777
slc pm: StrongLoop PM v3.1.19 (API v5.0.13) listening on port `7777`
slc pm: control listening on path `\\?\pipe\C:\Users\Administrator\pmctl`
slc pm: listen on 7777, work base is `C:\Users\Administrator\.strong-pm`
commit 8d45dc921fefc22cfe7e442010c06836f3b7cafe spawn `npm rebuild`...
Stop current (none)
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn npm ENOENT
  at exports._errnoException (util.js:746:11)
  at Process.ChildProcess._handle.onexit (child_process.js:1046:32)
  at child_process.js:1137:20
  at process._tickDomainCallback (node.js:381:11)
  at process.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-pm\node
_modules\strong-mesh-models\node_modules\loopback\node_modules\continuation-local-storage\node_modules\async-listener\in
dex.js:18:15)

PS C:\Users\Administrator\workspace\express-example-app> slc deploy http://localhost:7777
Counting objects: 303, done.
Compressing objects: 100% (279/279), done.
Writing objects: 100% (303/303), 236.67 KiB | 0 bytes/s, done.
Total 303 (delta 55), reused 0 (delta 0)
To http://localhost:7777/default
 * [new branch]      deploy -> deploy
Deployed `deploy` to `http://localhost:7777`

**Comment by sam-github** [comment]
@cgole fixed during strong-pm multi-app development, please try again

**Comment by cgole** [comment]
verified deploy from windows to a windows pm using git and tar from arc
