### ISSUE TITLE
windows issue : slc start fails with ftruncate

### ISSUE THREAD

**Issue by cgole** [strongloop/strong-pm#168]
PS C:\Users\Administrator\workspace\loopback-app> slc start
Error: connect ENOENT

**Comment by sam-github** [comment]
What is status?

**Comment by kraman** [comment]
@sam-github @cgole Why is this in verify? Is this still bug?

**Comment by cgole** [comment]
still a bug. 
D:\loopback-example-app-2>slc start
Error: pm failed, exit with status  8

**Comment by sam-github** [comment]
I don't see this issue, but I do see ftruncate is failing with EPERM, not sure if its simply unsupported, or its because I opened the file in append mode, will experiment.

**Comment by SC7639** [comment]
I'm having the same issue as @sam-github  when trying to run "slc start" command on windows it fails with the following error message:

fs.js:698
  return binding.ftruncate(fd, len);
                 ^
Error: EPERM, operation not permitted
    at Error (native)
    at Object.fs.ftruncateSync (fs.js:698:18)
    at Pm.spawn (C:\Users\SCrossan\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-start\lib\pm.js:82:6)
    at C:\Users\SCrossan\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-start\lib\pm.js:43:10
    at Socket.<anonymous> (C:\Users\SCrossan\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-start\lib\pm.js:52:12)
    at Socket.<anonymous> (C:\Users\SCrossan\AppData\Roaming\npm\node_modules\strongloop\node_modules\lodash\index.js:7363:25)
    at Socket.g (events.js:199:16)
    at Socket.emit (events.js:107:17)
    at net.js:459:14
    at process._tickDomainCallback (node.js:381:11)

**Comment by cgole** [comment]
Now,I can reproduce this too.

**Comment by SC7639** [comment]
I've taken to running it inside a docker container as I'm just going through the tutorials currently

**Comment by sam-github** [comment]
@SC7639 If you have docker, you have linux, why not just run on the host linux? This problem only effects Windows.

**Comment by SC7639** [comment]
I'm running it inside boot2docker VM. My Dev environment is widows and production environment is Linux

**Comment by WaseemCake** [comment]
@sam-github , On Windows am getting this 

D:\strongLoop\express-example-app-master>slc start
Error: pm failed, exit with status  8

Can you please help me here ?

**Comment by manishnakar** [comment]
any update ?
