### ISSUE TITLE
Create preliminary mock mesh-central to use as mock data for the Mesh UX design

### ISSUE THREAD

**Issue by kraman** [strongloop/strong-pm#174]
Create mock mesh-central for UI to run against with full tree of executors, instances, processes, metrics etc.

**Comment by chandadharap** [comment]
service, executor, instance, processes?

**Comment by kraman** [comment]
https://github.com/strongloop/strong-mesh-models/tree/feature/mock-mesh-central

`node test/mock-server.js`

**Comment by altsang** [comment]
awesome, thx @kraman we'll check out

**Comment by altsang** [comment]
/cc: @anthonyettinger, @seanbrookes, @jtary, @stacy-hunt

here we go guys - next version of Mesh based Process Manager API mock we
can use to get started, pls checkout

On Tue, Apr 7, 2015 at 4:50 PM, Krishna Raman <notifications@github.com>
wrote:

> Assigned #174 <https://github.com/strongloop/strong-pm/issues/174> to
> @altsang <https://github.com/altsang>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/strongloop/strong-pm/issues/174#event-275791729>.
>



-- 
Al Tsang
Co-Founder and CTO @ StrongLoop, Inc.

*StrongLoop <http://strongloop.com/>** makes it easy to **develop APIs
<http://strongloop.com/mobile-application-development/loopback/>** in Node,
plus get DevOps capabilities
<http://strongloop.com/node-js-performance/strongops/> like monitoring,
debugging and clustering**.*

**Comment by altsang** [comment]
verified on feature/mock-mesh-central
