### ISSUE TITLE
Azure on Marketplace

### ISSUE THREAD

**Issue by cgole** [strongloop/strong-pm#176]
After the image is ready, the test reports and other compliances

**Comment by chandadharap** [comment]
moved out of current sprint. overloaded and still need Product planning

**Comment by sam-github** [comment]
@rmg are we done with this?

**Comment by rmg** [comment]
@sam-github no idea, your mention was the first association between me and this.

**Comment by sam-github** [comment]
My apologies, I thought I saw your name on it, I think I just saw Azure.

**Comment by GeoffreyEmery** [comment]
was ths completed?

**Comment by GeoffreyEmery** [comment]
I see this https://azure.microsoft.com/en-us/marketplace/partners/nodejsapi/node-js-api/#starter it the same thing ?

**Comment by cgole** [comment]
nope, we never got to it.

**Comment by GeoffreyEmery** [comment]
so that azure starter kit was done by someone
