### ISSUE TITLE
sudo: sl-pm-install: command not found

### ISSUE THREAD

**Issue by sandipp** [strongloop/strong-pm#178]
I've used following command to install sl-pm
` npm install -g strong-pm && sl-pm-install` 

Then I've tried following command and got error as follows.
`sudo sl-pm-install --upstart=0.6`
`sudo: sl-pm-install: command not found`.

I'm running on `Centos6`, `AWS` `ec2` machine.

**Comment by rmg** [comment]
CentOS does not put `/usr/local/bin` in it's "secure_path" as used by `sudo`.

You can either edit your sudoers file (use `sudo visudo`, you can't edit it directly) or you can give it a more complete $PATH manually. If you do `sudo env PATH=$PATH sl-pm-install --upstart=0.6` it will run with the same $PATH as your current shell, which get you up and running.

**Comment by rmg** [comment]
@sandipp did my instructions solve your problem?

**Comment by sandipp** [comment]
@rmg yeah, it worked thank you.

**Comment by carlsonerik** [comment]
Awesome! This is exactly what I was looking for. Is it possible to add these things to the official documentation instead of resorting to google?

**Comment by rmg** [comment]
@carlsonerik it is in the docs, but perhaps not visible enough. Can you give a link to the page you expected to find this information on?

**Comment by carlsonerik** [comment]
https://docs.strongloop.com/display/SLC/Setting+up+a+production+host

I see the command, but it was not marked for the OS I am using. I am running Ubuntu 14.04, but it says to use it on 15+ . My inexperience with managing PATH doesn't help. Thank you!

**Comment by rmg** [comment]
Ubuntu 14.04 doesn't have that problem because `/usr/local/bin` is included in `secure_path`. If you installed node using `nvm`, then it would cause a similar symptom and would appear to be fixed by the same solution, but your apps won't deploy properly.

**Comment by carlsonerik** [comment]
I did use nvm to install the node version. What would be a remedy? Add the nvm install location to PATH?

**Comment by rmg** [comment]
If you absolutely must use nvm, then you will have to do a few things. You will need to modify the Upstart job (`/etc/init/strong-pm.conf` by default) to add the PATH for the specific version of node installed under nvm that you want it to use. You will also have to modify your permissions to allow the strong-pm user to access your user's home directory. If you remove that version of node from nvm, you will break strong-pm. If you wish to upgrade the version of node, you will have to repeat these steps using the location of that new version of node.

If you aren't stuck using nvm, then it is probably easiest just to use the .deb packages: https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions

**Comment by carlsonerik** [comment]
That information helped immensely. Thank you so much!
