### ISSUE TITLE
Docs for multi-app support

### ISSUE THREAD

**Issue by crandmck** [strongloop/strong-pm#182]
There will be both changes and additions for this feature. 
Also update http://strong-pm.io/compare.

 See: 
- #141
- https://github.com/strongloop-internal/scrum-nodeops/issues/373
- https://github.com/strongloop-internal/scrum-nodeops/issues/315
- https://github.com/strongloop-internal/scrum-nodeops/issues/417

Among other things, need to update [slc ctl command ref](http://docs.strongloop.com/display/NODE/slc+ctl) to add changes in https://github.com/strongloop/strong-mesh-models/blob/master/bin/sl-meshctl.txt

**Comment by crandmck** [comment]
In progress (hidden):
- [slc build](http://docs.strongloop.com/pages/viewpage.action?pageId=6719159)
- [slc deploy](http://docs.strongloop.com/pages/viewpage.action?pageId=6719157)
- [slc ctl](http://docs.strongloop.com/pages/viewpage.action?pageId=6719149)

**Comment by sam-github** [comment]
`slc ctl` docs haven't had the per-worker commands updated with the new argument format.

Specifically, the docs still say:

> <id>, a worker ID or process ID

But it should be: https://github.com/strongloop/strong-mesh-models/blob/master/bin/sl-meshctl.txt#L91-L96

**Comment by crandmck** [comment]
Yes, I haven't updated that yet.  Will do so asap.

**Comment by crandmck** [comment]
Updated http://docs.strongloop.com/pages/viewpage.action?pageId=6719149

**Comment by sam-github** [comment]
lgtm

**Comment by chandadharap** [comment]
done.
