### ISSUE TITLE
Deploying express-app not working properly

### ISSUE THREAD

**Issue by facascante** [strongloop/strong-pm#202]
Hi,

i tried to deploy a basic express app generated by express-generator.
i run it in node bin/www and it's working fine.
but when i deploy it in remote pm it seems to be deployed but not running

here is the status from slc

```
Service ID: 5
Service Name: <3rd-app-name>
Environment variables:
  No environment variables defined
Instances:
    Version  Agent version  Cluster size
     4.1.0       1.5.1            2
Processes:
        ID      PID   WID  Listening Ports  Tracking objects?  CPU profiling?
    5.1.18430  18430   0
    5.1.31910  31910   9
    5.1.31913  31913   10

```

here is the strong-pm logs

```
Run request for commit "5/deploy/default/develop" on current undefined/undefined
npm http GET https://registry.npmjs.org/morgan
npm http GET https://registry.npmjs.org/static-favicon
npm http GET https://registry.npmjs.org/cookie-parser
...
npm http GET https://registry.npmjs.org/fresh/0.2.0
npm http GET https://registry.npmjs.org/range-parser/0.0.4
npm http 304 https://registry.npmjs.org/negotiator
npm http 304 https://registry.npmjs.org/fresh/0.2.0
npm http 304 https://registry.npmjs.org/range-parser/0.0.4
Run request for commit "default/npm-pack" on current undefined/undefined
```
here last lines from the logs from log-dump

```
2015-05-13T06:11:20.119Z pid:18430 worker:0 ERROR supervisor worker id 4 (pid 18754) expected exit with 2
2015-05-13T06:11:20.216Z pid:18430 worker:0 INFO supervisor started worker 6 (pid 29768)
2015-05-13T06:11:20.216Z pid:18430 worker:0 INFO supervisor resized to 2
2015-05-13T06:11:20.452Z pid:29768 worker:6 INFO strong-agent v1.5.1 profiling app '<3rd-app-name>' pid '29768'
2015-05-13T06:11:20.456Z pid:29768 worker:6 INFO strong-agent[29768] started profiling agent
2015-05-13T06:11:20.623Z pid:29768 worker:6 INFO strong-agent not profiling, agent metrics requires a valid license.
2015-05-13T06:11:20.623Z pid:29768 worker:6 Please contact sales@strongloop.com for assistance.
```

and you can try the sample-express-app im deploying in this public repo

https://github.com/facascante/sample-express-app/tree/develop

please use branch develop.

appreciate any help :) we are planning to deploy existing express project to strong-pm

**Comment by rmg** [comment]
PM will run app.js when you deploy this app, not bin/www.js. That would explain the why it isn't running and also why it isn't crashing.

**Comment by facascante** [comment]
i see thanks i'll try and close this issue if that work :)

**Comment by facascante** [comment]
it work's when i move content of bin/www to app.js... thank you. so it must be strict to use app.js... 

suggestion : better if we can read the package.json or just run the app using "npm start" command :) with that we can specify how are app should be run :)

**Comment by sam-github** [comment]
We do read the package.json, app.js is only one of the options:

https://github.com/strongloop/strong-supervisor/blob/master/bin/sl-run.txt#L5-L11

We can't use npm start, its a shell script, and the supervisor needs to directly run a *node.js* file, both to make it a cluster worker and so that we can load instrumentation before passing control to the "app" script.

For some npm start commands, its possible to parse them, see what is being run with the shell, and then run the js file directly, but we haven't implemented that heuristic yet.

**Comment by facascante** [comment]
copy. so it's the main property of package.json. i see cool :)

**Comment by carloscarcamo** [comment]
:+1:
