### ISSUE TITLE
App does not update after deploy

### ISSUE THREAD

**Issue by paulJordaan** [strongloop/strong-pm#203]
When using ``slc deploy http:\\hostname.com`` the changes are not added to the live site.

 I can see the new branch under ``/var/lib/strong-pm/work`` but the 'current' symlink does not seem to update. Is there a way to force a switch to the new branch or could you perhaps hint at why it is not updating?

**Comment by sam-github** [comment]
I suspect it has failed to npm install, what does the strong-pm log say?

**Comment by jfoliveira** [comment]
I am having the same issue and as you suspect `npm install` does not seem to be running during my `slc deploy`.
I ssh-ed to the server
`cd /var/lib/strong-pm/svc/1/work/current`
`npm install`

No errors!

Then:
`/sbin/initctl stop strong-pm`
`/sbin/initctl start strong-pm`

Few seconds later the app was running and listening.
So, if nothing went wrong with the manual process, what could be happening during the automatic process?

Couldn't find [in the docs](http://docs.strongloop.com/display/NODE/slc+ctl) any extra params to `slc deploy`.
Is there any `verbose` flag to `slc deploy` so we could get a feedback from the failed app reboot?

**Comment by sam-github** [comment]
The chance that `npm install` was not run by pm is about zero. The chance that `npm install` behaves differently when run from command line vs. as a service is pretty good, I suspect in @jfoliveira's case, that is what is happening.

All the `npm install` output will be present in the strong-pm.log, see `/var/log/upstart/strong-pm.log` If you go back to your last deployment, you should see what `npm install` had to say for itself. Can you find that and report back?

Assuming you are running upstart, if its systemd, the log will be elsewhere.

**Comment by jfoliveira** [comment]
Thanks for replying!
I'm running upstart, and here is what I believe is the most relevant finding in the log file:
```javascript
child_process.js:1162
    throw errnoException(err, 'spawn');
          ^
Error: spawn ENOMEM
    at exports._errnoException (util.js:746:11)
    at ChildProcess.spawn (child_process.js:1162:11)
    at exports.spawn (child_process.js:995:9)
    at spawnNpm (/usr/lib/node_modules/strong-pm/node_modules/strong-spawn-npm/index.js:7:12)
    at spawn (/usr/lib/node_modules/strong-pm/lib/drivers/common/prepare.js:53:15)
    at /usr/lib/node_modules/strong-pm/lib/drivers/common/prepare.js:34:5
    at /usr/lib/node_modules/strong-pm/node_modules/async/lib/async.js:607:21
    at /usr/lib/node_modules/strong-pm/node_modules/async/lib/async.js:246:17
    at iterate (/usr/lib/node_modules/strong-pm/node_modules/async/lib/async.js:146:13)
    at async.eachSeries (/usr/lib/node_modules/strong-pm/node_modules/async/lib/async.js:162:9)
``` 
It seems during deployment process strong-pm was unable to spawn a child process to execute `npm install`.
Any ideas on how to dig deeper from here?

**Comment by rmg** [comment]
Running out of memory during `npm install` has come up a few times in different contexts. Unfortunately, the cause is usually as simple as the error implies. 

Usually when this comes up, it is a combination of the server having only a small amount of RAM (512mb-1gb) and not having any swap space (most cloud VMs don't enable swap by default).

**Comment by rmg** [comment]
I was looking for instructions I gave elsewhere, but can't seem to find them from my phone, so I'll just type them up again..

```
sudo dd if=/dev/zero of=/swapfile bs=1mb count=1024
sudo mkswap /swapfile
sudo swapon /swapfile
```

Since I'm on my phone I'll leave making it permanent (modifying /etc/fstab) for someone else to fill in.

**Comment by rmg** [comment]
This appears to be resolve. Please re-open if adding swap does not solve the problem.
