### ISSUE TITLE
Option to disable `npm rebuild` at deploy time

### ISSUE THREAD

**Issue by javefang** [strongloop/strong-pm#208]
OS: RHEL 6.6
node.js: 0.10.36
strong-pm: 4.1.0

I noticed that strong-pm always try to run `npm rebuild` and `npm install --production` at deploy time.
https://github.com/strongloop/strong-pm/blob/master/LIFE-CYCLE.md

The `npm install --production` is fine, as all non dev dependencies are declared as `bundledDependencies` in package.json. But `npm rebuild` is problematic when some package has native binaries (e.g. ldapjs), as it will trigger a `node-gyp rebuild` on the deployment target.

This might be a problem with our company's policy. We have to build all deployment packages on a dedicated build server (Linux), including download all dependencies, build all native binaries and pack them up as tar balls. Then deploy the tar balls to production servers (Linux). The production servers don't have Internet access, and no compilation should be performed on the production server. (i.e. it should just unpack the tar ball and run them.) Currently strong-pm calls rebuild regardless on the production server, which is stopping us from using it as process manager.

We always run `slc build --npm --scripts` on the build server so it will run all the install scripts to compile native binaries and include them in the deployment tar balls. Our build servers always have the same process architecture, OS and node version as the production server so in fact no rebuild is required. 

Is it possible to add an option to switch on/off the rebuild behaviour? Actually I think the default behaviour might better to be "do not rebuild" when deploying. 

To enable rebuild for a deploy:
`slc deploy  --rebuild -s <service> <url> <package>`

To disable rebuild for a deploy:
`slc deploy -s <service> <url> <package>`

Thanks in advance!
Jave

**Comment by rmg** [comment]
The current behaviour is because it is very common to do development on Mac and Windows and then deploy to Linux, but your setup should also work. @sam-github any thoughts?

**Comment by javefang** [comment]
Hi @rmg, I understand and we develop on windows as well. However, our policy does not allow any build/compilation at deploy time. (i.e. everything should be built and archived on the build server, tested on a test server with the same spec as production before deploy) 

In addition, build on the production server will require node-gyp to fetch node development header files from nodejs.org, which is a problem for us as: 1) the production server has no internet access; 2) installing development header on production server is yet another dependency and might not be a very good practice. (correct me if I'm wrong :) )

I would be appreciated if the rebuild flag could be added to strong-deploy and strong-pm, this will be a life saver for me and I think will benefit a lot of other developers working in corporate with similar policies. Thanks!

**Comment by rmg** [comment]
@javefang sorry if it wasn't clear, I completely agree with you.

**Comment by sam-github** [comment]
I'd like to find a way to avoid having this to be an install time flag, or even a dynamic flag set via `slc ctl`, though that would be  better. Unfortunately, I can't think of how we can know for sure whether  or not `npm rebuild` has to be run.

My intention was that `npm rebuild` be effectively a no-safe op if there are no compilers installed on the deployment machine, or if there is no outbound network access. I'll experiment with this, but can you clarify, do you actually have a build env on your deployment host?

**Comment by rmg** [comment]
Once #297 has been verified and passes our QA/QE, we should be able to release strong-pm v5.1.0 with a new `--skip-defaul-install` option that should solve this problem.

**Comment by cgole** [comment]
verified
