### ISSUE TITLE
Cannot specify port for app to run on

### ISSUE THREAD

**Issue by mstoddart** [strongloop/strong-pm#211]
Previously, setting PORT=X would allow us to force strong-pm hosted applications onto port X. Now apps are run at port 3000 + serviceId (https://github.com/strongloop/strong-pm/blob/3c845e180adab55ad779328e8b172bc7e2856766/lib/service-manager.js#L372). As mentioned in the documentation (http://docs.strongloop.com/display/NODE/slc+ctl), this port number cannot be guaranteed. A good solution is to use strong-arc and strong-nginx-controller, which monitor strong-pm changes and adjust the nginx config appropriately. However, neither of these products are open source. Is there an open source solution to this? If not, would it be possible to allow apps to run at the port declared by config?

**Comment by sam-github** [comment]
You can modify your app to ignore PORT and listen to anything you want, there is nothing strong-pm does to prevent apps running on the port they want (other than setting PORT, which is just convention, albeit fairly universal).

We're a bit between a rock and a hard place:

1. no port can be guaranteed
2. no app can be trusted to have hard-coded into it a free port
3. very few apps will listen on an ephemeral port (they usually have code like `port = process.env.PORT || 3000`, so setting `PORT=0` fails to have any effect

So, we are left with no working strategy, other than monkey patching node listen to force the port to be ephemeral... which would also confuse people in its intrusiveness, but we might do it eventually.

The issue of which port an app listens on and whether it will or will not be free, and how that port is put into the nginx configuration aren't related, it seems to me.

For the latter nginx config issue, if you remove any apps that listen at port 3000-3009 (assuming less than 9 apps) and allow strong-pm to own that range, then you can hard code the correct ports in your nginx config, and don't require any further source, open or closed.

We might add support for setting the strong-pm port base to something other than 3000, that would be easy.

Longer term, we'll be working on connecting strong-pm to nginx-controller directly... but that will be a while.

**Comment by antoniocb** [comment]
Hi Sam, could we at least override the starting port, ex: 40000, 40001...
Thanks.

**Comment by sam-github** [comment]
@antoniocb that would be very reasonable, I'll try to get it in the next release. You can hack it quickly: https://github.com/strongloop/strong-pm/blob/v4.1.1/lib/service-manager.js#L365

A proper fix will take me some more time, it will need to work for docker, too.

**Comment by rmg** [comment]
Maybe an environment variable like `STRONG_PM_BASE_PORT` with a fallback to `3000` if not set?

@antoniocb @mstoddart this might be an easy first PR if you're looking to contribute.

**Comment by mannyhenri** [comment]
I'm facing the same issue, where several people with top notch firewall software are blocking port 3000 and preventing the API to supply the data. Big frustrating issue. Any temporary solution?

**Comment by rmg** [comment]
@mannyhenri if your problem is you can't specify which app your port actually listens on and your app is a loopback app, there is a [workaround](http://stackoverflow.com/a/30494491/62525), which is to set an `npm_config_port` environment variable in your app's config (`slc ctl env-set 1 npm_config_port=1234`).

**Comment by mannyhenri** [comment]
@rmg thanks I'll try that as most firewalls in companies block port 3000

**Comment by rmg** [comment]
@mannyhenri do you mean they block 3000 specifically? Or they block everything but 80/443?

**Comment by mannyhenri** [comment]
@rmg most likely they do (ex.: one of my client couldn't see their site at a school and the same at their company until they opened port 3000 on their firewall). I mustn't be the only one experiencing such issues...Is it OK to switch the 80/443 ports instead for loopback?

**Comment by rmg** [comment]
The usual, and often recommended, solution is to either run a reverse proxy such as nginx or to set up a firewall policy on the server itself to redirect port 80 requests to the port your app is running on. This is because you should generally be running your app with the least privileges possible, and running on ports lower than 1024 requires root (or setting capabilities). That is why `slc pm-install`/`sl-pm-install` creates a strong-pm user for running PM under.

**Comment by mannyhenri** [comment]
@rmg So by doing the SLC PM-INSTALL it should resolve most of my issues with firewalls correct? I want to make sure as this is a production system that will have an impact on the client if it doesn't work as before.

**Comment by rmg** [comment]
@mannyhenri no, installing a proxy or creating appropriate iptables redirects will resolve most of your issues with firewalls. Listening on port 80 directly will get _harder_ by using `slc pm-install` because it will run PM as a non-root user that is not _allowed_ to listen on port 80.

**Comment by sam-github** [comment]
fixed by https://github.com/strongloop/strong-pm/pull/250
