### ISSUE TITLE
CoffeeScript support 

### ISSUE THREAD

**Issue by fuson** [strongloop/strong-pm#225]

**Comment by rmg** [comment]
@fuson can you elaborate?

**Comment by fuson** [comment]
For now in our web project we use PM2 with keymetrics monitoring dashboard, but looking to strong stack and "interpreters" support (in design not only coffee) looks like a primary showstopper to initiate migration activities. And i'm sure that this project is the proper place to implement it, you have "strong-runner", "strongloop" and another projects that looks like a candidate :) Anytime, we like your CRUD solution :)

**Comment by rmg** [comment]
Understood. You essentially want to override `process.execPath` so that your app is run by `/usr/local/bin/coffee` (or ./node_modules/.bin/coffee`) instead of `/usr/local/bin/node`.

Is pre-compiling your app in a `prepublish` script not a workable solution for you?

**Comment by fuson** [comment]
But what we receive in stack traces? .js line numbers that is absolutely irrelevant with .coffee code? Its not a good idea :(

**Comment by rmg** [comment]
My execPath comment was more about intent than actual implementation.

As for stack traces, I had assumed the `coffee` compiler took care of that, otherwise it wouldn't be so popular. Seems I was mistaken.

**Comment by sam-github** [comment]
We support coffee if you use `slc build`, and a prepublish or build script
