### ISSUE TITLE
slc start is not running

### ISSUE THREAD

**Issue by dhirenderbp** [strongloop/strong-pm#226]
When i run slc start with write log to a file then it gives me:

Mon, 01 Jun 2015 07:03:22 GMT slc slc.run: argv [ 'start' ] options { _: [ 'start' ], '$0': 'slc' }
Mon, 01 Jun 2015 07:03:22 GMT slc loadCommand name start run? function usage? object
Mon, 01 Jun 2015 07:03:22 GMT strong-start:start app is "."
Mon, 01 Jun 2015 07:03:22 GMT strong-start:pm start
Mon, 01 Jun 2015 07:03:22 GMT strong-start:pm alive? Error: connect ENOENT
Mon, 01 Jun 2015 07:03:22 GMT strong-start:pm pm is missing: Error: connect ENOENT
Mon, 01 Jun 2015 07:03:22 GMT strong-start:pm spawn: /usr/local/bin/node args ["/usr/local/lib/node_modules/strongloop/node_modules/strong-pm/bin/sl-pm.js","--base","/home/dhirender/.strong-pm","--control","/home/dhirender/.strong-pm/pmctl","--listen",8701] options {"detached":true,"stdio":"inherit"}
Mon, 01 Jun 2015 07:03:22 GMT strong-start:pm wait for pm to be alive
Mon, 01 Jun 2015 07:03:22 GMT strong-start:pm alive? Error: connect ENOENT
Mon, 01 Jun 2015 07:03:23 GMT strong-start:pm alive? Error: connect ENOENT
module.js:338
    throw err;
    ^
Error: Cannot find module '/usr/local/lib/node_modules/strongloop/node_modules/strong-mesh-models/node_modules/minkelite/node_modules/sqlite3/lib/binding/node-v14-linux-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/strongloop/node_modules/strong-mesh-models/node_modules/minkelite/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
Error: pm failed, exit with status  1

**Comment by rmg** [comment]
It looks like the sqlite3 native binding didn't build properly. Can you give the output of `slc version`?

**Comment by dhirenderbp** [comment]
strongloop v3.1.1 (node v0.12.2)
├── strong-arc@1.1.0
├── strong-build@1.0.3 (5a43a57)
├── strong-deploy@1.2.0 (1c78f8d)
├── strong-pm@3.1.9 (9579431)
├── strong-registry@1.1.4 (aab3dbb)
├── strong-start@1.0.3 (b23e63f)
├─┬ strong-supervisor@1.5.2 (cd3897a)
│ └── strong-agent@1.4.0
├── generator-loopback@1.9.0 (b90e9cd)
├── node-inspector@0.7.4
└── nodefly-register@0.3.3

**Comment by rmg** [comment]
@dhirenderbp can you try updating strongloop with `npm install -g strongloop`?

**Comment by rmg** [comment]
@dhirenderbp any update?

**Comment by simoami** [comment]
Hello, I don't think this got solved yet.

running `slc start` on node v0.12, and getting the following error:

```
$ slc pm
module.js:338
    throw err;
    ^
Error: Cannot find module '/usr/local/lib/node_modules/strongloop/node_modules/minkelite/node_modules/sqlite3/lib/binding/node-v14-darwin-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/strongloop/node_modules/minkelite/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

Here's my env:
```
node: v0.12.7
npm: 2.11.3
strongloop v5.0.0 (node v0.12.7)
├── strong-arc@1.7.1 (9bb91bb)
├── strong-build@2.0.4 (9294f54)
├── strong-deploy@3.0.0 (bee617c)
├── strong-mesh-models@8.0.0 (1b220f7)
├── strong-pm@5.0.0 (dbaa1a5)
├── strong-registry@1.1.5 (f46e58f)
├── strong-start@1.3.0 (3862a1f)
├─┬ strong-supervisor@3.0.2 (539c0ce)
│ └── strong-agent@1.6.4
├── generator-loopback@1.10.2 (167461e)
├── node-inspector@0.7.4
└── nodefly-register@0.3.3
```

**Comment by rmg** [comment]
This appears to have been resolved by the dependency updates that have been published recently.

@simoami can you do an `npm install -g strongloop` and see if it works for you now?

**Comment by rmg** [comment]
@dhirenderbp @simoami I'm closing this for now. Re-open if it is still a problem.

**Comment by simoami** [comment]
@rmg 
Sorry for not responding earlier. The issue got resolved after running `npm install -g strongloop` again. I had upgraded node to v0.12 and needed to re-install to have new sources recompile under node v0.12.

**Comment by EthraZa** [comment]
I had the same problems.
Strongloop does not install on node 4.2.2 and seens to install on 5.0.0 but does not work. Node 0.12.7 is the only one I could get it working.

**Comment by jeremiahlee** [comment]
I, too, am getting this error no matter how many times I reinstall.

Ubuntu 14.04.1 LTS (GNU/Linux 3.13.0-43-generic x86_64), node v4.2.2, npm v2.14.7, 

From `~/.strong-pm/start.log`:
```
module.js:339
    throw err;
    ^

Error: Cannot find module '/home/vagrant/npm-global/lib/node_modules/strongloop/node_modules/minkelite/node_modules/sqlite3/lib/binding/node-v46-linux-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/vagrant/npm-global/lib/node_modules/strongloop/node_modules/minkelite/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
```

**Comment by EthraZa** [comment]
Today I have upgraded node to 0.12.8 and it is working fine there. So I tryed 4.2.2...

With node 4.2.2 default npm it gave errors on install, so I rm strongloop, updated npm and called it to install strongloop again. It installed without error but does not run.

What I have:
~~~
[ec2-user@ip-172-31-42-199 node]$ slc version
strongloop v5.0.1 (node v4.2.2)
├── strong-arc@1.8.4 (b7b568d)
├── strong-build@2.0.6 (d008a3e)
├── strong-deploy@3.1.2 (be6180a)
├── strong-mesh-models@8.1.0 (62e539b)
├── strong-pm@5.0.1 (b96f806)
├── strong-registry@1.1.5 (f46e58f)
├── strong-start@1.3.2 (1327018)
├─┬ strong-supervisor@3.3.1 (1e39220)
│ └── strong-agent@2.0.2 (4ea7ee9)
├── generator-loopback@1.13.0 (a884c0b)
├── node-inspector@0.7.4
└── nodefly-register@0.3.3

[ec2-user@ip-172-31-42-199 node]$ npm -v
3.5.0
~~~

What I got:
~~~
Dec  2 00:55:05 ip-172-31-42-199 strong-pm: Error: Cannot find module '/home/ec2-user/.nvm/versions/node/v4.2.2/lib/node_modules/strongloop/node_modules/sqlite3/lib/binding/node-v46-linux-x64/node_sqlite3.node'
Dec  2 00:55:05 ip-172-31-42-199 strong-pm:     at Function.Module._resolveFilename (module.js:337:15)
Dec  2 00:55:05 ip-172-31-42-199 strong-pm:     at Function.Module._load (module.js:287:25)
Dec  2 00:55:05 ip-172-31-42-199 strong-pm:     at Module.require (module.js:366:17)
Dec  2 00:55:05 ip-172-31-42-199 strong-pm:     at require (module.js:385:17)
Dec  2 00:55:05 ip-172-31-42-199 strong-pm:     at Object.<anonymous> (/home/ec2-user/.nvm/versions/node/v4.2.2/lib/node_modules/strongloop/node_modules/sqlite3/lib/sqlite3.js:4:15)
Dec  2 00:55:05 ip-172-31-42-199 strong-pm:     at Module._compile (module.js:435:26)
Dec  2 00:55:05 ip-172-31-42-199 strong-pm:     at Object.Module._extensions..js (module.js:442:10)
Dec  2 00:55:05 ip-172-31-42-199 strong-pm:     at Module.load (module.js:356:32)
Dec  2 00:55:05 ip-172-31-42-199 strong-pm:     at Function.Module._load (module.js:311:12)
Dec  2 00:55:05 ip-172-31-42-199 strong-pm:     at Module.require (module.js:366:17)
Dec  2 00:55:05 ip-172-31-42-199 strong-pm:     at require (module.js:385:17)
~~~

Any ideas on why sqlite3 is not cooperating?

**Comment by rmg** [comment]
@EthraZa what do you mean by "so I rm strongloop"?

**Comment by EthraZa** [comment]
@rmg I mean I **npm -g rm strongloop** before I redo **npm install -g strongloop**

**Comment by daankets** [comment]
Still doesn't work with node versions other than v11... Really a shame...

**Comment by apikiakos** [comment]
@EthraZa Thanks, the rm before the general install did work for me !

**Comment by sam-github** [comment]
@daankets do you mean v0.11? That's pretty much the only major node version we do NOT test with... if its not working for you, I suggest you log a bug with some description.

@EthraZa got 0.12.8 working. I just tried 4.2.2 (on linux) which he didn't have success with:

```
nvm install 4.2.2
nvm use 4.2.2
npm install -g strongloop
.... long
/tmp/fu % slc pm
slc pm(30943): StrongLoop PM v5.1.0 (API v6.1.0) on port `8701`
slc pm(30943): Base folder `/home/sam/.strong-pm`
slc pm(30943): Applications on port `3000 + service ID`
Browse your REST API at http://127.0.0.1:8701/explorer
^C
/tmp/fu % slc -v
strongloop v6.0.0 (node v4.2.2)
├── strong-arc@1.8.7 (3496531)
├── strong-build@2.1.0 (47dd24a)
├── strong-deploy@3.1.2 (be6180a)
├── strong-liberty-pm@1.0.1 (2160c20)
├── strong-mesh-models@8.1.0 (62e539b)
├── strong-pm@5.1.0 (eb2f788)
├── strong-registry@1.1.5 (f46e58f)
├── strong-start@1.3.2 (1327018)
├─┬ strong-supervisor@3.3.1 (1e39220)
│ └── strong-agent@2.0.2 (4ea7ee9)
├── generator-loopback@1.14.0 (4a7aae3)
├── node-inspector@0.7.4
└── nodefly-register@0.3.3

/tmp/fu % node -v
v4.2.2
```

If sqlite is missing, then going back through your console logs to find where it was compiled would be helpful.

**Comment by daankets** [comment]
I'm using à fresh minimal Ubuntu 14.04 server vm with all the latest kernel
and other updates, and only node js 5.7.0 and build-essentials installed.
Then:

sudo npm -g install strongloop
sudo slc pm-install
sudo service strong-pm start

So far so good. But:

'slc start' gives me the beforementioned error. My start script is just:

node server/server.js

Maybe I lack some binary dependency?

**Comment by sam-github** [comment]
@daankets what's the beforementioned error? You mean:

```
Error: Cannot find module '/usr/local/lib/node_modules/strongloop/node_modules/strong-mesh-models/node_modules/minkelite/node_modules/sqlite3/lib/binding/node-v14-linux-x64/node_sqlite3.node'
```

?

When I install with that node version on ubuntu, I see

```
> sqlite3@3.1.1 install /home/sam/w/sn/strong-pm/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

[sqlite3] Success: "/home/sam/w/sn/strong-pm/node_modules/sqlite3/lib/binding/node-v47-linux-x64/node_sqlite3.node" is installed via remote

```

and all is well. Do you see something similar?

What happens when you just manually install sqlite3: `npm install sqlite3`?

**Comment by daankets** [comment]
Oh, my! That did the trick! You’ve just made my day ;-) It works now ;-) cluster with 4 processes running!

With kind regards

Daan Kets
Development Manager
Delta Source, Bulgaria

On 2 March 2016 at 20:59:59, Sam Roberts (notifications@github.com) wrote:

@daankets what's the beforementioned error? You mean:

Error: Cannot find module '/usr/local/lib/node_modules/strongloop/node_modules/strong-mesh-models/node_modules/minkelite/node_modules/sqlite3/lib/binding/node-v14-linux-x64/node_sqlite3.node'

?

When I install with that node version on ubuntu, I see

> sqlite3@3.1.1 install /home/sam/w/sn/strong-pm/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

[sqlite3] Success: "/home/sam/w/sn/strong-pm/node_modules/sqlite3/lib/binding/node-v47-linux-x64/node_sqlite3.node" is installed via remote


and all is well. Do you see something similar?

What happens when you just manually install sqlite3: npm install sqlite3?
