### ISSUE TITLE
Not able to get or set the environment variable using slc command line

### ISSUE THREAD

**Issue by dhirenderbp** [strongloop/strong-pm#227]
When i hit "slc ctl -C http://remote-host env-get app-name" then it return error 
"Command env-get failed with Error: There is no method to handle GET /ServiceInstances/1".

I am following http://docs.strongloop.com/display/SLC/Setting+and+viewing+environment+variables

**Comment by rmg** [comment]
Can you give the output `slc version`?

**Comment by dhirenderbp** [comment]
strongloop v3.1.1 (node v0.12.2)
├── strong-arc@1.1.0
├── strong-build@1.0.3 (5a43a57)
├── strong-deploy@1.2.0 (1c78f8d)
├── strong-pm@3.1.9 (9579431)
├── strong-registry@1.1.4 (aab3dbb)
├── strong-start@1.0.3 (b23e63f)
├─┬ strong-supervisor@1.5.2 (cd3897a)
│ └── strong-agent@1.4.0
├── generator-loopback@1.9.0 (b90e9cd)
├── node-inspector@0.7.4
└── nodefly-register@0.3.3

**Comment by rmg** [comment]
Same as the other issue, please update `strongloop` and see if the problem still exists.

**Comment by rmg** [comment]
@dhirenderbp is this still broken for you? Or can the issue be closed?
