### ISSUE TITLE
Support docker in docker

### ISSUE THREAD

**Issue by rmg** [strongloop/strong-pm#243]
Support using `--driver docker` when running strong-pm as a docker container itself.

**Comment by rmg** [comment]
The biggest changes are in how pm is run. For most cases, it is just a matter of:
 * adding `-v /var/run/docker.sock:/var/run/docker.sock` to `docker run` args to bind the docker socket
 * adding `-u :docker` to `docker run` args so pm runs as `strong-pm:docker` so it can connect to the docker socket
 * adding `--driver docker` to the container args to tell pm to use docker
 * removing any port mappings from the PM container that may conflict with the containers it launches

Best part is these can all be done by the person installing strong-pm as a docker container, and don't require any changes to strong-pm itself (though there is room for improvement w.r.t. error handling in such a setup).

**Comment by ivomarino** [comment]
@rmg seems to run this way: https://github.com/strongloop/strong-pm/issues/402#issuecomment-302332642.
