### ISSUE TITLE
installing on iojs

### ISSUE THREAD

**Issue by behrad** [strongloop/strong-pm#244]
I'm having problem installing and running strong-pm on centos 7, `iojs 2.3.0` installed via `nvm 0.25.4`

```
strong-pm.service - StrongLoop Process Manager
   Loaded: loaded (/etc/systemd/system/strong-pm.service; disabled)
   Active: failed (Result: start-limit) since Wed 2015-06-17 21:40:02 IRDT; 5s ago
  Process: 24465 ExecStart=/root/.nvm/versions/io.js/v2.3.0/bin/iojs /root/.nvm/versions/io.js/v2.3.0/lib/node_modules/strong-pm/bin/sl-pm.js --listen 8701 --base /var/lib/strong-pm --driver direct (code=exited, status=203/EXEC)
 Main PID: 24465 (code=exited, status=203/EXEC)

Jun 17 21:40:02 MG-Centos7 systemd[1]: Unit strong-pm.service entered failed state.
Jun 17 21:40:02 MG-Centos7 systemd[1]: strong-pm.service holdoff time over, scheduling restart.
Jun 17 21:40:02 MG-Centos7 systemd[1]: Stopping StrongLoop Process Manager...
Jun 17 21:40:02 MG-Centos7 systemd[1]: Starting StrongLoop Process Manager...
Jun 17 21:40:02 MG-Centos7 systemd[1]: strong-pm.service start request repeated too quickly, refusing to start.
Jun 17 21:40:02 MG-Centos7 systemd[1]: Failed to start StrongLoop Process Manager.
Jun 17 21:40:02 MG-Centos7 systemd[1]: Unit strong-pm.service entered failed state.
```

which npm: /root/.nvm/versions/io.js/v2.3.0/bin/npm
which node: /root/.nvm/versions/io.js/v2.3.0/bin/node

**Comment by rmg** [comment]
Your trouble here is from `nvm`, not `iojs`. The problem is `nvm` doesn't install node system-wide, which is generally what is required for system services to operate properly.

**Comment by behrad** [comment]
I read https://github.com/creationix/nvm/issues/745 and https://github.com/strongloop/strongloop/issues/200
it seems I can't use nvm + strongloop in production. 
should I download iojs releases, unzip, ln -s to /usr/bin then!?

**Comment by rmg** [comment]
@behrad that's what I normally do.

```
sudo tar -C /usr/local --strip-components 1 -xf iojs-v2.3.0-linux-x64.tar.xz
```

**Comment by behrad** [comment]
nice one-liner @rmg 
lemme test the whole thing this way :)

**Comment by rmg** [comment]
If you want the real one-liner, and you don't care about verifying the download, there's:
```sh
$ curl -L https://iojs.org/dist/v2.3.0/iojs-v2.3.0-linux-x64.tar.xz | sudo tar -C /usr/local --strip-components 1 -xJf -
```

**Comment by behrad** [comment]
after installing iojs:

```
npm install -g strong-pm
sudo env "PATH=$PATH" sl-pm-install --systemd
sudo /usr/bin/systemctl start strong-pm
```

causes

```
Failed to issue method call: Unit strong-pm.service failed to load: No such file or directory
```

and service status
```
strong-pm.service
   Loaded: not-found (Reason: No such file or directory)
   Active: failed (Result: start-limit) since Wed 2015-06-17 21:40:02 IRDT; 1h 12min ago
 Main PID: 24465 (code=exited, status=203/EXEC)

Jun 17 21:40:02 MG-Centos7 systemd[1]: Unit strong-pm.service entered failed state.
Jun 17 21:40:02 MG-Centos7 systemd[1]: strong-pm.service holdoff time over, scheduling restart.
Jun 17 21:40:02 MG-Centos7 systemd[1]: Stopping StrongLoop Process Manager...
Jun 17 21:40:02 MG-Centos7 systemd[1]: Starting StrongLoop Process Manager...
Jun 17 21:40:02 MG-Centos7 systemd[1]: strong-pm.service start request repeated too quickly, refusing to start.
Jun 17 21:40:02 MG-Centos7 systemd[1]: Failed to start StrongLoop Process Manager.
Jun 17 21:40:02 MG-Centos7 systemd[1]: Unit strong-pm.service entered failed state.
Jun 17 22:50:54 MG-Centos7 systemd[1]: Stopped strong-pm.service.
```

**Comment by behrad** [comment]
this is in my strong-pm.service
`/usr/local/bin/iojs /usr/local/lib/node_modules/strong-pm/bin/sl-pm.js --listen 8701 --base /var/lib/strong-pm --driver direct`
and it works when running it alone...

**Comment by rmg** [comment]
@behrad can you dump the entire `strong-pm.service` file here? Also, you may need to add `/usr/local/bin` to the service's `PATH`.

**Comment by behrad** [comment]
```
# strong-pm
# Generated by strong-service-systemd on 2015-06-17T18:20:22.618Z

[Unit]
Description=StrongLoop Process Manager

# To start/stop strong-pm service manually, run:
#
# systemctl start strong-pm
# systemctl stop strong-pm

[Service]
Type=simple
ExecStart=/usr/local/bin/iojs /usr/local/lib/node_modules/strong-pm/bin/sl-pm.js --listen 8701 --base /var/lib/strong-pm --driver direct
WorkingDirectory=/var/lib/strong-pm

User=strong-pm
Group=strong-pm

# Environment variables:
Environment=HOME=/var/lib/strong-pm


# Allow many incoming connections
LimitNOFILE=infinity
# Allow core dumps for debugging
LimitCORE=infinity

StandardInput=null
StandardOutput=syslog
StandardError=syslog
Restart=always

[Install]
WantedBy=multi-user.target
```

> Also, you may need to add /usr/local/bin to the service's PATH.

Whats the proper way to do that in cent 7?

**Comment by rmg** [comment]
Hm. According to the docs, systemd actually puts `/usr/local/bin` in the PATH for you... Not sure if that is something that CentOS changes or not.

You would set it by adding it to the `Environment=` line, something like this:
```systemd
Environment=HOME=/var/lib/strong-pm PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin
```

Do you have a `/usr/local/bin/node` alias? Or only the `/usr/local/bin/iojs` file?

You should also be able to check your logs to see if there are any error messages from strong-pm itself. Probably in `/var/log/messages` or wherever your system is dumping syslog to.

**Comment by behrad** [comment]
> Do you have a /usr/local/bin/node alias?

i do.

/var/log/messages shows
```
MG-Centos7 iojs: Listening failed with: EACCES: permission denied, open '/var/lib/strong-pm/strong-pm.json'
```

and ls -lt /var/lib/strong-pm
```
srwxr-xr-x. 1 strong-pm strong-pm     0 Jun 17 23:52 pmctl
-rw-r--r--. 1 root      root       8097 Jun 17 23:07 strong-pm.json
drwxr-xr-x. 3 root      root       4096 Jun 17 23:00 svc
-rw-r--r--. 1 root      root      10240 Jun 17 22:57 minkelite.db
-rw-r--r--. 1 strong-pm strong-pm     2 Jun 17 22:50 env.json
```

`sudo chown -R  strong-pm:strong-pm /var/lib/strong-pm` seems to fix this, but eager to know why this happened!

**Comment by rmg** [comment]
Up above when you said "it works when running it alone", would I be correct in guessing that you ran it as `root`?

Those files are initialized on startup of strong-pm, so running as root would result in them being created with root owning them.

**Comment by behrad** [comment]
> Up above when you said "it works when running it alone", would I be correct in guessing that you ran it as root?

didn't sudo, but that may have been causing the issue!

Thank you @rmg for your fast help

**Comment by rmg** [comment]
The `node` and `npm` paths starting with `/root/.nvm/...` is what I was going off of ;-)

Can this issue be closed?

**Comment by behrad** [comment]
thank you @rmg , sure.
