### ISSUE TITLE
[bug?] some of package's dependencies version error

### ISSUE THREAD

**Issue by zhangyaochun** [strongloop/strong-pm#248]
anyone notice that:

1、 [strong-control-channel](https://www.npmjs.com/package/strong-control-channel)   --- 1.3.0
``` 
"strong-control-channel": "^2.0.0"
```

2、[strong-mesh-models](https://www.npmjs.com/package/strong-mesh-models)   --- 7.1.0

```
 "strong-mesh-models": "^8.0.0",
```

3、[strong-runner](https://www.npmjs.com/package/strong-runner)  --- 2.0.0

```
 "strong-runner": "^3.0.0",
```

the above dependencies version are all wrong, for all of their's version is lower in npm.

**Comment by rmg** [comment]
The versions reflect the next major releases of the dependencies, which haven't been published to npm yet. To get those versions you would need to clone the repos and use `npm link`.

The repos are:
 * [strongloop/strong-control-channel](https://github.com/strongloop/strong-control-channel)
 * [strongloop/strong-mesh-models](https://github.com/strongloop/strong-mesh-models)
 * [strongloop/strong-runner](https://github.com/strongloop/strong-runner)
