### ISSUE TITLE
Document how to set app port

### ISSUE THREAD

**Issue by crandmck** [strongloop/strong-pm#251]
PR #250 enables you to set an app's port with `slc ctl env-set <SVC> PORT=<X>`.

Need to document this:
- http://docs.strongloop.com/display/NODE/slc+ctl (drafted & ready to go)
- Somewhere under [Build & deploy](http://docs.strongloop.com/display/SLC/Building+and+deploying)
as the basic way to do it.

**Comment by ernie58** [comment]
Hi, thx for fixing this! 
Any idea when this change will be available through npm install ? 

Thx!

**Comment by chandadharap** [comment]
Hi Ernie, we'll try an back port the fix to the latest release within the next 10 days, hope that helps,
-chanda

**Comment by ernie58** [comment]
That's great: thx!

**Comment by lukewendling** [comment]
:+1: to update the docs.

**Comment by crandmck** [comment]
Added a special row to the table in http://docs.strongloop.com/display/NODE/slc+ctl and a new section at the bottom of http://docs.strongloop.com/display/SLC/Controlling+Process+Manager.
