### ISSUE TITLE
mysql probe reported as broken

### ISSUE THREAD

**Issue by sam-github** [strongloop/strong-pm#258]
https://github.com/strongloop/loopback/issues/1430

unreproduced

@yagobski, what is the mysql version? `npm ls | grep mysql` in your app should tell you that.

**Comment by rmg** [comment]
This _should_ have been fixed by strongloop/strongops#272 which should be in strong-ageng@1.6.1.

**Comment by yagobski** [comment]
This link is dead: strongloop/strongops#272 

My mysql version : 5.5.43

**Comment by rmg** [comment]
@yagobski sorry, that's a link to a private repo.

**Comment by rmg** [comment]
@yagobski what version of strong-agent is installed?

**Comment by yagobski** [comment]
any way to know the version using ssh?

**Comment by rmg** [comment]
@yagobski it's at the top of your logs from the previous issue:
```
$ slc run
INFO strong-agent dashboard is at https://strongops.strongloop.com
INFO strong-agent using collector https://collector.strongloop.com:443
INFO strong-agent v1.5.1 profiling app 'App' pid '30292'
INFO strong-agent[30292] started profiling agent
...
```

If you have not upgraded by doing `slc update` or `npm install -g strongloop` then you are likely still using that version.

**Comment by yagobski** [comment]
INFO strong-agent native addon missing, install a compiler
INFO strong-agent v1.6.0 profiling app 'xxx' pid '2912'
INFO strong-agent[2912] started profiling agent

This is in my local machine. Iam using strong-pm on production and i deploy remotely from local to prod server

**Comment by yagobski** [comment]
In production i have this version : INFO strong-agent v1.6.3

**Comment by Setogit** [comment]
In strongloop/loopback#1430, five people reported the mysql problem -- the first person on June 3rd with strong-agent@1.5.1 and the last person on June 13 with strong-agent@1.6.0.  It is known that strong-agent@1.6.0 works with mysql@2.6.2 but has an issue with mysql@2.7.0 which was released on May 27th.  Mysql@2.8.0 was released on July 13, 2015. As @rmg commented earlier, we fixed the issue in strong-agent@1.6.1 on June 23rd.

@yagobski -- What version of mysql driver was installed when you experienced the difficulty?  You commented that you have strong-agent v1.6.3 in production.  Do you have the same difficulty in production?  What version of mysql driver is installed in production?

**Comment by sam-github** [comment]
@yagobski our theory is that you are running into a bug we already fixed, can you confirm that this is fixed by updating?

**Comment by yagobski** [comment]
fixed i upgrade all modules and all is fine.
Thanks for your help

2015-07-16 18:10 GMT+02:00 Sam Roberts <notifications@github.com>:
