### ISSUE TITLE
NODE_ENV=production using remote to strong-pm?

### ISSUE THREAD

**Issue by yagobski** [strongloop/strong-pm#261]
Hy,

I want to set specific env variable when i do slc build   slc deploy http://xxxxxx
I want to use specific configuration file when i deploy. How strong-pm handle that?
Something like  NODE_ENV=production slc deploy http://xxxxx

**Comment by sam-github** [comment]
You can't do it as a single shot with the `slc deploy`, you have to create the service, then deploy to it:

```
slc ctl create some-svc-name
slc ctl env-set some-svc-name NODE_ENV=production
slc deploy --service=svc-name http://xxxx
```

Next time you deploy the service already exists, you can just do (assuming there is something you want to change about the env):

```
slc ctl env-set some-svc-name FU=BAR
slc deploy --service=some-svc-name http://xxxx
```

NOTE you don't have to create the service if you've already deployed to it: deploy auto-creates the service (with default env, etc., and service name from the package.json), so you won't have to do `slc create` unless this is a brand new pm that the app has never been deployed to.

/cc @crandmck I think this may be a FAQ: how do I set up a service before deploying to it (set-size, env-set, etc.).

**Comment by crandmck** [comment]
@sam-github I added http://docs.strongloop.com/display/SLC/Deploying+applications+with+slc#Deployingapplicationswithslc-Settingupaservicebeforedeployment to cover this information.  It's just a start--can expand more as needed.

**Comment by yagobski** [comment]
Perfect this is was i am looking for. Thanks

2015-07-17 0:42 GMT+02:00 Rand McKinney <notifications@github.com>:
