### ISSUE TITLE
Delete old deployments files in Strong-pm

### ISSUE THREAD

**Issue by yagobski** [strongloop/strong-pm#263]
All time i make new deploy i have the old version stored in my server. Do you have add any configuration to keep only the last 10 deployments for exemple? All time i need to clean it manually.

Any solution also to switch between deployments? For exemple to comback to old version?

**Comment by sam-github** [comment]
I'm sorry, we don't delete the old deployments at the moment, but we should.

Switching between versions is best done, ATM, by using `slc build` and tracking what you have deployed:
- either keeping the .tgz packfiles around
- or using a deploy git branch, so you can re-deploy any commit

We will have better management and staging of deployments in the future, but we don't at the moment.

**Comment by erikverheij** [comment]
My server ran short on available inodes. It apears that my strongloop-pm deployments are consuming 80% of the available inodes.

Removing old deployments should be part of the default deployment flow. 

For the time being I use the following command to remove old deployments;

````
# List all deployments excluding the current;
ls -ldt /var/lib/strong-pm/svc/1/work/* | tail -n +3
# List and remove all deployments excluding the current;
ls -ldt /var/lib/strong-pm/svc/1/work/* | tail -n +3 | sudo xargs rm -rf
````

Replace the "1" with the id of your app.

**Comment by sam-github** [comment]
I'm sorry for the delay, dealing with this is near the top of our backlog.

Just an FYI: The reason this isn't just a trivial `deploy the new, rm -rf the last` in strong-pm is that it does zero-downtime restarts, the app is restarted by starting one worker after another in the new deployment directory, and until all the workers have restarted and *not crashed* for some minimal time, there are still old workers running on the previous deployment, so deleting immediately would actually delete the working directory of running workers. We need to wait until we *know* that all old workers have moved to the new deployment.

Also, we're thinking of keeping the deployments around, and exposing them, to allow rolling forward and back to arbitrary deployments, though that could require explicit removal on your part, and/or  a `--gc` flag to the deploy command to remove any unused deployments.

**Comment by sam-github** [comment]
Btw, the above behaviour is observable, if you deploy an app that requires files not in its package dependencies (or has some trivial syntax error), you'll see how pm keeps most of the old workers running until the new code doesn't crash.

**Comment by cgole** [comment]
backlogged.

**Comment by cgole** [comment]
https://github.com/strongloop-internal/scrum-nodeops/issues/913

**Comment by lkrnac** [comment]
+1

**Comment by ebarault** [comment]
i ran out of disk space at some point because of this, and strong-pm started mess up totally. nodejs process at 100%, connection refused when trying to connect remotely. rebooting, removing, reloading conf, restarting were of no help. I had for only solution to remove totally strong-pm est reinstall it from scratch after freeing some space.

Would someone provide a way to reset totally strong-pm state without removing/reinstalling? or any other mean to sort my issue out?
Where should i look for interesting strong-pm logs?

**Comment by despairblue** [comment]
You could stop the strong-pm service via upstart/systemd and delete the
strong-pm data dir. Somewhere in /usr/share I think. I'm on my phone so I
can't check.
When you start strong-pm after that it's completely pristine again.

Hope that helps.

On Thu, Apr 14, 2016, 20:16 ebarault <notifications@github.com> wrote:

> i ran out of disk space at some point because of this, and strong-pm
> started mess up totally. nodejs process at 100%, connection refused when
> trying to connect remotely. rebooting, removing, reloading conf, restarting
> were of no help. I had for only solution to remove totally strong-pm est
> reinstall it from scratch after freeing some space.
>
> Would someone provide a way to reset totally strong-pm state without
> removing/reinstalling? or any other mean to sort my issue out?
> Where should i look for interesting strong-pm logs?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/strongloop/strong-pm/issues/263#issuecomment-210084258>
>
-- 
Q: Why is this email five sentences or less?
A: http://five.sentenc.es

**Comment by ebarault** [comment]
@despairblue Are you referring to the /var/lib/strong-pm/svc dir ?
I tried this a couple of time by the past but didn't help and had no choice than removing everything and start over.
How can I see useful logs to investigate?

**Comment by ebarault** [comment]
/var/log/syslog gives 

```Apr 23 20:53:44 web01 kernel: [809733.843515] init: strong-pm main process (14734) terminated with status 1
Apr 23 20:53:44 web01 kernel: [809733.843533] init: strong-pm main process ended, respawning
Apr 23 20:53:45 web01 kernel: [809734.907545] init: strong-pm main process (14740) terminated with status 1
Apr 23 20:53:45 web01 kernel: [809734.907564] init: strong-pm main process ended, respawning
Apr 23 20:53:46 web01 kernel: [809735.969654] init: strong-pm main process (14746) terminated with status 1
Apr 23 20:53:46 web01 kernel: [809735.969672] init: strong-pm main process ended, respawning
Apr 23 20:53:47 web01 kernel: [809737.031126] init: strong-pm main process (14752) terminated with status 1
Apr 23 20:53:47 web01 kernel: [809737.031145] init: strong-pm main process ended, respawning```

**Comment by sam-github** [comment]
@ebarault can you report this as a different bug, it seems complete unrelated to this (and clarify what you mean by `node v14 instead of v47`, there is no node of those versions). FYI, strong-pm needs to store data to disk, the memory connector we used before was intended only as a test tool, it was not a robust DB, and cannot be made to be one, so we switched to a  real DB (sqlite3).

**Comment by ivanschwarz** [comment]
Hello, is there any progress on this issue? It was near the top of a backlog on Jul 30, 2015.

**Comment by paulJordaan** [comment]
+1

**Comment by ebarault** [comment]
for what it's worth given the different issues encountered with strong-pm,
we are currently moving away from it in favor of docker images operated
with docker-compose and gitlab-ci for automated deployments



2016-09-16 12:04 GMT+02:00 Paul Jordaan <notifications@github.com>:

**Comment by dycode** [comment]
We registered cron job to remove old releases every day on Debian server with this command:

```
$ find /var/lib/strong-pm/svc/1/work/ -mindepth 1 -maxdepth 1 ! -name $(basename `readlink -f /var/lib/strong-pm/svc/1/work/current`) -type d -exec rm -rf {} +
```
