### ISSUE TITLE
Koa support?

### ISSUE THREAD

**Issue by newlix** [strongloop/strong-pm#264]
Can I run Koa with strongloop-pm? 
How can I pass the --harmony option or can I use io.js ?

**Comment by rmg** [comment]
There's no way to pass `--harmony` to node when running your app under strong-pm, but iojs is supported.

**Comment by sam-github** [comment]
@newlix are you good for Koa, by using io.js?

**Comment by newlix** [comment]
Sorry for the late reply. 
In the end I didn't use strong-pm with io.js. I are using pm2 for now.
Thanks for your help.

**Comment by sam-github** [comment]
Thanks for getting back to us. Did you continue to have trouble with Koa.js, or was there some other issue with strong-pm?

**Comment by newlix** [comment]
No, they both run well on iojs. I just want to stick to Node.js for max stability and user popularity.

**Comment by sam-github** [comment]
OK, thanks for the feedback.
