### ISSUE TITLE
strong-pm stop/waiting on CentOS 6.6

### ISSUE THREAD

**Issue by danielrvt** [strongloop/strong-pm#267]
I'm deploying an API so I installed node and strong-pm in my server. I installed node using nvm, and then I installed strong-pm.

I added strong-pm to upstart like this:

$ sudo sl-pm-install --upstart=0.6
$ sudo /sbin/initctl start strong-pm

but the strong-pm service is always "stop/waiting" Why is this happening?

**Comment by sam-github** [comment]
nvm installs node for only the current user, but strong-pm runs as the strong-pm user.

nvm is a user-tool, it installs node in your personal ~/.nvm director, its not recommended to use it to install node for system services.

**Comment by rmg** [comment]
@crandmck here's another example of `nvm` causing problems. You've added a warning about it in the docs now, correct?

**Comment by crandmck** [comment]
Yes, there's a prominent warning here: https://docs.strongloop.com/display/SLC/Setting+up+a+production+host#Settingupaproductionhost-InstallusingnpmandrunPMservice

Let me know if you think it needs to be added elsewhere.

**Comment by rmg** [comment]
@crandmck thanks, looks pretty prominent to me.
