### ISSUE TITLE
Build with io.js 3.0.0

### ISSUE THREAD

**Issue by cjbratschke** [strongloop/strong-pm#269]
I'm using io.js 3.0.0 on a ubuntu server 14.04 and tried to build strong-pm, which is currently not possible. Could you help me out with that?

**Comment by rmg** [comment]
This is currently not possible due to a number of binary dependencies not being compatible with the version of v8 used by iojs-v3.0.0.
 - [ ] sqlite3
 - [ ] strong-fork-syslog
 - [ ] utf-8-validate
 - [ ] bufferutil

**Comment by rmg** [comment]
For the record, the only dependency that is actually blocking is sqlite3. The others are all optional.

**Comment by cgole** [comment]
strong-pm build  on mac failed with latest iojs - 3.3.0 - https://gist.github.com/cgole/8c56086298cf97f0c7d8
strong-pm build on ubuntu failed with latest iojs-3.3.0 -
https://gist.github.com/cgole/bb5d4f081c802f62e14b

**Comment by rmg** [comment]
@cgole those logs appear to include errors that have already been fixed. Did you install from staging?

**Comment by cgole** [comment]
Error for install from staging - 
errors on mac - https://gist.github.com/cgole/5dbe6ca7a5cca0ea0a6e
errors on ubuntu - https://gist.github.com/cgole/72cc0c22a8fdf6d18423

**Comment by rmg** [comment]
@cgole thanks for confirming we're blocked on node-sqlite3 (mapbox/node-sqlite3#495)

**Comment by sam-github** [comment]
@cgole do you want to re-verify that `slc` and all runs on v4.x, or can this be closed?

**Comment by rmg** [comment]
I was able to install and run `slc start`, `slc deploy`, and `slc pm` on node-v4.0.0 while verifying strongloop/strongloop#248 if that helps any.

I didn't do anything in depth, just made sure it installed and I could run & deploy apps, but I think it shows that this issue as reported has been resolved.

**Comment by cgole** [comment]
verified. I left this open because I ran into some issues creating a loopback app, but turned out I just had some permission issues.
