### ISSUE TITLE
Cant connect to postgres 

### ISSUE THREAD

**Issue by PhuongNL** [strongloop/strong-pm#271]
My app cant connect to postgres container when i deploy to docker run on CentOS 7. But when i development on docker local i still can connect to db. I dont know why, here is logs on docker strong-pm:

```
2015-08-19T16:06:54.067Z pid:4059 worker:400 Connection fails:  { [Error: connect EHOSTUNREACH 192.168.6.70:5432]
2015-08-19T16:06:54.067Z pid:4059 worker:400   code: 'EHOSTUNREACH',
2015-08-19T16:06:54.067Z pid:4059 worker:400   errno: 'EHOSTUNREACH',
2015-08-19T16:06:54.067Z pid:4059 worker:400   syscall: 'connect',
2015-08-19T16:06:54.067Z pid:4059 worker:400   address: '192.168.6.70',
2015-08-19T16:06:54.067Z pid:4059 worker:400   port: 5432 }
2015-08-19T16:06:54.067Z pid:4059 worker:400 It will be retried for the next request.
2015-08-19T16:06:54.068Z pid:4059 worker:400 events.js:141
2015-08-19T16:06:54.068Z pid:4059 worker:400       throw er; // Unhandled 'error' event
2015-08-19T16:06:54.068Z pid:4059 worker:400             ^
2015-08-19T16:06:54.068Z pid:4059 worker:400 Error: connect EHOSTUNREACH 192.168.6.70:5432
2015-08-19T16:06:54.068Z pid:4059 worker:400     at Object.exports._errnoException (util.js:814:11)
2015-08-19T16:06:54.068Z pid:4059 worker:400     at exports._exceptionWithHostPort (util.js:837:20)
2015-08-19T16:06:54.068Z pid:4059 worker:400     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1047:14)
```

**Comment by rmg** [comment]
The error says `EHOSTUNREACH`, meaning it can't connect to the DB because that address is unreachable. Generally you use names for container-to-container connections because the IPs may change. Did you link your strong-pm container to your postgres container?

**Comment by PhuongNL** [comment]
I dont link container sir, i connect via port. In strong-pm container local i can connect to remote container db.

**Comment by rmg** [comment]
If the pm container is running on the same host as the Postgres container then it will not have access to the Postgres container via the public IP unless you have specifically set up iptables rules to allow it. Is the address you are using on the docker0 bridge network? Or is it the same address you use to connect from the pm container when running locally?

strong-pm doesn't touch the network configuration so it seems unlikely that it would cause a process running under it to not be able to find a route to another network. Can you give more details about your network?

**Comment by PhuongNL** [comment]
strong-pm and postgres container run on same remote host.
Here is my network info in remote server:
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: enp2s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether d8:cb:8a:55:05:5d brd ff:ff:ff:ff:ff:ff
    inet 192.168.6.70/24 brd 192.168.6.255 scope global enp2s0
       valid_lft forever preferred_lft forever
    inet6 fe80::dacb:8aff:fe55:55d/64 scope link
       valid_lft forever preferred_lft forever
3: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP
    link/ether 02:42:3e:e6:df:5c brd ff:ff:ff:ff:ff:ff
    inet 172.17.42.1/16 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:3eff:fee6:df5c/64 scope link
       valid_lft forever preferred_lft forever
```
Maybe i know the problem.

**Comment by PhuongNL** [comment]
@rmg you are right about both strong-pm and postgres run on same host, thanks u so much.
After research i found the solution, maybe help another people.

- When your create container strong-pm, remember link it with postgres, redis.
- In your project create datasource.local.js or datasource.production.js with this content:
```
module.exports = {
  postgresDs: {
    "host": process.env.POSTGRES_PORT_5432_TCP_ADDR || 'localhost',
    "port": 5432,
    "database": '<database_name>',
    "password": '<database_pass>',
    "name": 'postgresDs',
    "connector": 'postgresql',
    "user": '<database_user>'
  }
};
```
If u use redis for store session here is solution: 

- Create session.js in boot folder with this content:

```
module.exports = function (app) {
  var session = require('express-session');
  var RedisStore = require('connect-redis')(session);
  app.middleware('session', session({
    secret: 'keyboard cat',
    resave: true,
    saveUninitialized: true,
    store: new RedisStore({
      host:  process.env.REDIS_PORT_6379_TCP_ADDR || '127.0.0.1',
      port:  process.env.REDIS_PORT_6379_TCP_PORT || 6379
    })
  }));
};
```

**Comment by rmg** [comment]
@PhuongNL thanks for confirming my suspicions and providing this guide for anyone else who might need it :-)
