### ISSUE TITLE
strong-pm 5.0.0 - failed with Error: connect ECONNREFUSED

### ISSUE THREAD

**Issue by glesage** [strongloop/strong-pm#272]
After updating global npm packages I get a `failed with Error: connect ECONNREFUSED` error when trying to `slc pmctl` or `slc ctl`

Here are my versions
```
strongloop v5.0.0 (node v0.10.25)
├── strong-arc@1.8.1
├── strong-build@2.0.4
├── strong-deploy@3.0.0
├── strong-mesh-models@8.0.0
├── strong-pm@5.0.0
├── strong-registry@1.1.5
├── strong-start@1.3.0
├─┬ strong-supervisor@3.0.2
│ └── strong-agent@1.6.4
├── generator-loopback@1.11.0
├── node-inspector@0.7.4
└── nodefly-register@0.3.3
```

**Comment by rmg** [comment]
@glesage was strong-pm previously installed as an OS service? If so, did you stop it before the upgrade and start it after?

**Comment by glesage** [comment]
Hm yes it was installed and no I did not stop it /:

**Comment by rmg** [comment]
@glesage have you tried starting or restarting it to make sure it is running again?

**Comment by glesage** [comment]
Yes, it is running since our loopback app is running.. also just restarted it and am getting the same error /:

`Command "status" on "http://127.0.0.1:8701" failed with Error: connect ECONNREFUSED`

**Comment by rmg** [comment]
@glesage I'm at a loss for how strong-pm could be running your app but not accepting connections itself. Do you want to hop on https://gitter.im/strongloop/chat and see if we can debug this?

**Comment by glesage** [comment]
Ha ok. Well I'll try a few other things but I'm also at my wits end... I've experienced this before actually when upgrading all npm global packages on dev environments. Usually end up re-installing strong-pm as a service clean.. should have probably looked to see the root cause of this instead.

I'll monitor that channel just in case tomorrow (:

**Comment by glesage** [comment]
Thks @rmg for the help, turns out it was because I upgraded from a version that used was using domain sockets by default AND the old version I had didn't have a default port yet
