### ISSUE TITLE
cluster-restart doesn't work with main scripts in subfolders.

### ISSUE THREAD

**Issue by simoami** [strongloop/strong-pm#283]
After redeploying updated versions of a test project, slc deploy restarts workers with the old code when the main file is located in subfolders. The following scenarios were tested:
package.main: “index.js” - WORKS
package.main: “server.js” - WORKS
package.main: “server/index.js” - FAILS
package.main: “server/server.js” - FAILS

Here's our test script (index.js):
```
'use strict';

var express = require('express');
var version = require('./package.json').version;

console.log('Current Version: ' + version);

module.exports = function() {
  var app = express();

  app.get('/', function(req, res) {
    res.send('Current Version: ' + version);
  });

  app.get('/api', function(req, res) {
    res.json({
      cwd: process.cwd(),
      message: 'Hello World',
      pid: process.pid,
      version: version,
    });
  });

  return app;
};
```

The following commands where run to reproduce this behavior:
```
npm version patch
slc build --pack
slc deploy -s express-app -z 2 http:localhost:8701 ../express-app-1.0.x.tgz 
```

Each time the project is bumped and deployer, the workers are expected to log an updated version to the console and via http. but this doesn't happen with subfolders.

**Comment by rmg** [comment]
Some notes:
Just digging through any related code I'm seeing some PRs to investigate:
 - strongloop/strong-supervisor#157
 - strongloop/strong-supervisor#144 which fixed a regression caused by strongloop/strong-supervisor#142

**Comment by rmg** [comment]
So far it's looking like another regression caused by strongloop/strong-supervisor#142 :blush:

**Comment by rmg** [comment]
strong-supervisor@3.3.0 has been released and includes the fix for this. @simoami can you update and give it a spin?
