### ISSUE TITLE
slc deploy shows fatal err on kerberos build error via mongodb connector

### ISSUE THREAD

**Issue by notbrain** [strongloop/strong-pm#285]
Haven't seen this before but when I attempt a deploy 

    slc deploy -s proteus-demo http://localhost:8701 demo-deploy

The strong-pm.log shows

    sl-pm.js: Service "1" listening on 0.0.0.0:3002
    In file included from ../lib/kerberos.cc:1:0:
    ../lib/kerberos.h:5:27: fatal error: gssapi/gssapi.h: No such file or directory
     #include <gssapi/gssapi.h>
                               ^
    compilation terminated.
    make: *** [Release/obj.target/kerberos/lib/kerberos.o] Error 1
    gyp ERR! build error
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
    gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
    gyp ERR! System Linux 3.13.0-48-generic
    gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /var/lib/strong-pm/svc/2/work/cbe323e706c5dda1d3e1bc463cd352071c0c7bc0.1444781004074/node_modules/loopback-connector-mongodb/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
    gyp ERR! node -v v0.12.7
    gyp ERR! node-gyp -v v2.0.1
    gyp ERR! not ok

Do I need to install kerberos or something with mongodb so it can compile? Having issues related to strong-pm deployment where new code is not resident immediately, wondering if this is related.

**Comment by Setogit** [comment]
http://stackoverflow.com/questions/32919589/npm-install-mongoose-causes-gyp-and-kerberos-errors-gssapi-gssapi-h-file-not-fo

Try installing the Kerberos Development Package:

`apt-get install libkrb5-dev`

**Comment by notbrain** [comment]
Thank you.
