### ISSUE TITLE
app does not start on Ubuntu 14.04 Error: Cannot find module 'strong-debugger/package.json'

### ISSUE THREAD

**Issue by jgngo** [strongloop/strong-pm#286]
I installed strongloop PM on Ubuntu 14.04 using the instructions. I'm using the nodesource repository node.js 4.2.0.
```
$ npm install -g strong-pm
$ sudo sl-pm-install
$ sudo /sbin/initctl start strong-pm 
```

When I run slc deploy from my client to the production server where strongloop PM is installed, it returns normally:

```
Deployed `../node-cliqq-versions-1.0.0.tgz` as `node-cliqq-versions` to `http://intranet:8701/`
```

However, the app does not start on http://intranet:3001. slpmctl shows that the service has not started. I try to start it manually using slpmctl start node-cliqq-versions but it still does not start. This error message appears in /var/log/upstart/strong-pm.log continuously. 

```
Error: Cannot find module 'strong-debugger/package.json'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/lib/node_modules/strong-pm/node_modules/strong-runner/node_modules/strong-supervisor/lib/runctl.js:4:23)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
Unexpected exit with 1 from Runner: commit default/npm-pack
```

**Comment by rmg** [comment]
@jgngo thanks for reporting this. I've added a note to the existing strong-supervisor issue related to this (strongloop/strong-supervisor#163) so I'm going to close this one.

**Comment by rmg** [comment]
Better yet, there's a PR in progress to fix this: strongloop/strong-supervisor#166

**Comment by rmg** [comment]
@jgngo strong-supervisor@3.3.0 has been released and should fix this. Please re-run `npm install -g strong-pm` to get the update and let us know if it works for you.

**Comment by jgngo** [comment]
Works beautifully now. Thanks.

**Comment by rmg** [comment]
:tada: glad to hear it
