### ISSUE TITLE
How can I deploy on the AWS EC2/Elasticbeanstalk?

### ISSUE THREAD

**Issue by smilechun** [strongloop/strong-pm#288]
I cannot found any useful tips for me to deploy a loopback application to strong-pm on AWS.

I have tried to create an ubuntu instance on AWS EC2 and installed the strong-pm on such instance. However, i got the "failed: socket hang up" when I entered the command "slc deploy http://username:password@.us-west-2.compute.amazonaws.com". 

I am new to strongloop and aws.
Please give some helps.....

**Comment by sam-github** [comment]
Did you install strong-pm with a username/password, using the `-http-auth` option to `sl-pm-install`?

https://github.com/strongloop/strong-pm/blob/master/bin/sl-pm-install.txt#L26

I suspect you are using your amazon user/pass, and that pm was installed with no authentication (which is not recommended).

**Comment by smilechun** [comment]
Same,  Yes,  i did.  

I wonder if there are any missing configuration on my aws.
