### ISSUE TITLE
docker driver to support base image customization

### ISSUE THREAD

**Issue by ycao56** [strongloop/strong-pm#294]
Currently, the strong-pm docker driver uses its own base image. In our use case, we want to be able to have control over the content of the base image. e.g. use IBM node, preinstall some npm modules, environment variables configuration. I think supporting a customized base image is going to be very helpful. 
Basically, the use case would be
1. prepare and build our own docker base image
2. deploy a customized base image
3. configure the strong-pm server to manage the app running inside the container

Hope it makes sense.

**Comment by rmg** [comment]
The way strong-pm currently builds docker images is described a bit in [a blog post](https://strongloop.com/strongblog/containerizing-node-js-apps-with-docker-and-strongloop/).

Short version:
 1. receive app from `slc deploy`
 2. use a generic **build image** ([node:0.10](https://github.com/nodejs/docker-node/blob/d798690bdae91174715ac083e31198674f044b68/0.10/Dockerfile)) to install strong-supervisor + **app**
 3. create an **app image** based on a **deployment image** ([node:0.10-slim](https://github.com/nodejs/docker-node/blob/d798690bdae91174715ac083e31198674f044b68/0.10/slim/Dockerfile)) by copying the strong-supervisor and **app** from the **build image** 
 4. launch a container from the custom **app image**

@yucao84 are you wanting to build your own **app image** and have strong-pm just launch it? Or do you want to provide your own **base image** and **deploy image** that strong-pm uses to build your **app image** from?

**Comment by yucao84** [comment]
@rmg I think the first option will give me more flexibility on the content of docker image. In my image, I don't mind to install strong-pm or whatever is necessary in order to work with strong-pm. The idea is that I can have a ready to use image prebuilt and when it is launched it could be simply connect to a strong-pm server and managed by it.

**Comment by rmg** [comment]
Thanks for the clarification. Sounds like this will involve:
 * [ ] document the expected image spec (`ENTRYPOINT`, which ports to use, etc.)
 * [ ] accept a docker image as a deployment type or allow overriding of generated image names

**Comment by yucao84** [comment]
@rmg Yes. The very similar working approach I am taking at the moment is putting the app and strongloop in the image and use ```ENTRYPOINT slc start . && tail -F ~/.strong-pm/start.log``` to start the app and keep the docker container running.
This starts strong-pm in <b>local mode</b> . The disadvantage for this is that the strong-pm server exists in every docker container. Is it ok to use this in production as long as I take care of the security of strong-pm access?

**Comment by sam-github** [comment]
@rmg do we need to backlog some of this?

**Comment by yucao84** [comment]
Is there an estimation on this?

**Comment by sam-github** [comment]
Looks like a nice feature, would like to have it, no time to do it. Do you have time?
