### ISSUE TITLE
Install problem !

### ISSUE THREAD

**Issue by toplinuxsir** [strongloop/strong-pm#295]
npm install -g strong-pm --build-from-source 

  SOLINK_MODULE(target) Release/obj.target/debugger.node
  COPY Release/debugger.node
make: Leaving directory '/usr/lib/node_modules/strong-pm/node_modules/strong-runner/node_modules/strong-supervisor/node_modules/strong-debugger/build'

> sqlite3@3.1.1 install /usr/lib/node_modules/strong-pm/node_modules/minkelite/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/5.1.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/strong-pm/node_modules/minkelite/node_modules/sqlite3/.node-gyp"
make: Entering directory '/usr/lib/node_modules/strong-pm/node_modules/minkelite/node_modules/sqlite3/build'
make: **\* No rule to make target '../.node-gyp/5.1.0/include/node/common.gypi', needed by 'Makefile'.  Stop.
make: Leaving directory '/usr/lib/node_modules/strong-pm/node_modules/minkelite/node_modules/sqlite3/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/lib/node_modules/strong-pm/node_modules/minkelite/node_modules/sqlite3/lib/binding/node-v47-linux-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/usr/lib/node_modules/strong-pm/node_modules/minkelite/node_modules/sqlite3/lib/binding/node-v47-linux-x64"
gyp ERR! cwd /usr/lib/node_modules/strong-pm/node_modules/minkelite/node_modules/sqlite3
gyp ERR! node -v v5.1.0
gyp ERR! node-gyp -v v3.2.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/lib/node_modules/strong-pm/node_modules/minkelite/node_modules/sqlite3/lib/binding/node-v47-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/usr/lib/node_modules/strong-pm/node_modules/minkelite/node_modules/sqlite3/lib/binding/node-v47-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/strong-pm/node_modules/minkelite/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Linux 3.16.0-4-amd64
node-pre-gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/strong-pm/node_modules/minkelite/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/lib/node_modules/strong-pm/node_modules/minkelite/node_modules/sqlite3
node-pre-gyp ERR! node -v v5.1.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.14
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/lib/node_modules/strong-pm/node_modules/minkelite/node_modules/sqlite3/lib/binding/node-v47-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/usr/lib/node_modules/strong-pm/node_modules/minkelite/node_modules/sqlite3/lib/binding/node-v47-linux-x64' (1)
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "strong-pm" "-g" "--build-from-source"
npm ERR! node v5.1.0
npm ERR! npm  v2.14.13
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@3.1.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@3.1.1 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request

**Comment by rmg** [comment]
I'm not able to reproduce this on my Mac, I'll try on a Linux VM next.

**Comment by toplinuxsir** [comment]
I change to node 4.2.2 and npm2 
Still procduce the error !

**Comment by rmg** [comment]
So far it appears to be a bug in node-gyp v3.2.0, specifically with how it handles using a temporary location for downloading the node headers/source... still investigating.

**Comment by rmg** [comment]
@toplinuxsir as a potential workaround and confirmation of my theory, does it work if you use `--unsafe-perm`?

**Comment by toplinuxsir** [comment]
Yes, It  works ,Thanks !

**Comment by rmg** [comment]
Now to track down what the root of the problem is..

**Comment by sam-github** [comment]
@rmg can we submit upstream?

**Comment by dominikriedel** [comment]
Hey! Did you get a solution already? 

I've got the same problem: 
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:357:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 2.6.32-042stab111.12
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/lib/node_modules/sqlite3/lib/binding/node-v46-linux-ia32/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/usr/lib/node_modules/sqlite3/lib/binding/node-v46-linux-ia32"
gyp ERR! cwd /usr/lib/node_modules/sqlite3
gyp ERR! node -v v4.2.3
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/lib/node_modules/sqlite3/lib/binding/node-v46-linux-ia32/node_sqlite3.node --module_name=node_sqlite3 --module_path=/usr/lib/node_modules/sqlite3/lib/binding/node-v46-linux-ia32' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Linux 2.6.32-042stab111.12
node-pre-gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/lib/node_modules/sqlite3
node-pre-gyp ERR! node -v v4.2.3
node-pre-gyp ERR! node-pre-gyp -v v0.6.14
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/lib/node_modules/sqlite3/lib/binding/node-v46-linux-ia32/node_sqlite3.node --module_name=node_sqlite3 --module_path=/usr/lib/node_modules/sqlite3/lib/binding/node-v46-linux-ia32' (1)
npm ERR! Linux 2.6.32-042stab111.12
npm ERR! argv "/usr/bin/nodejs" "/usr/local/bin/npm" "install" "-g" "sqlite3" "--unsafe-perm" "--no-rollback"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.15
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@3.1.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@3.1.1 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/bin/npm-debug.log

Even with --unsafe-perm it does not install. Seems to be a problem with sqlite3 as i can't actually install sqlite3 by itself.

**Comment by toplinuxsir** [comment]
npm install -g youpackaged --unsafe-perm


2015-12-16 16:17 GMT+08:00 dominikriedel <notifications@github.com>:

**Comment by dominikriedel** [comment]
> Even with --unsafe-perm it does not install. Seems to be a problem with sqlite3 as i can't actually install > sqlite3 by itself."

already tried!

**Comment by pleivac** [comment]
Does anybody gets a solution for this?

I have tried npm install -g strongloop --unsafe-perm, but it doesn't work. The result:

npm ERR! Linux 4.4.0-21-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "strongloop" "--unsafe-perm"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! path /usr/lib/node_modules/strongloop/node_modules/loopback-sdk-angular-cli/bin/lb-ng
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/lib/node_modules/strongloop/node_modules/loopback-sdk-angular-cli/bin/lb-ng'
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/lib/node_modules/strongloop/node_modules/loopback-sdk-angular-cli/bin/lb-ng'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

**Comment by rmg** [comment]
@pleivac you are seeing strongloop/loopback#2714 which was fixed by strongloop/strongloop#318 and released as strongloop@6.0.2 a few hours ago. You should be able to install now.
