### ISSUE TITLE
README and strong-pm.io should advertise systemd/upstart integration

### ISSUE THREAD

**Issue by bnoordhuis** [strongloop/strong-pm#298]
https://www.npmjs.com/package/strong-pm <- no mention

http://strong-pm.io/compare/ <- no mention

**Comment by sam-github** [comment]
It's here: http://strong-pm.io/prod/#npm-install, but I agree, its a nice feature, and worth boosting.

**Comment by crandmck** [comment]
It's also described in detail here https://docs.strongloop.com/display/SLC/Setting+up+a+production+host.
But we can certainly highlight it better on strong-pm.io & in README.
