### ISSUE TITLE
Is docker required to run strong-pm in a production hosting environment? 

### ISSUE THREAD

**Issue by pvijeh** [strongloop/strong-pm#302]
These docs mention docker ---> 

http://strong-pm.io/prod/

is that a requirement for hosting a strong-loop app using strong-pm ?

**Comment by rmg** [comment]
No, docker is not required. Those docs are referring to 2 different uses of docker, both of which are optional:
 1. run strong-pm itself inside a docker container
 2. run strong-pm on the server and have it run your apps as docker containers

Neither of those is the default.
