### ISSUE TITLE
Failed to start any applications

### ISSUE THREAD

**Issue by kylezengTR** [strongloop/strong-pm#310]
Hi guys,
I`m using RHEL 6 and my node is in the folder I have created.
here is the strong-pm.conf :

`exec su -m -s /bin/sh -c 'exec "$0" "$@"' strong-pm -- /appserver/node-v4.2.0-linux-x64/bin/node /appserver/node-v4.2.0-linux-x64/lib/node_modules/strong-pm/bin/sl-pm.js --listen 8701 --base /var/lib/strong-pm --base-port 3000 --driver direct 2>&1`

And I added this to strong-pm.conf 

`env PATH=/appserver/node-v4.2.0-linux-x64/bin:/appserver/java/jdk1.8.0_11/bin:/sbin:/bin:/usr/sbin:/usr/bin`

Right now, I have almost 20 services, and come of these services can successfully deployed to the remote server, some of them can`t, Even I go to the remote server, and download the package, try 'node app.js' to make sure it can be running, these microservices still can`t be deployed. It gonna report like this:

```
Service ID: 12
Service Name: sequence222
Environment variables:
    Name  Value
    PORT  8017
Instances:
    Version  Agent version  Debugger version  Cluster size  Driver metadata
     5.1.0       2.0.2             n/a              4             N/A
Processes:
        ID       PID   WID  Listening Ports  Tracking objects?  CPU profiling?                                                                                       Tracing?  Debugging?
    12.1.20612  20612   0
    12.1.20617  20617   1     0.0.0.0:8017
    12.1.20622  20622   2     0.0.0.0:8017
    12.1.20627  20627   3     0.0.0.0:8017
    12.1.20632  20632   4     0.0.0.0:8017

Service ID: 13
Service Name: cm333
Environment variables:
  No environment variables defined
Instances:
    Version  Agent version  Debugger version  Cluster size  Driver metadata
Not started

```

Could anybody tell me that what make strong-pm decide which services can be deployed?

**Comment by sam-github** [comment]
https://github.com/strongloop/strong-supervisor/blob/master/bin/sl-run.txt#L5-L20

^--- npm install -g strong-supervisor, then sl-run the app to confirm it can be found.

Also, check the logs for the service, it could be crashing.
