### ISSUE TITLE
Perf : Please make a switch for profiling

### ISSUE THREAD

**Issue by mossuchida** [strongloop/strong-pm#313]
Currently, Strong PM has profiling enabled by default, however, this will reduce the performance.  

Enhancement Request  1 :
Please add a switch so that user is able to turn on or turn off the profiling

Enhancement Request  2 :
For Bluemix purpose, please enable profile turn on/off by using the "User Defined" Bluemix Environment Variables so that we can easily enable/disable it.

BTW, am I allowed to fix the code by myself if I follow the guildelines??

**Comment by sam-github** [comment]
Any restrictions you have are between you and your managers.

Supervisor has a `--no-profile` CLI option. choosing when to set it, exposing a rest api to turn it on/off, etc, all is possible.

Note that profiling can't be turned on/off for a running node app, it is a start-time state. So, you'd need to do something like we do for tracing, which is even more expensive and defaults to "off". Follow the code through strong-pm/strong-mesh-models/strong-supervisor, and you will see how it works. It may not work like you like.

**Comment by mossuchida** [comment]
Closing issue based on priorities
