### ISSUE TITLE
Network timeout installing

### ISSUE THREAD

**Issue by jesucarr** [strongloop/strong-pm#315]
npm install -g strong-pm
npm ERR! fetch failed http://blip.strongloop.com/strong-pm@5.1.0
npm WARN retry will retry, error on last attempt: Error: connect ETIMEDOUT 54.230.228.240:80
loadDep:sl-blip → network ▀ ╢██████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟

node v5.5.0
npm 3.3.12

**Comment by sam-github** [comment]
Its an optional dep, so install should continue. This will be fixed in our next release.

/cc @rmg
