### ISSUE TITLE
Failure: socket hang up  when  slc deploy

### ISSUE THREAD

**Issue by kylezengTR** [strongloop/strong-pm#316]
Guys,
I have encountered this failure: 

```
Deploy `.../api-1.0.0-65.tgz` to `http://<username>:<password>@<url>:8701/api/services/1/deploy` failed: socket hang up
```

and even if I running 
slc deploy or sl-deploy(the strongloop pm deploy module)  
like 

```
slc deploy http://<url>
```

still will pop out this failure occasionally.
Any ideas about how to fix this??

**Comment by ziwar** [comment]
getting the same error
have you found a solution?

**Comment by kylezengTR** [comment]
@ziwar   seems like is a network issus, when I used a linux server and type the command manually, everything works find, but right now I am trying to use jenkins job to do that, enter the parameter, jenkins will run the shell script for me. But some network problems let this error happens.

**Comment by sam-github** [comment]
Its a low level TCP error, not sure what to say other than check your network configuration/stability.

**Comment by JoeShi** [comment]
same issue. Same command on the same machine in different network environment, the error happens.

**Comment by daamsie** [comment]
I had the same issue. Found it deployed despite this error.

**Comment by matiasvarela** [comment]
I have the same issue. Any solution?

**Comment by lucasftp** [comment]
I have the same issue. My network works well.

**Comment by lucasftp** [comment]
I found a solution to my problem. This issue is generated when you use a .tgz file. If you use a git branch, this problem is solved.

You should use this: 
slc deploy http://<username>:<password>@<url>:8701 git_branch

instead of this
slc deploy http://<username>:<password>@<url>:8701 file.tgz

**Comment by CNSKnight** [comment]
I'm seeing this now with the below recent client update, where `slc deploy ... file.tgz` was working fine.
```
RecipesAPI-LB@1.0.0 /var/www/acapF/vegrds-7109/public_html/acap-dev/plugins/RecipesAPI-LB
├── cldr-data@29.0.2
├── cors@2.8.1 
├── loopback@2.34.1 
├── loopback-boot@2.22.0                                                                                                                                       
├── loopback-datasource-juggler@2.51.0                                                                                                                         
├── nsp@2.6.1                                                                                                                                                  
└── strong-error-handler@1.1.0        
```

**Comment by pdesgarets** [comment]
Experiencing this too, with deploy from travis. Any update ? 
I don't think travis (nor every server used by people who encountered this error) has systematically network errors... The deployment occurs, but the socket hang up make the travis build fail.

And I don't consider "use git" a solution. Or don't sell this tgz deployment as a feature.
