### ISSUE TITLE
Strong-pm use in IMB Bluemix container group

### ISSUE THREAD

**Issue by paulJordaan** [strongloop/strong-pm#318]
Is it possible to use strong-pm in container group on IBM bluemix service? I've tried a group based on the official strong-pm image but am only able to assign one port at group creation and I don't seem to able to access this port for deployment.

**Comment by sam-github** [comment]
@saivennam thoughts?

**Comment by rmg** [comment]
I think you meant @svennam92 ;-)

**Comment by paulJordaan** [comment]
Any update @svennam92?

**Comment by svennam92** [comment]
Thanks for the reminder! I still need to investigate this support, I'll get back to you here shortly.

**Comment by svennam92** [comment]
From the [documentation](https://console.ng.bluemix.net/docs/containers/container_creating_ov.html#container_group_ui):
For container groups, you cannot include multiple ports.

Unfortunately, it looks like the ibm-node-strong-pm container does not have full support for container groups.  You could always still use the StrongLoop Process Manager to run the application in container groups (by extending the image), but you will not be able to use Arc to deploy Node.js applications or monitor them.

Thanks for bringing this up, I'll ensure the documentation gets updated to reflect this limitation.  Until IBM Containers supports multiple ports for groups, ibm-node-strong-pm will not be fully supported for container groups.
