### ISSUE TITLE
Chinese user help message! 

### ISSUE THREAD

**Issue by gggin** [strongloop/strong-pm#320]
If you install strong-pm fail in sqlite3, maybe download codes fail(you need use sth like shadowsocks or vpn to cross GFW...

**Comment by mike442144** [comment]
I ran into the same problem,,,,,,,fuck GFW

**Comment by gggin** [comment]
even cnpm means nothing。。。shit.

**Comment by JoeShi** [comment]
I confirm!!!!  the shit GFW.

**Comment by didikeke** [comment]
Tested in a fresh 64bit ubuntu 14.04 Qingdao(青岛) server without SS and VPN. I have installed strong-pm successfully today. 

I see Sqlite3 was blocked before.  However, you can check it again now. if it is unblocked, please close the issue.

**Comment by JoeShi** [comment]
@didikeke  I tested today with CentOS 7.0 in Shanghai without VPN failed. But with VPN. I install successfully.

**Comment by sam-github** [comment]
I'm sorry, is there a bug here? If so, please reopen and clarify what you did, and what didn't work. If your firewall isn't working, but you think there is something we could do that would help, please say what it is. I am not an expert on China's firewalls.

**Comment by JoeShi** [comment]
@sam-github We don't known what happened when install strong-pm from npm. I guess, it is trying to pre download something. It that is the case, put them on a non-Google's server will help. Google's IPs are totally blocked here. :(

**Comment by sam-github** [comment]
We don't download anything from google during install, but maybe other locations are blocked. I don't know if I can help, but if you tell me what exactly is not working, I can see if we can work around it, if possible.
