### ISSUE TITLE
[SUGGEST] Support for launchctl?

### ISSUE THREAD

**Issue by daankets** [strongloop/strong-pm#322]
As a lot of developers are on Mac these days (set-aside the use of docker and vagrant), wouldn't it be nice to support **[launchctl](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/launchctl.1.html)** as a service manager for strong-pm? It could be rather straightforward to add it I think?

**Comment by sam-github** [comment]
I think so, too, just takes some time,,, perhaps you can take a shot at it? There are already the systemd and upstart examples, so the multi-svs manager path already exists.

**Comment by rmg** [comment]
It would be easy to add, but I'm curious what the value would be since the service installation is meant for production environments. If it was installed as a service on Mac, it would start up automatically, but if `slc start` was used to start your app then it likely wouldn't start your app when it starts up.

**Comment by louisl** [comment]
Just did this on our OSX Server. Rough steps are...

Decide what user will be running the process manager eg 'serveradmin'.

Make a directory.
```mkdir /var/lib/strong-pm```

```sudo chown serveradmin:wheel /var/lib/strong-pm```

Install node if not installed already, I used homebrew.
```brew install node```

Set perms
```npm install --unsafe-perm -g strong-pm --user serveradmin```

Create a launch daemon.
```sudo pico /Library/LaunchDaemons/com.strongloop.strong-pm.plist```
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>KeepAlive</key>
  <true/>
  <key>Label</key>
  <string>com.strongloop.strong-pm</string>
  <key>ProgramArguments</key>
  <array>
    <string>/usr/local/bin/node</string>
    <string>/usr/local/bin/sl-pm</string>
    <string>--base</string>
    <string>/var/lib/strong-pm</string>
  </array>
  <key>StandardOutPath</key>
  <string>/tmp/strong-pm-info.log</string>
  <key>StandardErrorPath</key>
  <string>/tmp/strong-pm-error.log</string>
  <key>RunAtLoad</key>
  <true/>
  <key>UserName</key>
  <string>serveradmin</string>
  <key>WorkingDirectory</key>
  <string>/var/lib/strong-pm</string>
</dict>
</plist>
```
Set perms
```sudo chmod 644 /Library/LaunchDaemons/com.strongloop.strong-pm.plist```

Load it.
```sudo launchctl load -w /Library/LaunchDaemons/com.strongloop.strong-pm.plist```
