### ISSUE TITLE
Fresh install fails with "Cannot find module /loopback-connector-sqlite3/node_modules/sqlite3/lib/binding/node-v46-linux-x64/node_sqlite3.node"

### ISSUE THREAD

**Issue by CMendy** [strongloop/strong-pm#323]
on AWS i set up new EC2 instance runing Ubuntu Server 14.04 LTS, i run:

**curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
sudo apt-get install -y nodejs
sudo apt-get install -y build-essential
sudo npm install -g strong-pm
sudo sl-pm-install
sudo /sbin/initctl start strong-pm
slpmctl**

slpmctl returns Command "status" on "http://127.0.0.1:8701" failed with Error: connect ECONNREFUSED 127.0.0.1:8701

so i check:
**sudo cat /var/log/upstart/strong-pm.log**

and i see this repeating for ever:
```
Error: Cannot find module '/usr/lib/node_modules/strong-pm/node_modules/loopback-connector-sqlite3/node_modules/sqlite3/lib/binding/node-v46-linux-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/lib/node_modules/strong-pm/node_modules/loopback-connector-sqlite3/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
module.js:327
    throw err;
    ^


```

looking at /usr/lib/node_modules/strong
**/usr/lib/node_modules/strong-pm/node_modules/loopback-connector-sqlite3/node_modules/sqlite3/lib**
./binding/node-v46-linux-x64/node_sqlite3.node is missing

what can i do to fix this right now ? I am setting up our first production server!!! hlep !

did i do something wrong ?

**Comment by CMendy** [comment]
I used the same step to set up my staging server a month ago and had no problems, looking at the files on that machine i see that strong-pm does not have the loopback-connector-sqlite3 module.

**Comment by rmg** [comment]
The switch to sqlite3 as the store is a recent change. Where there any errors or warnings when you did `sudo npm install -g strong-pm`?

**Comment by CMendy** [comment]
No errors at all :(
here is the log:
`sudo npm install -g strong-pm
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.

> utf-8-validate@1.2.1 install /usr/lib/node_modules/strong-pm/node_modules/strong-control-channel/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/home/ubuntu/.node-gyp/4.3.2"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/strong-pm/node_modules/strong-control-channel/node_modules/ws/node_modules/utf-8-validate/.node-gyp"
make: Entering directory `/usr/lib/node_modules/strong-pm/node_modules/strong-control-channel/node_modules/ws/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  COPY Release/validation.node
make: Leaving directory `/usr/lib/node_modules/strong-pm/node_modules/strong-control-channel/node_modules/ws/node_modules/utf-8-validate/build'

> bufferutil@1.2.1 install /usr/lib/node_modules/strong-pm/node_modules/strong-control-channel/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/home/ubuntu/.node-gyp/4.3.2"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/strong-pm/node_modules/strong-control-channel/node_modules/ws/node_modules/bufferutil/.node-gyp"
make: Entering directory `/usr/lib/node_modules/strong-pm/node_modules/strong-control-channel/node_modules/ws/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  COPY Release/bufferutil.node
make: Leaving directory `/usr/lib/node_modules/strong-pm/node_modules/strong-control-channel/node_modules/ws/node_modules/bufferutil/build'
\
> heapdump@0.3.7 install /usr/lib/node_modules/strong-pm/node_modules/strong-runner/node_modules/strong-supervisor/node_modules/heapdump
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/home/ubuntu/.node-gyp/4.3.2"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/strong-pm/node_modules/strong-runner/node_modules/strong-supervisor/node_modules/heapdump/.node-gyp"
make: Entering directory `/usr/lib/node_modules/strong-pm/node_modules/strong-runner/node_modules/strong-supervisor/node_modules/heapdump/build'
  CXX(target) Release/obj.target/addon/src/heapdump.o
  SOLINK_MODULE(target) Release/obj.target/addon.node
  COPY Release/addon.node
make: Leaving directory `/usr/lib/node_modules/strong-pm/node_modules/strong-runner/node_modules/strong-supervisor/node_modules/heapdump/build'

> modern-syslog@1.1.2 install /usr/lib/node_modules/strong-pm/node_modules/strong-runner/node_modules/strong-supervisor/node_modules/modern-syslog
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/home/ubuntu/.node-gyp/4.3.2"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/strong-pm/node_modules/strong-runner/node_modules/strong-supervisor/node_modules/modern-syslog/.node-gyp"
make: Entering directory `/usr/lib/node_modules/strong-pm/node_modules/strong-runner/node_modules/strong-supervisor/node_modules/modern-syslog/build'
  CXX(target) Release/obj.target/core/core.o
  SOLINK_MODULE(target) Release/obj.target/core.node
  COPY Release/core.node
make: Leaving directory `/usr/lib/node_modules/strong-pm/node_modules/strong-runner/node_modules/strong-supervisor/node_modules/modern-syslog/build'

> strong-agent@2.0.2 install /usr/lib/node_modules/strong-pm/node_modules/strong-runner/node_modules/strong-supervisor/node_modules/strong-agent
> node-gyp rebuild || exit 0

gyp WARN EACCES user "root" does not have permission to access the dev dir "/home/ubuntu/.node-gyp/4.3.2"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/strong-pm/node_modules/strong-runner/node_modules/strong-supervisor/node_modules/strong-agent/.node-gyp"
make: Entering directory `/usr/lib/node_modules/strong-pm/node_modules/strong-runner/node_modules/strong-supervisor/node_modules/strong-agent/build'
  CXX(target) Release/obj.target/strong-agent/src/strong-agent.o
  SOLINK_MODULE(target) Release/obj.target/strong-agent.node
  COPY Release/strong-agent.node
make: Leaving directory `/usr/lib/node_modules/strong-pm/node_modules/strong-runner/node_modules/strong-supervisor/node_modules/strong-agent/build'
npm WARN cannot run in wd sqlite3@3.1.1 node-pre-gyp install --fallback-to-build (wd=/usr/lib/node_modules/strong-pm/node_modules/loopback-connector-sqlite3/node_modules/sqlite3)

> strong-debugger@1.0.0 install /usr/lib/node_modules/strong-pm/node_modules/strong-runner/node_modules/strong-supervisor/node_modules/strong-debugger
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/home/ubuntu/.node-gyp/4.3.2"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/strong-pm/node_modules/strong-runner/node_modules/strong-supervisor/node_modules/strong-debugger/.node-gyp"
make: Entering directory `/usr/lib/node_modules/strong-pm/node_modules/strong-runner/node_modules/strong-supervisor/node_modules/strong-debugger/build'
  CXX(target) Release/obj.target/debugger/src/mutex-wrap.o
  CXX(target) Release/obj.target/debugger/src/debugger.o
  CXX(target) Release/obj.target/debugger/src/controller.o
  CXX(target) Release/obj.target/debugger/src/worker.o
  CXX(target) Release/obj.target/debugger/src/worker-bindings.o
  SOLINK_MODULE(target) Release/obj.target/debugger.node
  COPY Release/debugger.node
make: Leaving directory `/usr/lib/node_modules/strong-pm/node_modules/strong-runner/node_modules/strong-supervisor/node_modules/strong-debugger/build'

> sqlite3@3.1.1 install /usr/lib/node_modules/strong-pm/node_modules/minkelite/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

[sqlite3] Success: "/usr/lib/node_modules/strong-pm/node_modules/minkelite/node_modules/sqlite3/lib/binding/node-v46-linux-x64/node_sqlite3.node" is installed via remote
/usr/bin/sl-pm -> /usr/lib/node_modules/strong-pm/bin/sl-pm.js
/usr/bin/sl-pmctl -> /usr/lib/node_modules/strong-pm/bin/sl-pmctl.js
/usr/bin/slpm -> /usr/lib/node_modules/strong-pm/bin/sl-pm.js
/usr/bin/slpmctl -> /usr/lib/node_modules/strong-pm/bin/sl-pmctl.js
/usr/bin/sl-pm-install -> /usr/lib/node_modules/strong-pm/bin/sl-pm-install.js
strong-pm@5.2.0 /usr/lib/node_modules/strong-pm
├── strong-spawn-npm@1.0.0
├── userhome@1.0.0
├── posix-getopt@1.2.0
├── extsprintf@1.3.0
├── async@0.9.2
├── strong-url-defaults@1.2.1
├── serve-favicon@2.3.0 (fresh@0.3.0, etag@1.7.0, parseurl@1.3.1, ms@0.7.1)
├── debug@2.2.0 (ms@0.7.1)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── bl@0.9.5 (readable-stream@1.0.33)
├── concat-stream@1.5.1 (inherits@2.0.1, typedarray@0.0.6, readable-stream@2.0.5)
├── compression@1.6.1 (on-headers@1.0.1, bytes@2.2.0, vary@1.1.0, compressible@2.0.7, accepts@1.3.1)
├── errorhandler@1.4.3 (escape-html@1.0.3, accepts@1.3.1)
├── express@4.13.4 (escape-html@1.0.3, array-flatten@1.1.1, cookie-signature@1.0.6, utils-merge@1.0.0, vary@1.0.1, content-type@1.0.1, merge-descriptors@1.0.1, methods@1.1.2, etag@1.7.0, fresh@0.3.0, parseurl@1.3.1, cookie@0.1.5, content-disposition@0.5.1, path-to-regexp@0.1.7, serve-static@1.10.2, range-parser@1.0.3, depd@1.1.0, qs@4.0.0, on-finished@2.3.0, finalhandler@0.4.1, proxy-addr@1.0.10, accepts@1.2.13, send@0.13.1, type-is@1.6.12)
├── strong-service-install@2.0.1 (uid-number@0.0.5, chownr@0.0.2, async@1.5.2, minimist@1.2.0, shell-quote@1.4.3, strong-service-systemd@1.2.1, which@1.2.4, strong-service-upstart@1.1.1)
├── rimraf@2.5.2 (glob@7.0.0)
├── tar@1.0.3 (inherits@2.0.1, block-stream@0.0.8, fstream@1.0.8)
├── strong-fork-cicada@1.1.2 (inherits@1.0.2, shell-quote@0.0.1, mkdirp@0.3.5, strong-fork-pushover@1.3.9)
├── dockerode@2.2.9 (docker-modem@0.3.0)
├── strong-docker-build@1.1.0 (async@1.5.2, through@2.3.8, tar@2.2.1, fstream-npm@1.0.7)
├── strong-tunnel@1.1.4 (ssh2@0.4.13)
├── strong-npm-ls@1.0.7 (topiary@1.1.2, read-installed@3.1.5)
├── http-auth@2.2.8 (node-uuid@1.4.1, htpasswd@2.2.0)
├── strong-control-channel@2.2.0 (newline-json@0.1.1, ws@0.8.1)
├── lodash@3.10.1
├── loopback-connector-sqlite3@1.1.1 (loopback-connector@2.3.0, moment@2.11.2, sqlite3@3.1.1)
├── strong-mesh-models@8.1.0 (sprintf@0.1.5, user-home@1.1.1, text-table@0.2.0, loopback-boot@2.17.0, request@2.69.0, loopback-datasource-juggler@2.45.2, loopback-explorer@1.8.0, loopback@2.27.0)
├── strong-runner@5.0.1 (strong-supervisor@3.3.1)
└── minkelite@1.2.5 (xtend@4.0.1, stats-lite@1.0.3, ago@1.0.0, md5@2.0.0, util@0.10.3, body-parser@1.9.3, express@4.9.8, sqlite3@3.1.1)`

**Comment by Astor** [comment]
sudo npm install --unsafe-perm --verbose -g strong-pm , this is a permissions issue.

**Comment by CMendy** [comment]
So this worked for me today on new EC2 instance:

**sudo apt-get update
sudo apt-get install build-essential sqlite git
curl -sL https://deb.nodesource.com/setup_4.x | sudo bash -
sudo apt-get install -y nodejs
sudo npm install -g strong-pm --unsafe-perm
sudo sl-pm-install
sudo /sbin/initctl start strong-pm**

**slpmctl**
reports : No services exist

**sudo cat /var/log/upstart/strong-pm.log**
reports: 
sl-pm.js(9668): StrongLoop PM v5.2.0 (API v6.1.0) on port `8701`
sl-pm.js(9668): Base folder `/var/lib/strong-pm`
sl-pm.js(9668): Applications on port `3000 + service ID`

everything is normal.

**Comment by didikeke** [comment]
I have the same problem on a new Ubuntu Server 14.04 LTS 64bit server by the root user today, when I install it by "npm install -g strong-pm".

So I created a new instance and used 

`npm install **--unsafe-perm** -g strong-pm`

then everything is going well. 

@rmg I think this issue should be open again, because it is not the same flow as the document now. https://docs.strongloop.com/display/SLC/Setting+up+a+production+host#Settingupaproductionhost-Ubuntu

**Comment by rmg** [comment]
@crandmck would you mind updating the docs to include the `--unsafe-perm` flag as a possible solution to some installation problems?

**Comment by crandmck** [comment]
Added a note to https://docs.strongloop.com/display/SLC/Setting+up+a+production+host#Settingupaproductionhost-Installnpmpackage.  There's already a similar note in https://docs.strongloop.com/display/SL/Installation+troubleshooting#Installationtroubleshooting-Makesureyouhavesufficientfileprivileges for installing `strongloop`.

If that looks sufficient, please close the issue.
