### ISSUE TITLE
Collect StrongPM metrics using any script

### ISSUE THREAD

**Issue by priyavivek1** [strongloop/strong-pm#325]
Do we have any way to collect strong-pm metrics using any script. Currently, i understand all ways listed at below https://docs.strongloop.com/display/SLC/Monitoring+with+slc" and i am able to push metrics to influx db or Graphite using this.

But on Prod systems, we need to open ports for Databases like influx from each VM, which is not a approved process at our end. 

Is there anyway to use any script and get the metrics

@sam-github @piscisaureus

**Comment by sam-github** [comment]
I've no idea what you mean by any script. 

If you want to send them off-system, you need open ports.

You can write them to file if you don't want to open up ports, and then do whatever you want.

also, you can run etsy/statsd or something like that on the system, and write a backend to do whatever you want. Or just implement the statsd UDP protocol yourself, its very simple
