### ISSUE TITLE
no current application

### ISSUE THREAD

**Issue by hongyin163** [strongloop/strong-pm#339]
when I deploy service and start it,return meesag like this

d:\Workfolder\express>slc ctl -C  http://10.0.1.51:8701/ start express
Service: "express"
    Instance  Response
        3     **no current application**
**Command "start" on "http://10.0.1.51:8701/" failed with error**

**Comment by bistmaster** [comment]
@hongyin163 did it deployed successfully? I think you can start without "slc ctl -C http://10.0.1.51:8701 start express". You can also check the status of the app by "slc ctl -C http://10.0.1.51:8701 start status"
