### ISSUE TITLE
Failed to start strong-pm

### ISSUE THREAD

**Issue by Arn-hm** [strongloop/strong-pm#340]
Hello everyone,

I am using Loopback to create a RESTful API, which is very usefull ! But I have some problems when I want to deploy it on a Debian server. I am following the official guide to setting up a production host.
https://docs.strongloop.com/display/SLC/Setting+up+a+production+host

[Environment]
Debian
node v4.4.3

When I start strong-pm using 
`systemctl start strong-pm`
and then check the service status with "systemctl status strong-pm" I receive these messages :

first : 

```
 strong-pm.service - StrongLoop Process Manager
   Loaded: loaded (/etc/systemd/system/strong-pm.service; enabled)
   Active: active (running) since ven. 2016-04-29 11:49:08 CEST; 1s ago
 Main PID: 7314 (nodejs)
   CGroup: /system.slice/strong-pm.service
           └─7314 /usr/bin/nodejs /usr/lib/node_modules/strong-pm/bin/sl-pm.js --listen 8701 --base /var/lib/strong-p...
```

and then when I check it again :

```
● strong-pm.service - StrongLoop Process Manager
   Loaded: loaded (/etc/systemd/system/strong-pm.service; enabled)
   Active: failed (Result: start-limit) since ven. 2016-04-29 11:49:12 CEST; 1s ago
  Process: 7325 ExecStart=/usr/bin/nodejs /usr/lib/node_modules/strong-pm/bin/sl-pm.js --listen 8701 --base /var/lib/strong-pm --base-port 3000 --driver direct (code=exited, status=1/FAILURE)
 Main PID: 7325 (code=exited, status=1/FAILURE)

avril 29 11:49:12 xxxx systemd[1]: Unit strong-pm.service entered failed state.
avril 29 11:49:12 xxxx systemd[1]: strong-pm.service start request repeated too quickly, refusing to start.
avril 29 11:49:12 xxxx systemd[1]: Failed to start StrongLoop Process Manager.
avril 29 11:49:12 xxxx systemd[1]: Unit strong-pm.service entered failed state.
```

When I try with this : 

`/usr/bin/nodejs /usr/lib/node_modules/strong-pm/bin/sl-pm.js --listen 8701 --base /var/lib/strong-pm --base-port 3000 --driver direct`

This is what happened : 

```
module.js:327
    throw err;
    ^

Error: Cannot find module '/usr/lib/node_modules/strong-pm/node_modules/sqlite3/lib/binding/node-v46-linux-x64/node_sqlite3.node'
```

So I look inside the folders and in the "lib" there is only 3 files but no clue of '/binding/node'...

I don't understand what happened, maybe you could help me.

Thanks a lot !

**Comment by nicodmf** [comment]
Hello, I have the same problem and my configuration is more or less identical (debian jessie and node 4.4.3).

When i launch the service command : 

```
/usr/bin/nodejs /usr/lib/node_modules/strong-pm/bin/sl-pm.js\
 --listen 8701 --base /var/lib/strong-pm --base-port 3000 --driver direct
```

the result is

```
Error: Cannot find module 
'/usr/lib/node_modules/strong-pm/node_modules/sqlite3/lib/binding/node-v46-linux-x64/node_sqlite3.node'
```

It seems to me this should be easy to resolve, but if i was a node specialist anybody has an idea on this problem ?

Best Regards

**Comment by nicodmf** [comment]
Maybe the solution is here : #342, i will try tomorrow and say if it work

**Comment by nicodmf** [comment]
maybe related to  #337
