### ISSUE TITLE
Strong-pm 5.2.1 / Ubuntu 14.04 loopback-connector-sqlite3 dependancy issue

### ISSUE THREAD

**Issue by pessato** [strongloop/strong-pm#342]
Installed latest strong-pm, 5.2.1, on a fresh Ubuntu 14.04 server.

After starting the service getting the following error in the logs repetitively and strong-pm not firing:

`loopback-connector-sqlite3 must be installed to use the sql backend. Use the --json-file-db option if you are unable to install loopback-connector-sqlite3.`

Temp solution was to uninstall strong-pm as per Strongloop documentation:

```
$ sudo /sbin/initctl stop strong-pm
$ sudo rm /etc/init/strong-pm.conf
$ sudo /sbin/initctl reload-configuration
$ sudo rm -rf /var/lib/strong-pm
```

And then reinstall using strong-pm version 5.1.0:

`sudo npm install -g strong-pm@5.1.0`

I think the latest version has tried to address this however there still seems to be an issue or am I missing something? Thanks

**Comment by kashifeqbal** [comment]
I had the same issue,  I uninstall the strong-pm from server using comand
`sudo npm uninstall -g strong-pm`

After that follow Uninstall instruction of strong-pm as per Strongloop documentation:
`$ sudo /sbin/initctl stop strong-pm`
`$ sudo rm /etc/init/strong-pm.conf`
`$ sudo /sbin/initctl reload-configuration`
`$ sudo rm -rf /var/lib/strong-pm`

Then Re-install strong-pm on server.

Above procedure solve this issue for me.

**Comment by Alexx1992** [comment]
Be sure you have build-essential, and then install strong-pm.

**Comment by haipham23** [comment]
Just want to confirm that today I run into the exact error like @pessato described, with the same error message.

At first I used strong-pm@5.2.3 (latest). What I did is to follow what he suggested above (using strong-pm@5.1.0), and it works.

My spec:
Ubuntu@14.04
Node@4.4.7
npm@3.10.5

**Comment by nqd** [comment]
I also want to confirm same error.

```
strongloop v6.0.1 (node v4.4.6)
├── strong-arc@1.8.8
├── strong-build@2.1.2 (a98f310)
├── strong-deploy@3.1.4 (9b29df0)
├── strong-mesh-models@8.1.0 (62e539b)
├── strong-pm@5.2.3
├── strong-registry@1.1.6 (f8c2339)
├── strong-start@1.3.4 (28c261d)
├─┬ strong-supervisor@3.3.3
│ └── strong-agent@2.0.4 (de9885e)
├── generator-loopback@1.23.0 (db2f1a4)
├── node-inspector@0.7.4
└── nodefly-register@0.3.3
```

Has pure install on ubuntu 14.04, npm 2.15.5

**Comment by didikeke** [comment]
Oct 25, 2016

Failed:
ubuntu 14.04
node 6.9.1 
strong-pm 5.2.3 or strong-pm 5.1.0 

Success:
ubuntu 14.04
node 4.6.1 
strong-pm 5.2.3 or strong-pm 5.1.0 

Success:
ubuntu 16.04
node 6.9.1 
strong-pm 5.2.3

**Comment by fenixping** [comment]
After investigate installation log, I found issue from here `npm WARN cannot run in wd sqlite3@3.1.7 node-pre-gyp install --fallback-to-build (wd=/usr/lib/node_modules/strong-pm/node_modules/loopback-connector-sqlite3/node_modules/sqlite3)`

Please use argument --unsafe-perm. For example: `npm install -g --unsafe-perm strong-pm`.
