### ISSUE TITLE
slc deploy to remote server

### ISSUE THREAD

**Issue by hoangtrongphuc** [strongloop/strong-pm#343]
When i run
`slc deploy http://example.com:8701`
Result error : RPC failed; result=55; HTTP code = 0
                      The remote end hang up unexpectedly

**Comment by nicodmf** [comment]
Be you sure on your deploy server ? It seem that your server doesn't respond and if you don't have change the hosts file to have a real example.com, this can't work. (use localhost maybe)...

**Comment by hoangtrongphuc** [comment]
Yes, Server Address is correct, I use IP address and I only show example for you.
I build project with 
`slc build --commit` 
This command build project and commit to deploy branch, after i deploy with
`slc deploy http://myhostaddress:8701`
Maybe deploy with node_modules folder so large, or I missing something
