### ISSUE TITLE
slc deploy always giving RPC failed; result=55, HTTP code = 0

### ISSUE THREAD

**Issue by idlescan** [strongloop/strong-pm#347]
Hi everyone, I'm getting this error trying to deploy to a remote box. The box has SLC PM installed as a service and I've verified that it's running.

Can anyone give some direction on this?

**slc deploy -s testdeploy http://mybox
Counting objects: 6707, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (4945/4945), done.
Writing objects: 100% (6707/6707), 10.28 MiB | 0 bytes/s, done.
Total 6707 (delta 1297), reused 6702 (delta 1295)
error: RPC failed; result=55, HTTP code = 0
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
Everything up-to-date
Failed to deploy 'deploy' as 'testdeploy' to 'http://mybox:8701/' via 'http://mybox:8701/'**

I've tried increasing git buffer size, this has no effect.
`git config http.postBuffer 524288000`

I've successfully deployed to PM on my local machine, but cannot get this to deploy to the remote environment.

I've also run it with the following parameters, output below:

`GIT_CURL_VERBOSE=1 GIT_TRACE=1 slc deploy -s testdeploy http://mybox`

POST /api/services/2/deploy/default/git-receive-pack HTTP/1.1
Host: mybox:8701
User-Agent: git/2.3.2 (Apple Git-55)
Accept-Encoding: gzip
Content-Type: application/x-git-receive-pack-request
Accept: application/x-git-receive-pack-result
Content-Length: 10780126

 Recv failure: Connection reset by peer
 Closing connection 1
error: RPC failed; result=56, HTTP code = 0
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
Everything up-to-date
Failed to deploy 'deploy' as 'testdeploy' to 'http://mybox:8701/' via 'http://mybox:8701/'

Thanks!

**Comment by sam-github** [comment]
@rmg have you seen this? @idlescan I wonder if using ssh tunneling would allow you basically "be" local on the remote system and bypass this?

see https://github.com/strongloop/strong-deploy/blob/master/bin/sl-deploy.txt#L28-L36

**Comment by rmg** [comment]
@idlescan what version of node and strong-pm are running on the remove system you are trying to deploy to?

**Comment by idlescan** [comment]
@rmg 

**slc -v**
strongloop v6.0.1 (node v4.2.6)
├── strong-arc@1.8.8 (fb756f2)
├── strong-build@2.1.2 (a98f310)
├── strong-deploy@3.1.4 (9b29df0)
├── strong-mesh-models@8.1.0 (62e539b)
├── strong-pm@5.2.1 (6ab604c)
├── strong-registry@1.1.6 (f8c2339)
├── strong-start@1.3.4 (28c261d)
├─┬ strong-supervisor@3.3.3
│ └── strong-agent@2.0.3 (ec2d95b)
├── generator-loopback@1.20.6 (c53788b)
├── node-inspector@0.7.4
└── nodefly-register@0.3.3

**node -v**
v4.2.6

It's running on latest Ubuntu on DigitalOcean. I previously had a bunch of issues getting strongloop installed, had to do --unsafe-perms on any npm installation.

@sam-github 
I can successfully deploy to the host if I do it *from* the host itself - check out the repo onto the box, and do slc deploy from there.
I've tried the http+ssh://REMOTEHOST deployment with environment variables set, but get the following:
ssh connection error:  { [Error: All configured authentication methods failed] level: 'client-authentication' }

**Comment by idlescan** [comment]
Hi everyone,

Any advice on how to approach this issue?

I'm currently SSH-ing onto the remote server, checking out the repository and deploying locally, due to the above issue.

Is that a safe way to deploy my application in a production environment? Any downsides to this?

Thanks!

**Comment by idlescan** [comment]
@rmg 
Sorry to keep on about this one but can you confirm if deploying locally on a production server is safe/secure for production and if there are any potential issues I need to consider while the above issue is open?

**Comment by bachirelkhoury** [comment]
related to #335 checkout my solution.

**Comment by rmg** [comment]
@idlescan that should be fine.

**Comment by idlescan** [comment]
@bachirelkhoury Thanks - I saw your issue previously but there doesn't actually seem to be many large files that I can delete. It's a 10MB deploy, which doesn't seem so big that it should cause an issue like this.

@rmg thanks, I'll do local deploys on the production server for now

**Comment by bachirelkhoury** [comment]
@idlescan this seem to be happening again. #335 turned out to be a random success. How are you deploying locally on production? using sl-pm? any help would be really appreciated.

**Comment by idlescan** [comment]
@bachirelkhoury yeah, I've got strong-pm service running on the production machine and I'm running slc build --npm followed by slc deploy on that machine - It's been working fine for the last while (though I haven't updated strongloop etc recently)
