### ISSUE TITLE
Different config files for strong-pm

### ISSUE THREAD

**Issue by yagobski** [strongloop/strong-pm#348]
Anyone can help me to get a different configs files for strong-pm (prod). how can i tell to strong-pm run my app using this config.json and datasources.json config files?

I read this documentation but i don't see how can i make it work with strong-pm
https://docs.strongloop.com/display/public/LB/Environment-specific+configuration

**Comment by lukewendling** [comment]
On a similar note, how do we use strong-pm in a similar fashion as pm2, where you specify the commands for pm2 to control? I need strong-pm to also start and control a worker process, not just a web process. The worker is a node.js script that lives in the save project as the web app.
