### ISSUE TITLE
Recover from slc deploy failure

### ISSUE THREAD

**Issue by boxfish** [strongloop/strong-pm#355]
I had an app deployed to strong-pm. Due to an error in the code, it kept throwing exception and strong-pm kept attempting to restart it and took almost 100% cpu. Further calling to slc deploy always failed with Error: connect ECONNREFUSED 127.0.0.1:8701. Even thought I have a fix to the app, I cannot deploy this new version due to slc is not responding to deploy requests anymore. What is the best strategy to escape from such situation?

**Comment by dmastag** [comment]
Guess you could 
```slc ctl remove SVC```

and then deploy again
