### ISSUE TITLE
ECONNREFUSED 127.0.0.1:8701 Ubuntu 16.04 Fresh Install

### ISSUE THREAD

**Issue by reggie3** [strongloop/strong-pm#357]
I'm attempting to start a keystone.js application using the command "slc start" in the same directory my keystone.js file is located.  My package.json has "keystone.js" as its main.  The startup fails with the following error: "Error: pm failed, exit with status 1"  I logged the startup using "DEBUG=\* slc start >debug.log 2>&1" and got the following:

melvin@Keystonejs-Porfolio-Project:~/Keystone_Portfolio_and_Project_Site/portfolio$ more debug.log
Tue, 21 Jun 2016 18:55:18 GMT slc slc.run: argv [ 'start' ] options { _: [ 'start' ], '$0': '/home/melvin/.npm-global/bi
n/slc' }
Tue, 21 Jun 2016 18:55:18 GMT slc loadCommand name start run? function usage? object
Tue, 21 Jun 2016 18:55:19 GMT strong-start:start app is "."
Tue, 21 Jun 2016 18:55:19 GMT strong-start:pm start
Tue, 21 Jun 2016 18:55:19 GMT strong-start:pm isAlive...
Tue, 21 Jun 2016 18:55:19 GMT strong-start:pm alive? Error: connect ECONNREFUSED 127.0.0.1:8701
Tue, 21 Jun 2016 18:55:19 GMT strong-start:pm pm is missing: Error: connect ECONNREFUSED 127.0.0.1:8701
Tue, 21 Jun 2016 18:55:19 GMT strong-start:pm spawn: /usr/bin/nodejs args ["/home/melvin/.npm-global/lib/node_modules/st
rongloop/node_modules/strong-pm/bin/sl-pm.js","--base","/home/melvin/.strong-pm"] options {"detached":true,"stdio":["ign
ore",10,10]}
Tue, 21 Jun 2016 18:55:19 GMT strong-start:pm wait for pm to be alive
Tue, 21 Jun 2016 18:55:19 GMT strong-start:pm isAlive...
Tue, 21 Jun 2016 18:55:19 GMT strong-start:pm alive? Error: connect ECONNREFUSED 127.0.0.1:8701
Tue, 21 Jun 2016 18:55:19 GMT strong-start:pm isAlive...
Tue, 21 Jun 2016 18:55:19 GMT strong-start:pm alive? Error: connect ECONNREFUSED 127.0.0.1:8701
Tue, 21 Jun 2016 18:55:20 GMT strong-start:pm isAlive...
Tue, 21 Jun 2016 18:55:20 GMT strong-start:pm alive? Error: connect ECONNREFUSED 127.0.0.1:8701
Error: pm failed, exit with status  1

I installed slc as root using "npm install -g strongloop".  I think did a "slc pm-install" as root after encountering the error the first time, but the error persisted.
The keystone.js application is not under the root user.
Node version is 6.2.1

**Comment by rakesh-roshan** [comment]
Could you solve this issue? I am facing same.
