### ISSUE TITLE
Failed to deploy , no current application

### ISSUE THREAD

**Issue by Mengkzhaoyun** [strongloop/strong-pm#365]
When I Build & Deploy my app to remote server (Centos 7.0)
My app can not run in strong-pm.

Here is the log

c:\Temps\mybpp>slc deploy http://192.168.26.128
Deployed `..\mybpp-1.0.4.tgz` as `mybpp` to `http://192.168.26.128:8701/`

c:\Temps\mybpp>slc ctl -C http://192.168.26.128 status
Service ID: 1
Service Name: mybpp
Environment variables:
  No environment variables defined
Instances:
    Version  Agent version  Debugger version  Cluster size  Driver metadata
Not started

c:\Temps\mybpp>slc ctl -C http://192.168.26.128 start mybpp
Service: "mybpp"
    Instance  Response
        1     no current application
Command "start" on "http://192.168.26.128" failed with error

c:\Temps\mybpp>slc ctl -C http://192.168.26.128:8701 start mybpp
Service: "mybpp"
    Instance  Response
        1     no current application
Command "start" on "http://192.168.26.128:8701" failed with error

**Comment by yangguoyk2015** [comment]
I face with same issue, even, i tried slc ctl soft-restart myapp, same error saying "no current application"; I have to run local npm run build, then slc start, which will start the app; But after that, the slc build, slc deploy can deploy the latest source code into .../.strong-pm/svc/1/work folder, but there is no current folder, which seem to me that the slc deploy is not working.  
@rmg can you give any  idea on this? i was blocked by this for several days. If you have any suggestion that start a app from scratch, will be great!

**Comment by rmg** [comment]
@yangguoyk2015 when you do `slc start` it runs the app in place - it does not do a real deployment. It should only be used for local development.

**Comment by rmg** [comment]
@Mengkzhaoyun have you tried `slc ctl -C http://192.168.26.128:8701 log-dump mybpp` to see if it provides any information? If the app is failing too early in the startup process you may have to look at the strong-pm logs on the server itself.

**Comment by yangguoyk2015** [comment]
@rmg , thanks for your quick response. You are correct. Finally, i got my issue resolved.  The root cause is due to at the beginning, i am using the "slc start" way to run my project, which run the project just in the project root folder, its never do real deployment. Following is my steps to fix it:
  1. "slc ctl stop app" and "slc ctl remove app"  the app service, better to remove the /var/lib/strong-pm/svc subfolder
  2. make sure you are running the strong-pm service, not the strongloop pm (not use slc pm)
  3. use slc build and then slc deploy, never use slc start command, now i can see the

**Comment by htmlauthor** [comment]
I was having same issue with "no current application". In my case it was failure of one of private npm packages which was not available on npm.org
On server running strong-pm I did found npm-debug.log file (/var/lib/strong-pm/svc/1/work) witch was indicating problem.

Just sharing in case someone else will have same problems.

**Comment by yagobski** [comment]
I have same issue "No application running, no log to dump"
Application deployed but no current folder in /var/lib/strong-pm/svc/1

Please help!

**Comment by rmg** [comment]
@htmlauthor @yagobski did you use `slc start` to start the app?

**Comment by htmlauthor** [comment]
@rmg nope, when I deploy my app to strong-pm it starts automatically.
