### ISSUE TITLE
var resolved = ifExists(cwd, parts[3]) || requireable(cwd, parts[3]);

### ISSUE THREAD

**Issue by hypwxm** [strongloop/strong-pm#366]
there is something wrong with the parts, the module in strong-supervisor/lib/start-command, when i try **slc start** and **slc pm**,it always return the  **Cannot read property '3' of null**

```
Unexpected exit with 1 from Runner: commit 1/default
Start Runner: commit 1/default
/usr/lib/node_modules/strongloop/node_modules/strong-supervisor/lib/start-command.js:159
  var resolved = ifExists(cwd, parts[3]) || requireable(cwd, parts[3]);
                                    ^

TypeError: Cannot read property '3' of null
    at fromStart (/usr/lib/node_modules/strongloop/node_modules/strong-supervisor/lib/start-command.js:159:37)
    at resolvePackageStart (/usr/lib/node_modules/strongloop/node_modules/strong-supervisor/lib/start-command.js:148:10)
    at resolveArgs (/usr/lib/node_modules/strongloop/node_modules/strong-supervisor/lib/start-command.js:45:20)
    at Object.<anonymous> (/usr/lib/node_modules/strongloop/node_modules/strong-supervisor/lib/config.js:97:11)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
Unexpected exit with 1 from Runner: commit 1/default
```

**Comment by hypwxm** [comment]
my platform is ubuntu 16.04;

**Comment by hypwxm** [comment]
```
strongloop v6.0.1 (node v5.12.0)
├── strong-arc@1.8.8 (fb756f2)
├── strong-build@2.1.2 (a98f310)
├── strong-deploy@3.1.4 (9b29df0)
├── strong-mesh-models@8.1.0 (62e539b)
├── strong-pm@5.2.3
├── strong-registry@1.1.6 (f8c2339)
├── strong-start@1.3.4 (28c261d)
├─┬ strong-supervisor@3.3.3
│ └── strong-agent@2.0.4 (de9885e)
├── generator-loopback@1.23.2 (ebe6d41)
├── node-inspector@0.7.4
└── nodefly-register@0.3.3
```

**Comment by hypwxm** [comment]
There is a problem ,after i do ```sudo npm install -g --unsafe-perm install strongloop```,and restart my ubuntu,  I can not enter the system anymore,it always staying loading page,but i can control it buy Through a remote system with ssh root@host.

**Comment by rmg** [comment]
@hypwxm The error is coming from the code that tries to figure out how to start your app.

What is in your `package.json` for `main` or `scripts.start`? How are you trying to run it?

**Comment by hypwxm** [comment]
···
{
  "name": "xxx",
  "version": "0.0.0",
  "private": true,
  "mian": "app.js",
  "scripts": {
    "start": "bin/www",
    "pretest": "jshint .",
    "preinstall": "node .sl-blip.js || exit 0"
  },
  "dependencies": {
    "body-parser": "~1.13.2",
    "connect-flash": "^0.1.1",
    "connect-mongo": "^1.3.2",
    "cookie-parser": "~1.3.5",
    "debug": "~2.2.0",
    "ejs": "~2.3.3",
    "express": "^5.0.0-alpha.2",
    "express-mysql-session": "^1.1.1",
    "helmet": "^2.1.2",
    "jquery-file-upload-middleware": "^0.1.7",
    "mongoose": "^4.5.8",
    "morgan": "~1.6.1",
    "muler": "~1.1.0",
    "multer": "^1.1.0",
    "serve-favicon": "~2.3.0"
  }
}
···

this is my package.json, I did ```slc pm -l 3000``` start a process manage,and do ```slc build``` ,then ```slc deploy --server=name http://localhost:3000``` ,and opened a new ternimal window In my project directory ,then I did ```slc start``` in the new ternimal window, both of terminal windows are return the same log just as my question.  my english is not very good. I  tried to see strongloop documentation a few days ago,.

**Comment by rmg** [comment]
@hypwxm does your app work if you try running it with `npm start` instead?

**Comment by hypwxm** [comment]
@rmg yes, it also can be work when i tried ```slc run bin/www```,but it would break when something wrong happened immediatly.

**Comment by rmg** [comment]
Is `bin/www` a node script? If so, can you try changing the `start` script in `package.json` to `node bin/www` instead?

```json
{
  ...
  "scripts": {
    "start": "node bin/www",
    ...
  },
  ...
}
```

**Comment by hypwxm** [comment]
@rmg I used express to build my application, now I am resinstalling my ubuntu16.04 system, and i will try it.something wrong happened and i cannot into my system.

**Comment by hypwxm** [comment]
if  i need to change my ubuntu system to 15 or 14?i reinstalling my system, i do not kown what i do was true,  i used
 ```$ sudo sl-pm-install``` 
 ```$ sudo /sbin/initctl start strong-pm```,
and my system version is 16.

**Comment by hypwxm** [comment]
or centos is the better choose?

**Comment by rmg** [comment]
Any relatively recent Ubuntu or CentOS would be fine.
