### ISSUE TITLE
Cannot build under Alpine Linux (musl libc)

### ISSUE THREAD

**Issue by johanforssell** [strongloop/strong-pm#367]
I cannot run `npm install -g strong-pm` on an Alpine Linux box (https://alpinelinux.org/posts/Alpine-3.4.0-released.html), getting this error:

```
make: Entering directory '/home/vk/.npm-packages/lib/node_modules/strong-pm/node_modules/strong-agent/build'
  CXX(target) Release/obj.target/strong-agent/src/strong-agent.o
In file included from ../src/strong-agent.cc:15:0:
../src/watchdog.h: In function 'const char* strongloop::agent::watchdog::StartCpuProfiling(v8::Isolate*, uint64_t)':
../src/watchdog.h:242:6: error: 'struct sigevent' has no member named '_sigev_un'
   ev._sigev_un._tid = profiler_tid;
      ^
../src/watchdog.h:243:21: error: 'SIGEV_THREAD_ID' was not declared in this scope
   ev.sigev_notify = SIGEV_THREAD_ID;
                     ^
strong-agent.target.mk:98: recipe for target 'Release/obj.target/strong-agent/src/strong-agent.o' failed
```

Anyone with some more info on this problem?

**Comment by KostyaEsmukov** [comment]
Works for me on Alpine 3.5

    apk add --no-cache nodejs make g++ build-base musl-dev linux-headers
    npm install -g strongloop
    slc -v
    strongloop v6.0.3 (node v6.9.2)
    ├── strong-arc@1.8.9 (3dd25ac)
    ├── strong-build@2.1.2 (a98f310)
    ├── strong-deploy@3.1.4 (9b29df0)
    ├── strong-mesh-models@8.1.0 (62e539b)
    ├── strong-pm@5.2.4
    ├── strong-registry@1.1.6 (f8c2339)
    ├── strong-start@1.3.4 (28c261d)
    ├─┬ strong-supervisor@3.3.3
    │ └── strong-agent@2.1.2 (4b9dde0)
    ├── generator-loopback@1.25.0 (6a0e2c0)
    ├── node-inspector@0.7.5 (16841d6)
    └── nodefly-register@0.3.3
