### ISSUE TITLE
Is project discontinued?

### ISSUE THREAD

**Issue by lkrnac** [strongloop/strong-pm#373]
Development on this project seem to be stagnating. What is the recommended way to host Loopback application nowadays?

**Comment by sam-github** [comment]
Its not getting a lot of focus, but its working fine, we would still recommend it.

**Comment by oncletom** [comment]
@sam-github considering the folllowing notice stated on the [Strongloop _Setting up monitoring_ documentation page](https://docs.strongloop.com/display/SLC/Setting+up+monitoring):

> StrongLoop Arc and slc are no longer under active development, and will soon be deprecated.

Would you still recommend to use `slc`? It seems to be te mandatory way to use `strong-pm`.

**Comment by sam-github** [comment]
I would not recommend using `slc`. It is not the mandatory way to use stong-pm, btw, stong-pm can be installed and used directly.

That said, I would recommend using strong-supervisor over strong-pm, its smaller, simpler in function, and more actively maintained: https://www.npmjs.com/package/strong-supervisor
