### ISSUE TITLE
Install error on Windows python.EXE

### ISSUE THREAD

**Issue by batusy** [strongloop/strong-pm#375]
I am using Windows and show  
> npm install -g strongloop

> heapdump@0.3.7 install C:\Users\user1\AppData\Roaming\npm\node_modules\strongloop\node_modules\heapdump
> node-gyp rebuild

C:\Users\user1\AppData\Roaming\npm\node_modules\strongloop\node_modules\heapdump>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Python executable "C:\Python34\python.EXE" is v3.4.3, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:406:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:395:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:193:7)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:852:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:323:11)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at Socket.emit (events.js:188:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:492:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\user1\AppData\Roaming\npm\node_modules\strongloop\node_modules\heapdump
gyp ERR! node -v v6.3.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm WARN install:heapdump@0.3.7 heapdump@0.3.7 install: `node-gyp rebuild`
npm WARN install:heapdump@0.3.7 Exit status 1

> bufferutil@1.2.1 install C:\Users\user1\AppData\Roaming\npm\node_modules\strongloop\node_modules\bufferutil
> node-gyp rebuild

C:\Users\user1\AppData\Roaming\npm\node_modules\strongloop\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Python executable "C:\Python34\python.EXE" is v3.4.3, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:406:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:395:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:193:7)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:852:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:323:11)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at Socket.emit (events.js:188:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:492:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\user1\AppData\Roaming\npm\node_modules\strongloop\node_modules\bufferutil
gyp ERR! node -v v6.3.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm WARN install:bufferutil@1.2.1 bufferutil@1.2.1 install: `node-gyp rebuild`
npm WARN install:bufferutil@1.2.1 Exit status 1

> strong-agent@2.1.0 install C:\Users\user1\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-agent
> node-gyp rebuild || exit 0

C:\Users\user1\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-agent>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Python executable "C:\Python34\python.EXE" is v3.4.3, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:406:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:395:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:193:7)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:852:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:323:11)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at Socket.emit (events.js:188:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:492:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\user1\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-agent
gyp ERR! node -v v6.3.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok

can anybody help me?

Thank you

**Comment by loay** [comment]
Hi @batusy 
Please uninstall python and install python 2.7.x
Thanks.

**Comment by batusy** [comment]
Loay , it`s ok, but i'm reading nodejs/node-gyp requirements..  and says: 

https://github.com/nodejs/node-gyp

On Windows:

Option 1: Install all the required tools and configurations using Microsoft's windows-build-tools using **npm install --global --production windows-build-tools** from an elevated PowerShell or CMD.exe (run as Administrator).

> npm install --global --production windows-build-tools  on mi command line and: 

C:\Users\user1>npm install --global --production windows-build-tools

> windows-build-tools@0.6.0 postinstall C:\Users\user1\AppData\Roaming\npm\node_modules\windows-build-tools
> node ./lib/index.js

Downloading BuildTools_Full.exe
Downloading python-2.7.11.msi
[>                                            ] 0.0% (0 B/s)
Downloaded python-2.7.11.msi. Saved to C:\Users\user1\.windows-build-tools\python-2.7.11.msi.
Starting installation...
Launched installers, now waiting for them to finish.
This will likely take some time - please be patient!
Waiting for installers... |**Successfully installed Python 2.7**
Waiting for installers... \Successfully installed Visual Studio Build Tools.

----------------------------------------------------------------------------------------

Later ...

> npm install -g strongloop  and show compilation errors:

C:\Users\user1\AppData\Roaming\npm\slc -> C:\Users\user1\AppData\Roaming\npm\node_modules\strongloop\bin\slc.js
C:\Users\user1\AppData\Roaming\npm\lb-ng -> C:\Users\user1\AppData\Roaming\npm\node_modules\strongloop\node_modules\loopback-sdk-angular-cli\bin\lb-ng.js

> heapdump@0.3.7 install C:\Users\user1\AppData\Roaming\npm\node_modules\strongloop\node_modules\heapdump
> node-gyp rebuild


C:\Users\user1\AppData\Roaming\npm\node_modules\strongloop\node_modules\heapdump>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Los proyectos de esta solución se van a compilar de uno en uno. Para habilitar la compilación en paralelo, agregue el modificador "/m".
  heapdump.cc
     Creating library C:\Users\user1\AppData\Roaming\npm\node_modules\strongloop\node_modules\heapdump\build\Release\addon.lib and object C:\Users\user1\AppData\Roamin
  g\npm\node_modules\strongloop\node_modules\heapdump\build\Release\addon.exp
  Generating code
  Finished generating code
  addon.vcxproj -> C:\Users\user1\AppData\Roaming\npm\node_modules\strongloop\node_modules\heapdump\build\Release\\addon.node
  addon.vcxproj -> C:\Users\user1\AppData\Roaming\npm\node_modules\strongloop\node_modules\heapdump\build\Release\addon.pdb (Full PDB)

> bufferutil@1.2.1 install C:\Users\user1\AppData\Roaming\npm\node_modules\strongloop\node_modules\bufferutil
> node-gyp rebuild


C:\Users\user1\AppData\Roaming\npm\node_modules\strongloop\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Los proyectos de esta solución se van a compilar de uno en uno. Para habilitar la compilación en paralelo, agregue el modificador "/m".
  bufferutil.cc
  win_delay_load_hook.c
C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.c(34): error C2373: '__pfnDliNotifyHook2': redefinition; different type modifiers
[C:\Users\user1\AppData\Roaming\npm\node_modules\strongloop\node_modules\bufferutil\build\bufferutil.vcxproj]
  C:\Program Files\Microsoft Visual Studio 14.0\VC\include\delayimp.h(134): note: see declaration of '__pfnDliNotifyHook2'
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\user1\AppData\Roaming\npm\node_modules\strongloop\node_modules\bufferutil
gyp ERR! node -v v6.3.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm WARN install:bufferutil@1.2.1 bufferutil@1.2.1 install: `node-gyp rebuild`
npm WARN install:bufferutil@1.2.1 Exit status 1

> utf-8-validate@1.2.1 install C:\Users\user1\AppData\Roaming\npm\node_modules\strongloop\node_modules\utf-8-validate
> node-gyp rebuild


C:\Users\user1\AppData\Roaming\npm\node_modules\strongloop\node_modules\utf-8-validate>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Los proyectos de esta solución se van a compilar de uno en uno. Para habilitar la compilación en paralelo, agregue el modificador "/m".
  validation.cc
  win_delay_load_hook.c
C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.c(34): error C2373: '__pfnDliNotifyHook2': redefinition; different type modifiers
[C:\Users\user1\AppData\Roaming\npm\node_modules\strongloop\node_modules\utf-8-validate\build\validation.vcxproj]
  C:\Program Files\Microsoft Visual Studio 14.0\VC\include\delayimp.h(134): note: see declaration of '__pfnDliNotifyHook2'
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\user1\AppData\Roaming\npm\node_modules\strongloop\node_modules\utf-8-validate
gyp ERR! node -v v6.3.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm WARN install:utf-8-validate@1.2.1 utf-8-validate@1.2.1 install: `node-gyp rebuild`
npm WARN install:utf-8-validate@1.2.1 Exit status 1

> strong-debugger@1.0.0 install C:\Users\user1\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-debugger
> node-gyp rebuild


C:\Users\user1\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-debugger>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Los proyectos de esta solución se van a compilar de uno en uno. Para habilitar la compilación en paralelo, agregue el modificador "/m".
  mutex-wrap.cc
  debugger.cc
  controller.cc
  worker.cc
  worker-bindings.cc
  win_delay_load_hook.c
C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.c(34): error C2373: '__pfnDliNotifyHook2': redefinition; different type modifiers
[C:\Users\user1\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-debugger\build\debugger.vcxproj]
  C:\Program Files\Microsoft Visual Studio 14.0\VC\include\delayimp.h(134): note: see declaration of '__pfnDliNotifyHook2'
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\user1\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-debugger
gyp ERR! node -v v6.3.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm WARN install:strong-debugger@1.0.0 strong-debugger@1.0.0 install: `node-gyp rebuild`
npm WARN install:strong-debugger@1.0.0 Exit status 1
C:\Users\user1\AppData\Roaming\npm
`-- strongloop@6.0.3
  `-- heapdump@0.3.7

npm WARN optional Skipping failed optional dependency /strongloop/modern-syslog:
npm WARN notsup Not compatible with your operating system or architecture: modern-syslog@1.1.4
npm WARN optional Skipping failed optional dependency /strongloop/strong-supervisor/modern-syslog:
npm WARN notsup Not compatible with your operating system or architecture: modern-syslog@1.1.4

**Comment by batusy** [comment]
Last error:

C:\Users\user1\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-debugger>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Los proyectos de esta solución se van a compilar de uno en uno. Para habilitar la compilación en paralelo, agregue el modificador "/m".
  mutex-wrap.cc
  debugger.cc
  controller.cc
  worker.cc
  worker-bindings.cc
..\src\controller.cc(189): warning C4996: 'v8::Debug::ProcessDebugMessages': was declared deprecated [C:\Users\user1\AppData\Roaming\npm\node_modules\strongloop\node_mo dules\strong-debugger\build\debugger.vcxproj]
  C:\Users\user1\.node-gyp\6.9.1\include\node\v8-debug.h(251): note: see declaration of 'v8::Debug::ProcessDebugMessages'
..\src\controller.cc(196): warning C4996: 'v8::Debug::SetMessageHandler': was declared deprecated [C:\Users\user1\AppData\Roaming\npm\node_modules\strongloop\node_modul es\strong-debugger\build\debugger.vcxproj]
  C:\Users\user1\.node-gyp\6.9.1\include\node\v8-debug.h(178): note: see declaration of 'v8::Debug::SetMessageHandler'
..\src\controller.cc(205): warning C4996: 'v8::Debug::ProcessDebugMessages': was declared deprecated [C:\Users\user1\AppData\Roaming\npm\node_modules\strongloop\node_mo dules\strong-debugger\build\debugger.vcxproj]
  C:\Users\user1\.node-gyp\6.9.1\include\node\v8-debug.h(251): note: see declaration of 'v8::Debug::ProcessDebugMessages'
..\src\controller.cc(206): warning C4996: 'v8::Debug::SetMessageHandler': was declared deprecated [C:\Users\user1\AppData\Roaming\npm\node_modules\strongloop\node_modul es\strong-debugger\build\debugger.vcxproj]
  C:\Users\user1\.node-gyp\6.9.1\include\node\v8-debug.h(178): note: see declaration of 'v8::Debug::SetMessageHandler'
  win_delay_load_hook.cc
LINK : fatal error LNK1194: cannot delay-load 'node.exe' due to import of data symbol '"__declspec(dllimport) const v8::ArrayBuffer::Allocator::`vftable'" (__imp_??_7All ocator@ArrayBuffer@v8@@6B@)'; link without /DELAYLOAD:node.exe [C:\Users\user1\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-debugger\build\debugger.v cxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\user1\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-debugger
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
C:\Users\user1\AppData\Roaming\npm
`-- strongloop@6.0.3
  +-- bufferutil@1.2.1
  | +-- bindings@1.2.1
  | `-- nan@2.4.0
  `-- utf-8-validate@1.2.1

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: modern-syslog@^1.1.2 (node_modules\strongloop\node_modules\modern-syslog):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for modern-syslog@1.1.4: wanted {"os":"!win32","arch":"any"} (current: {"os":"win32","arch":"ia32"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: modern-syslog@^1.x (node_modules\strongloop\node_modules\strong-supervisor\node_modules\modern-syslog):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for modern-syslog@1.1.4: wanted {"os":"!win32","arch":"any"} (current: {"os":"win32","arch":"ia32"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: strong-debugger@1.0.0 (node_modules\strongloop\node_modules\strong-debugger):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: strong-debugger@1.0.0 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

**Comment by sam-github** [comment]
> gyp ERR! stack Error: Python executable "C:\Python34\python.EXE" is v3.4.3, which is not supported by gyp.

Use the right version of python.

In your succeeding log dumps, I have no idea of whether you have in fact corrected the original problem or not, and I can't read them.

The end of your logs however say "SKIPPING OPTIONAL DEPENDENCY", so it appears you only had build issues for modern-syslog, which doesn't work on windows, this is OK and expected, and for strong-debugger, which is unused, so doesn't matter.

Feel free to re-open if there is still an issue.

**Comment by batusy** [comment]
There is an error yet.   I have the correct version of Python 2.7 

-- > Waiting for installers... |Successfully installed Python 2.7

ERROR: 

LINK : fatal error LNK1194: cannot delay-load 'node.exe' due to import of data symbol '"__declspec(dllimport) const v8::ArrayBuffer::Allocator::vftable'" (__imp_??_7All ocator@ArrayBuffer@v8@@6B@)'; link without /DELAYLOAD:node.exe [C:\Users\user1\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-debugger\build\debugger.v cxproj] gyp ERR! build error gyp ERR! stack Error:C:\Program Files\MSBuild\14.0\bin\msbuild.exefailed with exit code: 1 gyp ERR! stack at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23) gyp ERR! stack at emitTwo (events.js:106:13) gyp ERR! stack at ChildProcess.emit (events.js:191:7) gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12) gyp ERR! System Windows_NT 10.0.14393 gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" gyp ERR! cwd C:\Users\user1\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-debugger gyp ERR! node -v v6.9.1 gyp ERR! node-gyp -v v3.4.0 gyp ERR! not ok C:\Users\user1\AppData\Roaming\npm --

**Comment by sam-github** [comment]
strong-debugger is an optional dependency, above is not an error
