### ISSUE TITLE
After deploy current version is not updated

### ISSUE THREAD

**Issue by felipetoffolo1** [strongloop/strong-pm#376]
Sometimes when i make a deploy, the version that is on the current is not the last one
Here is example
![selecao_007](https://cloud.githubusercontent.com/assets/3484842/20428321/9dfa803c-ad6f-11e6-8fe0-781107dbfc5d.png)
  I deployed a new version and in the current is a version form one day before. And if i change the symbolic link manually, it goes back to the old version after restart of the service.

**Comment by seb2086** [comment]
Hello, i have exactly the same issue.

How do you fix it ?

Thx.
