### ISSUE TITLE
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

### ISSUE THREAD

**Issue by ampsarfraz** [strongloop/strong-pm#384]
Loopback Server on remote machine does not start. When I look at the strong-pm.log file. Below is the error message.

The server was working fine and suddenly started having this issue. Can you please help fix the problem?
sl-pm version is 5.2.3

<--- Last few GCs --->

   89760 ms: Scavenge 1399.4 (1457.4) -> 1399.4 (1457.4) MB, 15.9 / 0 ms (+ 4.8 ms in 1 steps since last GC) [allocation failure] [incremental marking delaying mark-sweep].
   91399 ms: Mark-sweep 1399.4 (1457.4) -> 1397.5 (1457.4) MB, 1639.0 / 0 ms (+ 7.3 ms in 2 steps since start of marking, biggest step 4.8 ms) [last resort gc].
   93059 ms: Mark-sweep 1397.5 (1457.4) -> 1400.7 (1457.4) MB, 1660.0 / 0 ms [last resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x35cc017e3ac1 <JS Object>
    1: _initProperties [/usr/lib/node_modules/strong-pm/node_modules/loopback-datasource-juggler/lib/model.js:260] [pc=0x1a0501c2f4a9] (this=0x3f993b9ca71 <a ModelConstructor with map 0x3d9b75f3d781>,data=0x109e45187769 <an Object with map 0x3d9b75f3df11>,options=0x3f993b9cab1 <an Object with map 0x3d9b75f3e0c9>)
    2: constructor(aka ModelBaseClass) [/usr/lib/node_modules/strong-pm/node_modul...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

**Comment by sam-github** [comment]
There isin't enough info in the log for me to see what process is running out of memory. Is it strong-pm itself, or is it your application?

Most likely your application, in which case you would most likely have a memory leak.
