### ISSUE TITLE
How to manage Node worker memory in strong-loop

### ISSUE THREAD

**Issue by satyendra-singh** [strongloop/strong-pm#385]
Hi,
On production I am using strong-pm service to run my node app.
4 workers are running.
I just want to know how i can i increase memory of each worker to avoid process out memory exception.

**Comment by sam-github** [comment]
error log showing exception?

are you sure you don't have a memory leak? Why does your app use so much memory? default memory limits are quite generous.

Where are you running? cloud/hardware/...?

node version?

**Comment by satyendra-singh** [comment]
Hi Sam,
thanx for reply, but actually there is no memory leak.. RPM is very high on my app, so I need to increase memory consumed by memory...
node version is 4.4.0
