### ISSUE TITLE
slc deploy with port forwarding

### ISSUE THREAD

**Issue by eMatsiyana** [strongloop/strong-pm#386]
I have 2 instances on aws ec2.
Server 1 is only accessible from my IP address via SSH.
Server 2 is only accessible via Server 1's IP as per security group configuration.

What I want to do is to slc deploy to server 1 and have everything port forwarded to server 2 which has Strong loop installed.

I can directly deploy to server 2 using slc deploy and it works very well. However, I shouldn't open any ports from any IP except Server 1's IP. Hence I am trying to port forward.

I've tried this:
```
sysctl net.ipv4.ip_forward=1
iptables -t nat -A PREROUTING -p tcp --dport port -j DNAT --to-destination ip:port
iptables -t nat -A POSTROUTING -j MASQUERADE
```
But I get this following when I slc deploy to Server 1's IP address
```
Error connecting to server: { Error: connect EPERM /
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
  code: 'EPERM',
  errno: 'EPERM',
  syscall: 'connect',
  address: '/' }
```
Is it possible to port forward a deployment? 
Is port forwarding even the correct way to deploy to Server 2 via Server 1?

**Comment by sam-github** [comment]
How to do ssh and/or iptables port forwarding is out of scope, here, sorry.

Yes, port forwarding is your only way if you need to access that port.

**Comment by eMatsiyana** [comment]
Thanks for the feedback @sam-github.
Assuming you probably know how I can do this or someone out there is in a position to assist. Would you rather not keep this open so I can be in a position to continue using strong loop?
:)

**Comment by sam-github** [comment]
I don't know how, sorry, I would have told you if I did. I'd google on how to do ssh port forwarding if I needed to do this, but you have to understand this isn't a good place to get ssh or iptables support.

Also, closing it in no way prevents anyone who happens to know how to do this from commenting here to help you out.

**Comment by eMatsiyana** [comment]
I understand. 
Thanks
