### ISSUE TITLE
Problems when deploy a service with parameters 

### ISSUE THREAD

**Issue by masalinas** [strongloop/strong-pm#387]
I have a problem with strong-pm, I build a service correctly inside strong-pm. The package of this service deployed has this script configured:

"scripts": {
      "start": "node_modules/node-red/red.js -s settings.js"
},
strong-pm start correctly red.js but the parameter settings.js is not used. What is wrong?

**Comment by sam-github** [comment]
strong-pm doesn't use the start script, it couldn't inject metrics and other instrumentation if it did.

See point 1 here: https://github.com/strongloop/strong-supervisor#slc-run

I recommend modifying your code so the `start` behaviour is the default.
