### ISSUE TITLE
strong-pm on Windows cannot accept git deployments

### ISSUE THREAD

**Issue by kalanbates** [strongloop/strong-pm#39]
I'm following the demo located @ http://docs.strongloop.com/display/SLC/Deploy+and+manage+an+application
and also the one located @
http://docs.strongloop.com/display/SLC/slc+build.

Commands I executed to get my error (in the order I executed them):
$ git clone https://github.com/strongloop/loopback-example-app
$ cd loopback-example-app/
$ git checkout -b deploy
$ git checkout master
$ git checkout production
$ git clean -x -d  <= This command errored "fatal: clean.requireForce defaults to true and neither -i, -n nor -f given; refusing to clean"
$ slc build --onto deploy --install --commit

In separate terminal
$ slc pm -l 7777

Back in original terminal
$ slc deploy http://localhost:7777/app

Original terminal spool "URL 'http://localhost:7777/app/default' is not valid

ProcessManager Terminal spools
$ slc pm -l 7777
slc pm: listen on 7777, work base is `.strong-pm` with config `c:\dev\lab\strong
ops\tutorials\processmanager\.strong-pm\config`
slc pm: control listening on path `\\?\pipe\c:\dev\lab\strongops\tutorials\proce
ssmanager\pmctl`
Stop current (none)

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT running command git-upload-pack --stateless-rpc --advertise-
refs c:\dev\lab\strongops\tutorials\processmanager\.strong-pm\repo\app\default
    at ChildProcess.<anonymous> (c:\Users\abates\AppData\Roaming\npm\node_module
s\strongloop\node_modules\strong-pm\node_modules\cicada\node_modules\pushover\li
b\info.js:69:28)
    at ChildProcess.emit (events.js:95:17)
    at Process.ChildProcess._handle.onexit (child_process.js:808:12)

Am I doing something wrong or are the docs for the demo inaccurate?

**Comment by sam-github** [comment]
@rmg, this should be fixed in our fork, right?

More to the point, I just deployed with git, and it seemed to work fine.

@cgole moving to verify

@kalanbates I think this is fixed, if you'd like to try it again.

**Comment by cgole** [comment]
verified fixed
