### ISSUE TITLE
Can't create StrongLoop login, only Bluemix

### ISSUE THREAD

**Issue by hanballs** [strongloop/strong-pm#401]
I am unable to get a login to work for strong-pm. The register page brings me to a newsletter signup, which I did. I chose forgot password after this, and my email wasn't registered with strongloop arc. I signed up with Bluemix, and then used that as the credentials and that did not work. Where do I register a login for strongloop arc?

**Comment by DaveYVR** [comment]
In early 2016 the StrongLoop team announced that Arc would reach its end of life within a year. That year has passed, and Arc has been replaced by API Connect. New users cannot register for Arc, and we recommend interested users try out the Essentials edition of API Connect. If you have questions about API Connect, please email reachsl@us.ibm.com or visit this site:
 
https://console.ng.bluemix.net/catalog/services/api-connect?cm_mmc=Earned-_-IBM+Cloud_API+Economy-_-WW_WW-_-StrongLoop+API+Connect+Page_ov49843&cm_mmca1=000000WT&cm_mmca2=10002833&
 
You can also try LoopBack, our Open Source node framework:
 
http://loopback.io/
 
Thanks for reaching out.
