### ISSUE TITLE
I am getting Login page after given the command slc arc

### ISSUE THREAD

**Issue by lincsphere7** [strongloop/strong-pm#404]
Hi ,

I am new Strongloop pm.  I am getting a problem when I am trying to use slc arc. 
It is showing log in page in local host. I do not have an account. When I am trying to register it is routing to https://strongloop.com/register/ url which is not found.

Can you please help me? 

How to use it?

**Comment by vivek-vidhema** [comment]
I have the same issue and found that StrongLoop Arc is no longer under active development, and will soon be deprecated. Arc's features are being included in the IBM API Connect Developer Toolkit: Please use it instead.

**Comment by chiqui3d** [comment]
but IBM is free?

**Comment by sam-github** [comment]
Free for development, like arc.

Also, see https://www.npmjs.com/package/loopback-cli
