### ISSUE TITLE
Deploying (more than 10?) apps to a server: MaxListenersExceededWarning

### ISSUE THREAD

**Issue by notbrain** [strongloop/strong-pm#405]
So I have a hunch that this is because I'm being a bit ridiculous and deploying 13 distinct apps to a 4-vCPU server and it just isn't meant to handle this many apps. Or is it? (They are very low, intermittent load). 

Is this a limit I could increase or would it need to be done inside strong-pm code?

    (node:1684) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
    (node:1684) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit
    (node:1684) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 unpipe listeners added. Use emitter.setMaxListeners() to increase limit
    (node:1684) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 drain listeners added. Use emitter.setMaxListeners() to increase limit

**Comment by sam-github** [comment]
Ignore the warning, it doesn't matter.

**Comment by sam-github** [comment]
https://nodejs.org/api/events.html#events_eventemitter_defaultmaxlisteners for more info. We should probably find the EE in question and up the limit, but don't have time ATM.
