### ISSUE TITLE
"dbg-start"  failed with Error: Cannot load the debugger module. 

### ISSUE THREAD

**Issue by georgefloros** [strongloop/strong-pm#406]
Hi , i have deploy  my API  on a Centos 7 server. 
When i try to attach the debugger on a worker   using the  the following command :

`"slc ctl -C http://<username>:<password>@xxx.xxx.xxx.xxx dbg-start  x.x.xxxx"`

 i get the error : 

`Command "dbg-start" on "http://<username>:<password>@xxx.xxx.xxx.xxx" failed with Error: Cannot load the debugger module. `

Any suggestions ? 
Thnks in advance .

**Comment by sam-github** [comment]
That command was being worked on, but is no longer implemented, or being worked on. Since @bajtos was working on it, node has switched to the inspect protocol, and there have been many other changes.

**Comment by georgefloros** [comment]
@sam-github thank you for your immediate response ! Would be too much , if i asked for your guidance on how i could attach the debugger using strong pm?

**Comment by sam-github** [comment]
https://nodejs.org/en/docs/guides/debugging-getting-started/

You can't use the `--inspect` CLI option, you have to send `SIGUSR1`, as described in the bottom of this section: https://nodejs.org/en/docs/guides/debugging-getting-started/#enable-inspector
