### ISSUE TITLE
module strong-supervisor not found issue with node 6.13.1 

### ISSUE THREAD

**Issue by pwnsrma** [strongloop/strong-pm#410]
After installing strong-pm I can't find **strong-supervisor** module inside strong-pm/node_modules/**strong-runner**/node_modules/

npm install -g strong-pm

Node Version: **6.13.1**

But running the same command with node version as **4.3.1** I can see this module there
 i.e strong-pm/node_modules/strong-runner/node_modules/**strong-supervisor**

what could be the reason?

**Comment by sam-github** [comment]
Probably because of a different version of npm, which puts strong-supervisor at a different level of the hierarchy.
