### ISSUE TITLE
Is This Still Maintained?

### ISSUE THREAD

**Issue by 0X1A** [strongloop/strong-pm#412]
I've just been bit by a litany of bugs, and when attempting to reinstall, pulled a multitude of no longer maintained dependencies.

Is this project still maintained? If not, a deprecation warning on the README would be appreciated.

**Comment by dhmlau** [comment]
@0X1A , I'm sorry that this module is not under active development.  I just updated the README.

**Comment by jhenry9636** [comment]
@dhmlau Can you suggest an alternative? Strongloop PM seemed the most promising. Why has this been deprecated?

**Comment by dhmlau** [comment]
@jhenry9636 , there's no official recommendation on the alternatives because it might be specific to your usage.  However, @mastermunj  commented on another issue https://github.com/strongloop/loopback/issues/3851#issuecomment-378919267:
> Since Loopback is built on top of Express, try going through [this](https://expressjs.com/en/advanced/pm.html).
> We use PM2 for our production servers to run a thread per core.

**Comment by sam-github** [comment]
You can also look at strong-supervisor, https://github.com/strongloop/strong-supervisor
