### ISSUE TITLE
response event listener registration error

### ISSUE THREAD

**Issue by emarteca** [strongloop/strong-pm#420]
Hi all, I've been working on a tool to identify instances of events registered to the wrong object in uses of some JavaScript event-driven APIs, as part of a research project.
The tool flagged [line 40](https://github.com/strongloop/strong-pm/blob/master/test/test-local-deploy.js#L40) in test/test-local-deploy.js, on the registration of the listener for `response`.

The reason I believe this is an error is as follows (from looking at the [nodejs http API documentation](https://nodejs.org/api/http.html#http_class_http_clientrequest)):
the listener for `response` is registered on the return from the [call to `local`](https://github.com/strongloop/strong-pm/blob/master/test/test-local-deploy.js#L32); and this function [returns a server](https://github.com/strongloop/strong-pm/blob/master/test/deploy.js#L74), which is created by a call to [`http.createServer`](https://github.com/strongloop/strong-pm/blob/master/test/deploy.js#L23), which returns an object of type http.Server. 

`response` is an event on http.ClientRequest, and not on http.Server.

Thanks!

**Comment by sam-github** [comment]
You'll have to look more closely at your tool! Sorry, look at this line, https://github.com/strongloop/strong-pm/blob/master/test/deploy.js#L65, any event can be emitted on an EventEmitter, not the just the ones from it's object type. In our case, _we_ emit the response event on the Server, though you/your tool is correct, its not something node core/a normal HTTP Server object would emit.

**Comment by emarteca** [comment]
Ah, this is an edge case I didn't consider yet when building my tool -- I'll have to start tracking the emits too. Thank you! :)
