### ISSUE TITLE
Can't install strong-pm

### ISSUE THREAD

**Issue by shikar** [strongloop/strong-pm#423]
Node V11.15.0
NPM 6.7.0
**sudo npm install -g strong-pm**
> heapdump@0.3.15 install /usr/local/lib/node_modules/strongloop/node_modules/heapdump
> node-gyp rebuild

gyp WARN EACCES current user ("nobody") does not have permission to access the dev dir "/Users/shikar/Library/Caches/node-gyp/14.4.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/strongloop/node_modules/heapdump/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/strongloop/node_modules/heapdump/.node-gyp'
gyp ERR! System Darwin 19.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/strongloop/node_modules/heapdump
gyp ERR! node -v v14.4.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 

**sudo npm install -g strong-pm --unsafe-perm**
more error
Release/obj.target/appmetrics/geni/appmetrics.cpp:664:57: warning: 'v8::Local<v8::Object> v8::Value::ToObject() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
             Local<Value> grandparent = parent->ToObject()->Get(Nan::New<String>(asciiString("parent")).ToLocalChecked());
                                                         ^
In file included from /root/.node-gyp/11.15.0/include/node/node.h:63:0,
                 from Release/obj.target/appmetrics/geni/appmetrics.cpp:21:
/root/.node-gyp/11.15.0/include/node/v8.h:10257:15: note: declared here
 Local<Object> Value::ToObject() const {
               ^~~~~
Release/obj.target/appmetrics/geni/appmetrics.cpp:665:61: warning: 'v8::Local<v8::Object> v8::Value::ToObject() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
             Local<Value> gpfilename = grandparent->ToObject()->Get(Nan::New<String>(asciiString("filename")).ToLocalChecked());
                                                             ^
In file included from /root/.node-gyp/11.15.0/include/node/node.h:63:0,
                 from Release/obj.target/appmetrics/geni/appmetrics.cpp:21:
/root/.node-gyp/11.15.0/include/node/v8.h:10257:15: note: declared here
 Local<Object> Value::ToObject() const {
               ^~~~~
Release/obj.target/appmetrics/geni/appmetrics.cpp:666:108: warning: 'v8::Local<v8::String> v8::Value::ToString() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
             if (gpfilename->IsString() && isAppMetricsFile("launcher.js", toStdString(gpfilename->ToString()))) {
                                                                                                            ^
In file included from /root/.node-gyp/11.15.0/include/node/node.h:63:0,
                 from Release/obj.target/appmetrics/geni/appmetrics.cpp:21:
/root/.node-gyp/11.15.0/include/node/v8.h:10251:15: note: declared here
 Local<String> Value::ToString() const {
               ^~~~~
Release/obj.target/appmetrics/geni/appmetrics.cpp: In function 'bool isGlobalAgentAlreadyLoaded(v8::Local<v8::Object>)':
Release/obj.target/appmetrics/geni/appmetrics.cpp:684:98: warning: 'v8::Local<v8::String> v8::Value::ToString() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
             if (entry->IsString() && isAppMetricsFile("launcher.js", toStdString(entry->ToString()))) {
                                                                                                  ^
In file included from /root/.node-gyp/11.15.0/include/node/node.h:63:0,
                 from Release/obj.target/appmetrics/geni/appmetrics.cpp:21:
/root/.node-gyp/11.15.0/include/node/v8.h:10251:15: note: declared here
 Local<String> Value::ToString() const {
               ^~~~~
Makefile:282: recipe for target 'Release/obj.target/appmetrics/geni/appmetrics.o' failed
make: *** [Release/obj.target/appmetrics/geni/appmetrics.o] Error 1
make: Leaving directory '/usr/lib/node_modules/appmetrics/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:193:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:255:12)
gyp ERR! System Linux 5.6.14-x86_64-linode135
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/appmetrics
gyp ERR! node -v v11.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! appmetrics@3.1.3 install: `node extract_all_binaries.js || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the appmetrics@3.1.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by shikar** [comment]
appmetrics@5.1.1 is ok
How do I replace 3.1.3 to 5.1.1

**Comment by jaircuevajunior** [comment]
Please, reopen this issue, i'm into this aswell
@shikar  - did you get it working? I'm going back to pm2...
