### ISSUE TITLE
Clarification on Strong-PM Config

### ISSUE THREAD

**Issue by bitmage** [strongloop/strong-pm#45]
I can't seem to get file copies working.  The documentation seems nebulous... an example project with a config file and some env files would be helpful.

Here's what I have.  In the strong-deploy root:

```
drwxr-xr-x  4 strong-pm root      4096 Oct 27 16:40 .
drwxr-xr-x 11 root      root      4096 Oct 15 19:45 ..
-rw-r--r--  1 strong-pm root        58 Oct 27 16:40 config
drwxr-xr-x  3 strong-pm root      4096 Oct 16 14:19 repo
-rw-r--r--  1 strong-pm root        17 Oct 27 15:40 staging.env
drwxr-xr-x  7 strong-pm strong-pm 4096 Oct 27 16:26 work
```

In `config`:

```ini
[config-staging]

[config-staging.files]
.env=staging.env
```

In `staging.env`:

```ini
NODE_ENV=staging
```

I'm expecting the staging.env file to get copied over to the work/current/.env when I deploy, but that's not happening.  I'm deploying with:

```
slc deploy http://[remote-ip]:4040/staging master
```

1. How can I get this file to copy?
2. Can we get some verbosity on the deploy command?  I'd like to know at minimum when the deploy completes.  Ideally I would see output detailing the steps it is performing (perhaps only when --verbose).
3. [This comment](https://github.com/strongloop/strong-pm/blob/master/lib/prepare.js#L35) should probably be in documentation [here](http://docs.strongloop.com/display/SLC/Running+Process+Manager#RunningProcessManager-Configuration).
4. More clearly document that `config` is the default name of the PM config file.  It's mentioned [here](https://github.com/strongloop/strong-pm#options) but not [here](http://docs.strongloop.com/display/SLC/Running+Process+Manager#RunningProcessManager-Configuration).

**Comment by bitmage** [comment]
@sam-github this continues to be a problem for me.  I currently have hard coded values in my production config, and I have to re-make these edits every time I deploy.

I would really appreciate help on getting the file copying working.

**Comment by sam-github** [comment]
Please note my comments above, you were not using the `--config` option of `slc deploy`, and you were calling your config `staging` in the git push, but `config-staging` in the config file.

If you show me again your config file, and the command you are using to deploy, and the output of `slc --version`, I will try to reproduce.

**Comment by sam-github** [comment]
Sorry, I reconsidered. Don't use this config file feature. We introduced direct support for remote control of the environment of the managed process in https://github.com/strongloop/strong-pm/pull/47 specifically to obsolete this cumbersome and error-prone editing of config files.

Please see the pmctl documentation: https://github.com/strongloop/strong-pm#slc-pmctl

You can directly set NODE_ENV (or any other env value) to any value you would like, before or after deploy, as you wish. Try it out, should be much better.

**Comment by bitmage** [comment]
Thank you, I will try that now.

**Comment by sam-github** [comment]
Great, tell use how it goes. We hope the env control will really helpful for your use case.

**Comment by bitmage** [comment]
I just did a `npm install -g strongloop` to upgrade.  All of the `pmctl` commands now hang - no output, never exits.  I tried doing `slc pm-install` to finish the upgrade.  Commands still hang.

**Comment by rmg** [comment]
@bitmage did you restart the strong-pm instance you are trying to connect to after upgrading it?

**Comment by bitmage** [comment]
I can't.  The start/stop commands hang.

**Comment by rmg** [comment]
Restarting strong-pm would be through init, so either initctl for upstart or systemctl for systemd.

**Comment by bitmage** [comment]
Ah.  Ok, well I tried rebooting the machine and it didn't come back up.  I have to wait til morning for the sysadmin to restart it now.

Thanks for your help guys.  I'll look again in the morning.

**Comment by rmg** [comment]
Sorry, I was typing on my phone. I meant to spell out the restart commands.
 * Upstart: `initctl restart strong-pm`
 * systemd: `systemctl restart strong-pm`

When re-installing the systemd or Upstart service, it is probably a good idea to reload those job/service/unit configs.
 * Upstart: `initctl reload-configuration`
 * systemd: `systemctl daemon-reload`

All `initctl` and `systemctl` commands generally require root access, so run them in a root shell or with `sudo`.

**Comment by sam-github** [comment]
@bitmage  Has this worked for you yet?

@rmg @crandmck we might need an upgrade guide for strong-pm, its a bit more than the normal `npm install -g strongloop`, so we should document it somewhere.

**Comment by bitmage** [comment]
@sam-github Sorry for the late reply.  Yeah, that's all working perfectly now.  Once we got the server rebooted the upgrade was successful, environment variables are working properly, and my deploy is now fully automated again.

Yay!  Thanks for your help!
