### ISSUE TITLE
Expose environment variable get/set through REST API

### ISSUE THREAD

**Issue by rmg** [strongloop/strong-pm#48]
Proper REST API, where the environment is a modifiable property of the service instance.

Extending functionality from #47

**Comment by sam-github** [comment]
Verify via confirming env-set/get/etc. still work after rewrite.

**Comment by cgole** [comment]
verified 

$ slc pmctl -C http://localhost:7777 env-set PORT=3004
Environment updated: Updated environment, restarting app
$ slc pmctl -C http://localhost:7777 env PORT
Environment variables:
 PORT=3004
Chandrikas-MacBook-Air:loopback1 chandrikagole$ slc pmctl -C http://localhost:7777 env-get PORT
Environment variables:
 PORT=3004
$ slc pmctl -C http://localhost:7777 env-unset PORT
Environment updated: Updated environment, restarting app
$ slc pmctl -C http://localhost:7777 env-get PORT
Environment variables:
  No matching environment variables defined
