### ISSUE TITLE
Create a stable/unique ID in the env for worker use

### ISSUE THREAD

**Issue by sam-github** [strongloop/strong-pm#97]
If each worker had a stable ID, starting from 1, such that when a worker restarts it is given the lowest free ID, it would be possible for each worker, even though it is using node cluster, to listen on a different TCP port, say `process.env.PORT + process.env.STRONGLOOP_CLUSTER_ID`, allowing the loadbalancing to be done externally with nginx. Also, since node 0.11+ supports "exclusive" tcp listens, those ports could be completely private to the worker, though even if they aren't, the worker's port will still be used by only the one worker.

This is a pretty cheap alternative to rewriting node cluster, the other option described https://github.com/strongloop-internal/scrum-nodeops/issues/260

**Comment by rmg** [comment]
Interesting approach. Basically use cluster to provide:
 * convenient IPC
 * a rather elegant solution to coordinating port binding multiple consecutive processes

I wonder what the performance characteristics would be like from this approach vs. cluster's "load balancing".

**Comment by sam-github** [comment]
I think the performance improvements are:

1. v0.10: don't suffer from the problem where connections are delivered to the most recent worker, instead of equally across all workers. this is solved, in theory, with RR in v0.11
2. nginx has better load balancing algorithms:
  - sticky sessions, including having socket.io hitting the same worker as the http, and having the same client on the same worker, most of the time
  - ability to balance across ports based on responsiveness, etc.
3. v0.11: slightly faster connections, as the connections don't have to be accepted by the master, and sent to the worker. hard to know if connection establishment is really noticeable, particularly when HTTP keep-alive is default pretty much everywhere, YMMV

How big an impact any of that will make "depends"

**Comment by ijroth** [comment]
Perhaps we could configure this manually (nginx load balancing vs built-in load balancing) and run a test? If it's better with nginx, we could blog about our results when we release the feature...

**Comment by danielfbm** [comment]
@ijroth hi guys, any feedback on this? I am still trying to get this to work for socket.io. Thanks

**Comment by sam-github** [comment]
Not scheduled. I recommend looking at http://socket.io/docs/using-multiple-nodes/

**Comment by danielfbm** [comment]
@sam-github Hi Sam, thanks. I had to separate my application in order to implement this. Thanks anyway

**Comment by masalinas** [comment]
It's possible use my socket.io apps controlled by strong-pm and proxy with nginx???. Exist any example for that??

**Comment by sam-github** [comment]
Not if you need sticky sessions, no.
